package main

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf16"
)

// utf16LEWithBOM encodes s as UTF-16LE with a BOM — the Windows Notepad
// "Unicode" export format from issue #671.
func utf16LEWithBOM(s string) []byte {
	u := utf16.Encode([]rune(s))
	out := []byte{0xFF, 0xFE}
	for _, r := range u {
		out = append(out, byte(r), byte(r>>8))
	}
	return out
}

// TestIssue671_UTF16TxtNotLabelledTextPlain is the exact scenario from the
// issue: a UTF-16 encoded .txt (Windows export) is rejected as binary by the
// content heuristic, but its MimeType used to stay "text/plain;
// charset=utf-8" from the extension — Kind/Error and MimeType contradicted
// each other on the rejection path. Post-fix, MimeType comes from the same
// source (content sniffing) and is downgraded to octet-stream here.
func TestIssue671_UTF16TxtNotLabelledTextPlain(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "utf16.txt")
	if err := os.WriteFile(p, utf16LEWithBOM("hello world"), 0644); err != nil {
		t.Fatal(err)
	}

	att := readClipboardFileAttachment(p)
	if att.Error == "" {
		t.Fatalf("UTF-16 content must still be rejected as binary (intentional heuristic), got %+v", att)
	}
	if att.Kind != "binary" {
		t.Fatalf("expected Kind=binary, got %q", att.Kind)
	}
	if strings.HasPrefix(att.MimeType, "text/") {
		t.Fatalf("#671 regression: binary-rejected attachment still labelled %q while Kind=%q Error=%q — fields contradict",
			att.MimeType, att.Kind, att.Error)
	}
	if att.MimeType != "application/octet-stream" {
		t.Fatalf("expected sniffed-and-downgraded application/octet-stream, got %q", att.MimeType)
	}
}

// TestIssue671_RenamedImageExtNotTrusted: a .png extension on non-image
// bytes must not keep an "image/png" MimeType — the value now comes from
// content sniffing, same as the Kind/Error decision.
func TestIssue671_RenamedImageExtNotTrusted(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "fake.png")
	// Arbitrary non-image binary payload.
	if err := os.WriteFile(p, []byte{0x00, 0x01, 0x02, 0x03, 0xFE, 0xFF}, 0644); err != nil {
		t.Fatal(err)
	}

	att := readClipboardFileAttachment(p)
	if att.Error == "" {
		t.Fatalf("expected binary rejection, got %+v", att)
	}
	if strings.HasPrefix(att.MimeType, "image/") {
		t.Fatalf("#671 regression: extension-derived %q kept for non-image content", att.MimeType)
	}
	if att.MimeType != "application/octet-stream" {
		t.Fatalf("expected application/octet-stream, got %q", att.MimeType)
	}
}

// TestIssue671_UTF8TextKeepsRicherExtMime: the extension is still honored
// when it AGREES with the content verdict — a real UTF-8 .csv keeps
// text/csv instead of degrading to the sniffed generic text/plain.
func TestIssue671_UTF8TextKeepsRicherExtMime(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "data.csv")
	if err := os.WriteFile(p, []byte("a,b\n1,2\n"), 0644); err != nil {
		t.Fatal(err)
	}

	att := readClipboardFileAttachment(p)
	if att.Error != "" {
		t.Fatalf("UTF-8 CSV must paste as text, got error %q", att.Error)
	}
	if att.Kind != "text" {
		t.Fatalf("expected Kind=text, got %q", att.Kind)
	}
	if !strings.HasPrefix(att.MimeType, "text/csv") {
		t.Fatalf("expected richer extension mime text/csv to be kept, got %q", att.MimeType)
	}
}

// TestIssue671_UTF8TextUnknownExtSniffed: a real UTF-8 text file with an
// unknown extension gets the sniffed text/plain instead of an empty
// MimeType (previously only the extension value was set, empty when
// unknown — the sniffing fallback now guarantees a value).
func TestIssue671_UTF8TextUnknownExtSniffed(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "notes.weirdext")
	if err := os.WriteFile(p, []byte("plain utf-8 text"), 0644); err != nil {
		t.Fatal(err)
	}

	att := readClipboardFileAttachment(p)
	if att.Kind != "text" || att.Error != "" {
		t.Fatalf("expected accepted text, got Kind=%q Error=%q", att.Kind, att.Error)
	}
	if !strings.HasPrefix(att.MimeType, "text/plain") {
		t.Fatalf("expected sniffed text/plain, got %q", att.MimeType)
	}
}

// TestIssue671_ImageBranchUnchanged: an actual image keeps the content-based
// image/* mime and Data payload regardless of extension — regression guard
// that the fix only touched the non-image path.
func TestIssue671_ImageBranchUnchanged(t *testing.T) {
	dir := t.TempDir()
	// 1x1 PNG generated by the stdlib encoder (no handcrafted CRCs).
	var buf bytes.Buffer
	img := image.NewRGBA(image.Rect(0, 0, 1, 1))
	img.Set(0, 0, color.RGBA{R: 255, A: 255})
	if err := png.Encode(&buf, img); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "dot.txt") // image content, text extension
	if err := os.WriteFile(p, buf.Bytes(), 0644); err != nil {
		t.Fatal(err)
	}

	att := readClipboardFileAttachment(p)
	if att.Error != "" {
		t.Fatalf("real image must attach, got error %q", att.Error)
	}
	if att.Kind != "image" {
		t.Fatalf("expected Kind=image (content wins over extension), got %q", att.Kind)
	}
	if !strings.HasPrefix(att.MimeType, "image/png") {
		t.Fatalf("expected content-sniffed image/png, got %q", att.MimeType)
	}
	if att.Data == "" {
		t.Fatal("expected base64 data payload")
	}
}

// TestIssue671_NoSelfContradictionOnAnyPath is the invariant from the issue
// title: whatever the branch, an attachment rejected as binary must never
// carry a text/* MimeType, and an accepted text attachment must always carry
// a text/* MimeType.
func TestIssue671_NoSelfContradictionOnAnyPath(t *testing.T) {
	dir := t.TempDir()
	cases := map[string][]byte{
		"utf8.txt":     []byte("hello"),
		"utf16.txt":    utf16LEWithBOM("hello"),
		"binary.bin":   {0x00, 0x01, 0xFF, 0xFE, 0x7F},
		"misext.csv":   {0xDE, 0xAD, 0xBE, 0xEF, 0x00},
		"misext2.json": utf16LEWithBOM(`{"a":1}`),
	}
	for name, data := range cases {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, data, 0644); err != nil {
			t.Fatal(err)
		}
		att := readClipboardFileAttachment(p)
		if att.Kind == "binary" && strings.HasPrefix(att.MimeType, "text/") {
			t.Errorf("%s: binary rejection with text/* mime %q — fields contradict", name, att.MimeType)
		}
		if att.Kind == "text" && !strings.HasPrefix(att.MimeType, "text/") {
			t.Errorf("%s: accepted text with non-text mime %q — fields contradict", name, att.MimeType)
		}
	}
}
