package memory

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type projectPathHint struct {
	Path        string
	Description string
}

var projectPathHints = []projectPathHint{
	{Path: "cmd/ggcode", Description: "main CLI entrypoint and startup wiring"},
	{Path: "cmd/ggcode-installer", Description: "Go-based installer that downloads release binaries"},
	{Path: "internal/agent", Description: "agent loop, tool execution, and autopilot continuation"},
	{Path: "internal/tui", Description: "Bubble Tea terminal UI, slash commands, and activity views"},
	{Path: "internal/provider", Description: "provider protocol adapters and endpoint runtime selection"},
	{Path: "internal/memory", Description: "project memory and auto-memory loading"},
	{Path: "internal/subagent", Description: "sub-agent spawning, tracking, and coordination"},
	{Path: "internal/tool", Description: "built-in tools exposed to the agent"},
	{Path: "docs", Description: "project documentation and architecture notes"},
	{Path: "npm", Description: "npm wrapper that installs the GitHub Release binary"},
	{Path: "python", Description: "Python wrapper that installs the GitHub Release binary"},
}

// GenerateProjectMemory builds a GGCODE.md document using the current repo state.
func GenerateProjectMemory(root string) (string, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}

	projectName := filepath.Base(absRoot)
	moduleName := detectGoModule(absRoot)
	summary := detectReadmeSummary(absRoot)
	if summary == "" {
		summary = fmt.Sprintf("%s repository", projectName)
	}

	stack := detectTechStack(absRoot)
	importantPaths := detectImportantPaths(absRoot)
	validation := detectValidation(absRoot)
	conventions := detectConventions(absRoot)

	var b strings.Builder
	b.WriteString("# GGCODE.md\n\n")
	b.WriteString("> Generated by `/init` from the current repository snapshot. Review and edit when project conventions change.\n\n")

	b.WriteString("## Project Snapshot\n")
	b.WriteString(fmt.Sprintf("- Name: `%s`\n", projectName))
	if moduleName != "" {
		b.WriteString(fmt.Sprintf("- Module: `%s`\n", moduleName))
	}
	b.WriteString(fmt.Sprintf("- Summary: %s\n", summary))
	if len(stack) > 0 {
		b.WriteString(fmt.Sprintf("- Stack: %s\n", strings.Join(stack, "; ")))
	}
	b.WriteString("\n")

	if len(importantPaths) > 0 {
		b.WriteString("## Important Paths\n")
		for _, line := range importantPaths {
			b.WriteString("- ")
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if len(validation) > 0 {
		b.WriteString("## Validation\n")
		for _, line := range validation {
			b.WriteString("- ")
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if len(conventions) > 0 {
		b.WriteString("## Current Project Conventions\n")
		for _, line := range conventions {
			b.WriteString("- ")
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Working Notes\n")
	b.WriteString("- Add repo-specific coding conventions, testing expectations, and product constraints here.\n")
	b.WriteString("- Keep this file focused on durable guidance, not one-off task plans.\n")

	return b.String(), nil
}

func detectReadmeSummary(root string) string {
	data, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		return ""
	}
	lines := strings.Split(string(data), "\n")
	var paragraph []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			if len(paragraph) > 0 {
				break
			}
			continue
		}
		if strings.HasPrefix(line, "#") {
			continue
		}
		paragraph = append(paragraph, line)
	}
	return strings.Join(paragraph, " ")
}

func detectGoModule(root string) string {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

func detectTechStack(root string) []string {
	var stack []string
	if fileExists(filepath.Join(root, "go.mod")) {
		stack = append(stack, "Go codebase")
	}
	if fileContains(filepath.Join(root, "go.mod"), "github.com/charmbracelet/bubbletea") {
		stack = append(stack, "Bubble Tea / Lip Gloss TUI")
	}
	if fileContains(filepath.Join(root, "README.md"), "MCP") {
		stack = append(stack, "MCP client integration")
	}
	if fileContains(filepath.Join(root, "README.md"), "Plugin System") {
		stack = append(stack, "plugin-based tool extensions")
	}
	if dirExists(filepath.Join(root, "npm")) {
		stack = append(stack, "npm release wrapper")
	}
	if dirExists(filepath.Join(root, "python")) {
		stack = append(stack, "Python release wrapper")
	}
	return stack
}

func detectImportantPaths(root string) []string {
	var paths []string
	for _, hint := range projectPathHints {
		fullPath := filepath.Join(root, filepath.FromSlash(hint.Path))
		if _, err := os.Stat(fullPath); err == nil {
			paths = append(paths, fmt.Sprintf("`%s/` — %s", hint.Path, hint.Description))
		}
	}
	return paths
}

func detectValidation(root string) []string {
	var lines []string
	if fileExists(filepath.Join(root, "go.mod")) {
		lines = append(lines, "`go test ./... && go vet ./...`")
	}
	makefile := filepath.Join(root, "Makefile")
	if fileContains(makefile, "\nbuild:") || fileStartsWith(makefile, "build:") {
		lines = append(lines, "`make build`")
	}
	if fileContains(makefile, "\ntest:") || fileStartsWith(makefile, "test:") {
		lines = append(lines, "`make test`")
	}
	if fileContains(makefile, "\nlint:") || fileStartsWith(makefile, "lint:") {
		lines = append(lines, "`make lint`")
	}
	return lines
}

func detectConventions(root string) []string {
	var lines []string
	if fileContains(filepath.Join(root, "ggcode.example.yaml"), "vendors:") &&
		fileContains(filepath.Join(root, "ggcode.example.yaml"), "endpoint:") {
		lines = append(lines, "Configuration uses `vendor` / `endpoint` / `vendors` rather than the old `provider/providers` schema.")
	}
	if fileContains(filepath.Join(root, "internal/permission/mode.go"), "AutopilotMode") {
		lines = append(lines, "Runtime modes include `supervised`, `plan`, `auto`, `bypass`, and `autopilot`.")
	}
	if len(ProjectMemoryFilenames) > 0 {
		lines = append(lines, fmt.Sprintf("Project memory files loaded at startup: `%s`.", strings.Join(ProjectMemoryFilenames, "`, `")))
	}
	if fileContains(filepath.Join(root, "README.md"), "GitHub Releases as the binary source of truth") {
		lines = append(lines, "Installers use GitHub Releases as the binary source of truth across Go, npm, and Python entrypoints.")
	}
	return lines
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func fileContains(path, needle string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), needle)
}

func fileStartsWith(path, prefix string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.HasPrefix(string(data), prefix)
}
