// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailskit} from '../models';

export function GetConfig():Promise<wailskit.ConfigSnapshot>;

export function GetEndpoints(arg1:string):Promise<Array<wailskit.EndpointInfo>>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPlatform():Promise<string>;

export function GetVendors():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function GetWorkDir():Promise<string>;

export function ListFiles(arg1:string):Promise<Array<Record<string, any>>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveConfig(arg1:Record<string, string>):Promise<void>;

export function SelectDirectory():Promise<string>;
