// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomEndpoint(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCustomEndpoint'](arg1, arg2, arg3, arg4, arg5);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function ApplyImpersonation(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyImpersonation'](arg1, arg2, arg3);
}

export function BindIMAdapter(arg1) {
  return window['go']['main']['App']['BindIMAdapter'](arg1);
}

export function CancelMessage() {
  return window['go']['main']['App']['CancelMessage']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CompleteAnthropicOAuth() {
  return window['go']['main']['App']['CompleteAnthropicOAuth']();
}

export function CompleteMCPOAuth(arg1) {
  return window['go']['main']['App']['CompleteMCPOAuth'](arg1);
}

export function CompleteOnboard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompleteOnboard'](arg1, arg2, arg3, arg4);
}

export function CycleReasoningEffort() {
  return window['go']['main']['App']['CycleReasoningEffort']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DrainLogStream() {
  return window['go']['main']['App']['DrainLogStream']();
}

export function DrainStreamEvents() {
  return window['go']['main']['App']['DrainStreamEvents']();
}

export function FetchModels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2, arg3, arg4);
}

export function ForceReauthMCPServer(arg1) {
  return window['go']['main']['App']['ForceReauthMCPServer'](arg1);
}

export function GetAnthropicOAuthStatus() {
  return window['go']['main']['App']['GetAnthropicOAuthStatus']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentSessionID() {
  return window['go']['main']['App']['GetCurrentSessionID']();
}

export function GetEndpointDetails(arg1, arg2) {
  return window['go']['main']['App']['GetEndpointDetails'](arg1, arg2);
}

export function GetEndpoints(arg1) {
  return window['go']['main']['App']['GetEndpoints'](arg1);
}

export function GetHooks() {
  return window['go']['main']['App']['GetHooks']();
}

export function GetIMPlatformRegistry() {
  return window['go']['main']['App']['GetIMPlatformRegistry']();
}

export function GetImpersonationPresets() {
  return window['go']['main']['App']['GetImpersonationPresets']();
}

export function GetLSPStatus() {
  return window['go']['main']['App']['GetLSPStatus']();
}

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetModelLimits() {
  return window['go']['main']['App']['GetModelLimits']();
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetResolvedEndpoint() {
  return window['go']['main']['App']['GetResolvedEndpoint']();
}

export function GetSessionHistory() {
  return window['go']['main']['App']['GetSessionHistory']();
}

export function GetSessionLimits() {
  return window['go']['main']['App']['GetSessionLimits']();
}

export function GetTeamBoard() {
  return window['go']['main']['App']['GetTeamBoard']();
}

export function GetVendorPresets() {
  return window['go']['main']['App']['GetVendorPresets']();
}

export function GetVendors() {
  return window['go']['main']['App']['GetVendors']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function InitWorkspace(arg1) {
  return window['go']['main']['App']['InitWorkspace'](arg1);
}

export function InstallLSPServer(arg1, arg2) {
  return window['go']['main']['App']['InstallLSPServer'](arg1, arg2);
}

export function IsSharing() {
  return window['go']['main']['App']['IsSharing']();
}

export function IsWorking() {
  return window['go']['main']['App']['IsWorking']();
}

export function LanChatApprovalPolicies() {
  return window['go']['main']['App']['LanChatApprovalPolicies']();
}

export function LanChatApprove(arg1) {
  return window['go']['main']['App']['LanChatApprove'](arg1);
}

export function LanChatMessages() {
  return window['go']['main']['App']['LanChatMessages']();
}

export function LanChatParticipants() {
  return window['go']['main']['App']['LanChatParticipants']();
}

export function LanChatPendingApprovals() {
  return window['go']['main']['App']['LanChatPendingApprovals']();
}

export function LanChatReject(arg1, arg2) {
  return window['go']['main']['App']['LanChatReject'](arg1, arg2);
}

export function LanChatSelf() {
  return window['go']['main']['App']['LanChatSelf']();
}

export function LanChatSend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LanChatSend'](arg1, arg2, arg3, arg4);
}

export function LanChatSetApprovalPolicy(arg1, arg2) {
  return window['go']['main']['App']['LanChatSetApprovalPolicy'](arg1, arg2);
}

export function LanChatSetNick(arg1) {
  return window['go']['main']['App']['LanChatSetNick'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListIMAdapters() {
  return window['go']['main']['App']['ListIMAdapters']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LogoutAnthropicOAuth() {
  return window['go']['main']['App']['LogoutAnthropicOAuth']();
}

export function MuteIMAdapter(arg1, arg2) {
  return window['go']['main']['App']['MuteIMAdapter'](arg1, arg2);
}

export function NeedsOnboard() {
  return window['go']['main']['App']['NeedsOnboard']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function ReadClipboardAttachments() {
  return window['go']['main']['App']['ReadClipboardAttachments']();
}

export function ReadClipboardImage() {
  return window['go']['main']['App']['ReadClipboardImage']();
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RebindIMAdapter(arg1) {
  return window['go']['main']['App']['RebindIMAdapter'](arg1);
}

export function ReconnectMCPServer(arg1) {
  return window['go']['main']['App']['ReconnectMCPServer'](arg1);
}

export function RemoveIMAdapter(arg1) {
  return window['go']['main']['App']['RemoveIMAdapter'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RespondApproval(arg1, arg2) {
  return window['go']['main']['App']['RespondApproval'](arg1, arg2);
}

export function RespondAskUser(arg1, arg2) {
  return window['go']['main']['App']['RespondAskUser'](arg1, arg2);
}

export function SaveA2AEnabled(arg1) {
  return window['go']['main']['App']['SaveA2AEnabled'](arg1);
}

export function SaveAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2, arg3);
}

export function SaveDefaultMode(arg1) {
  return window['go']['main']['App']['SaveDefaultMode'](arg1);
}

export function SaveHooks(arg1) {
  return window['go']['main']['App']['SaveHooks'](arg1);
}

export function TestHookMatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestHookMatch'](arg1, arg2, arg3, arg4);
}

export function SaveIMAdapter(arg1, arg2) {
  return window['go']['main']['App']['SaveIMAdapter'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendMessageWithImages(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithImages'](arg1, arg2);
}

export function SetEndpointLimits(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetEndpointLimits'](arg1, arg2, arg3, arg4);
}

export function SetIMAdapterEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetIMAdapterEnabled'](arg1, arg2);
}

export function SetMCPServerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetMCPServerEnabled'](arg1, arg2);
}

export function SetModelLimits(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetModelLimits'](arg1, arg2, arg3, arg4, arg5);
}

export function SetPermissionMode(arg1) {
  return window['go']['main']['App']['SetPermissionMode'](arg1);
}

export function SetSessionLimits(arg1, arg2) {
  return window['go']['main']['App']['SetSessionLimits'](arg1, arg2);
}

export function StartAnthropicOAuth() {
  return window['go']['main']['App']['StartAnthropicOAuth']();
}

export function StartMCPOAuth(arg1) {
  return window['go']['main']['App']['StartMCPOAuth'](arg1);
}

export function StartShare() {
  return window['go']['main']['App']['StartShare']();
}

export function StopShare() {
  return window['go']['main']['App']['StopShare']();
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}

export function TestEndpointConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestEndpointConnection'](arg1, arg2, arg3);
}

export function TestIMConnection(arg1) {
  return window['go']['main']['App']['TestIMConnection'](arg1);
}

export function ToggleLogStream(arg1) {
  return window['go']['main']['App']['ToggleLogStream'](arg1);
}

export function UnbindIMAdapter(arg1) {
  return window['go']['main']['App']['UnbindIMAdapter'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
