// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailskit} from '../models';

export function AddCustomEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddMCPServer(arg1:Record<string, string>):Promise<void>;

export function ApplyImpersonation(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function CancelMessage():Promise<void>;

export function CompleteOnboard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<wailskit.FullConfig>;

export function GetEndpoints(arg1:string):Promise<Array<wailskit.EndpointInfo>>;

export function GetImpersonationPresets():Promise<Array<wailskit.ImpersonationPresetInfo>>;

export function GetModelInfo():Promise<Record<string, any>>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPlatform():Promise<string>;

export function GetVendorPresets():Promise<Array<wailskit.VendorPresetInfo>>;

export function GetVendors():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function GetWorkDir():Promise<string>;

export function InitWorkspace(arg1:string):Promise<void>;

export function ListFiles(arg1:string):Promise<Array<Record<string, any>>>;

export function ListIMAdapters():Promise<Array<wailskit.IMAdapterInfo>>;

export function ListMCPServers():Promise<Array<wailskit.MCPServerInfo>>;

export function ListSessions():Promise<Array<wailskit.SessionInfo>>;

export function LoadSession(arg1:string):Promise<void>;

export function NeedsOnboard():Promise<boolean>;

export function NewSession():Promise<void>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RemoveIMAdapter(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveIMAdapter(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectWorkspace():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SetIMAdapterEnabled(arg1:string,arg2:boolean):Promise<void>;

export function TestEndpointConnection(arg1:string,arg2:string,arg3:string):Promise<wailskit.TestEndpointResult>;

export function TestIMConnection(arg1:string):Promise<void>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;
