// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function CancelMessage() {
  return window['go']['main']['App']['CancelMessage']();
}

export function CompleteOnboard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompleteOnboard'](arg1, arg2, arg3, arg4);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEndpoints(arg1) {
  return window['go']['main']['App']['GetEndpoints'](arg1);
}

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetVendorPresets() {
  return window['go']['main']['App']['GetVendorPresets']();
}

export function GetVendors() {
  return window['go']['main']['App']['GetVendors']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function InitWorkspace(arg1) {
  return window['go']['main']['App']['InitWorkspace'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListIMAdapters() {
  return window['go']['main']['App']['ListIMAdapters']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NeedsOnboard() {
  return window['go']['main']['App']['NeedsOnboard']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RemoveIMAdapter(arg1) {
  return window['go']['main']['App']['RemoveIMAdapter'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function SaveAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2, arg3);
}

export function SaveIMAdapter(arg1, arg2) {
  return window['go']['main']['App']['SaveIMAdapter'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetIMAdapterEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetIMAdapterEnabled'](arg1, arg2);
}

export function TestIMConnection(arg1) {
  return window['go']['main']['App']['TestIMConnection'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
