// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {wailskit} from '../models';
import {swarm} from '../models';
import {lanchat} from '../models';

export function AddCustomEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddMCPServer(arg1:Record<string, string>):Promise<void>;

export function ApplyImpersonation(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function BindIMAdapter(arg1:string):Promise<void>;

export function CancelMessage():Promise<void>;

export function CheckForUpdates():Promise<Record<string, any>>;

export function CompleteAnthropicOAuth():Promise<void>;

export function CompleteMCPOAuth(arg1:string):Promise<void>;

export function CompleteOnboard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CycleReasoningEffort():Promise<Record<string, any>>;

export function DeleteSession(arg1:string):Promise<void>;

export function DrainLogStream():Promise<string>;

export function DrainStreamEvents():Promise<Array<main.StreamEventEnvelope>>;

export function FetchModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function ForceReauthMCPServer(arg1:string):Promise<boolean>;

export function GetAnthropicOAuthStatus():Promise<boolean>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetConfig():Promise<wailskit.FullConfig>;

export function GetCurrentSessionID():Promise<string>;

export function GetEndpointDetails(arg1:string,arg2:string):Promise<wailskit.EndpointDetails>;

export function GetEndpoints(arg1:string):Promise<Array<wailskit.EndpointInfo>>;

export function LogoutAnthropicOAuth():Promise<void>;

export function GetIMPlatformRegistry():Promise<Array<wailskit.IMPlatformMeta>>;

export function GetImpersonationPresets():Promise<Array<wailskit.ImpersonationPresetInfo>>;

export function GetLSPStatus():Promise<wailskit.LSPStatusResponse>;

export function GetModelInfo():Promise<Record<string, any>>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPlatform():Promise<string>;

export function GetResolvedEndpoint():Promise<wailskit.ResolvedEndpointInfo>;

export function GetSessionHistory():Promise<Array<wailskit.SessionMessage>>;

export function GetTeamBoard():Promise<Array<swarm.TeamBoardSnapshot>>;

export function GetVendorPresets():Promise<Array<wailskit.VendorPresetInfo>>;

export function GetVendors():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function GetWorkDir():Promise<string>;

export function InitWorkspace(arg1:string):Promise<void>;

export function InstallLSPServer(arg1:string,arg2:string):Promise<wailskit.LSPInstallResult>;

export function IsSharing():Promise<boolean>;

export function IsWorking():Promise<boolean>;

export function LanChatApprovalPolicies():Promise<Record<string, string>>;

export function LanChatApprove(arg1:string):Promise<void>;

export function LanChatMessages():Promise<Array<lanchat.Message>>;

export function LanChatParticipants():Promise<Array<lanchat.Participant>>;

export function LanChatPendingApprovals():Promise<Array<lanchat.PendingAgentMsg>>;

export function LanChatReject(arg1:string,arg2:string):Promise<void>;

export function LanChatSelf():Promise<lanchat.Participant>;

export function LanChatSend(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function LanChatSetApprovalPolicy(arg1:string,arg2:string):Promise<void>;

export function LanChatSetNick(arg1:string):Promise<void>;

export function ListFiles(arg1:string):Promise<Array<Record<string, any>>>;

export function ListIMAdapters():Promise<Array<wailskit.IMAdapterInfo>>;

export function ListMCPServers():Promise<Array<wailskit.MCPServerInfo>>;

export function ListSessions():Promise<Array<wailskit.SessionInfo>>;

export function LoadSession(arg1:string):Promise<void>;

export function MuteIMAdapter(arg1:string,arg2:boolean):Promise<void>;

export function NeedsOnboard():Promise<boolean>;

export function NewSession():Promise<string>;

export function ReadClipboardAttachments():Promise<Array<main.ClipboardAttachment>>;

export function ReadClipboardImage():Promise<main.PastedImage>;

export function ReadFileAsBase64(arg1:string):Promise<main.FileBinaryData>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RebindIMAdapter(arg1:string):Promise<void>;

export function ReconnectMCPServer(arg1:string):Promise<boolean>;

export function RemoveIMAdapter(arg1:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondApproval(arg1:string,arg2:string):Promise<void>;

export function RespondAskUser(arg1:string,arg2:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveDefaultMode(arg1:string):Promise<void>;

export function SaveIMAdapter(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectWorkspace():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SendMessageWithImages(arg1:string,arg2:Array<main.PastedImage>):Promise<void>;

export function SetIMAdapterEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetEndpointLimits(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SetMCPServerEnabled(arg1:string,arg2:boolean):Promise<boolean>;

export function SetPermissionMode(arg1:string):Promise<void>;

export function StartMCPOAuth(arg1:string):Promise<wailskit.MCPOAuthStartResult>;

export function StartShare():Promise<main.ShareInfo>;

export function StopShare():Promise<void>;

export function StartAnthropicOAuth():Promise<string>;

export function SwitchModel(arg1:string):Promise<void>;

export function TestEndpointConnection(arg1:string,arg2:string,arg3:string):Promise<wailskit.TestEndpointResult>;

export function TestIMConnection(arg1:string):Promise<void>;

export function ToggleLogStream(arg1:boolean):Promise<void>;

export function UnbindIMAdapter(arg1:string):Promise<void>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;
