// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEndpoints(arg1) {
  return window['go']['main']['App']['GetEndpoints'](arg1);
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetVendors() {
  return window['go']['main']['App']['GetVendors']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
