package commands

func bundledSkills() []*Command {
	return []*Command{
		{
			Name:          "verify",
			DisplayName:   "Verify work",
			Description:   "Prove that a change actually satisfies the request instead of stopping at a plausible-looking fix.",
			WhenToUse:     "Use when code changes are done and you need targeted validation, reproduction checks, or a final confidence pass before concluding.",
			Template:      "Verify the work against the user's actual request. Re-state the expected behavior, choose the smallest existing checks that prove it, and inspect the concrete output instead of assuming success. Prefer focused tests, builds, or direct reproductions over broad ritual validation. If a gap remains, name the exact missing behavior or failed check rather than papering over it.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "debug",
			DisplayName:   "Debug systematically",
			Description:   "Work backward from symptoms to root cause instead of stacking guesses and speculative edits.",
			WhenToUse:     "Use when tests fail, the TUI behaves unexpectedly, a runtime error appears, a command hangs, or behavior does not match expectations.",
			Template:      "Debug systematically. Reproduce the issue first, isolate the failing layer, compare expected versus actual behavior, inspect the smallest relevant logs or code paths, and identify the root cause before editing. Prefer one strong hypothesis at a time. When useful, read `/tmp/ggcode-debug.log`, inspect recent harness or MCP state, and use focused commands to confirm or falsify the next guess.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
			Context:       "fork",
			AllowedTools: []string{
				"read_file",
				"list_directory",
				"search_files",
				"glob",
				"run_command",
				"start_command",
				"read_command_output",
				"wait_command",
				"stop_command",
				"list_commands",
				"git_status",
				"git_diff",
				"git_log",
				"web_fetch",
				"web_search",
			},
		},
		{
			Name:          "simplify",
			DisplayName:   "Simplify design",
			Description:   "Reduce unnecessary complexity before adding more logic.",
			WhenToUse:     "Use when the current approach feels over-engineered or duplicated.",
			Template:      "Simplify the approach before adding more code. Prefer reusing existing helpers, removing duplication, and shrinking the surface area of the solution while preserving correctness.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "update-config",
			DisplayName:   "Update ggcode config",
			Description:   "Safely adjust ggcode.yaml settings, MCP servers, hooks, plugins, and UI preferences without clobbering existing config.",
			WhenToUse:     "Use when the user asks to change ggcode behavior, permissions, MCP setup, hooks, plugins, models, or persistent UI settings.",
			Template:      "Update ggcode configuration carefully. Read the existing config first and merge changes instead of replacing the whole file. ggcode prefers project-local `ggcode.yaml` or `.ggcode/ggcode.yaml` before `~/.ggcode/ggcode.yaml`. Preserve existing sections and env placeholders like `${API_KEY}` rather than writing secrets inline. Common keys include `vendor`, `endpoint`, `vendors`, `model`, `default_mode`, `allowed_dirs`, `tool_permissions`, `mcp_servers`, `plugins`, `hooks.pre_tool_use`, `hooks.post_tool_use`, and `ui.sidebar_visible`. For hook changes, use ggcode's actual hook shape (`match`, `command`, `inject_output`) rather than Claude Code's settings.json schema. For MCP changes, prefer adding or updating `mcp_servers` entries and explain whether reconnect or restart is needed.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "browser-automation",
			DisplayName:   "Use browser automation",
			Description:   "Route browser and website tasks through MCP-backed browser tools instead of pretending browser access exists by default.",
			WhenToUse:     "Use when the user wants to open websites, click elements, fill forms, capture screenshots, inspect console output, or automate browser flows.",
			Template:      "Handle browser tasks through MCP. Start by checking `list_mcp_capabilities` for a browser-oriented MCP server and its tools or prompts. If browser MCP tools are already available, use them directly. If they are not available, state that ggcode does not have built-in browser control and needs a browser automation MCP server first. In interactive sessions, guide the user toward `/mcp` install or the built-in Playwright preset (`b` in the `/mcp` panel), or add an equivalent `mcp_servers` config entry such as `playwright` via `npx -y @playwright/mcp`. Once connected, re-check capabilities and use the discovered MCP tools or MCP prompt-backed skills rather than freehanding web interactions.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "documentation-update",
			DisplayName:   "Update documentation",
			Description:   "Conservatively review user-facing code changes and keep documentation, README content, and release notes synchronized without cluttering docs.",
			WhenToUse:     "Use after changes to features, CLI commands or flags, config options, APIs, user-visible behavior, breaking changes, or release-worthy functionality that may need documentation updates.",
			Template:      "Review documentation impact conservatively. Inspect the current working tree, current branch diff against the default/base branch, or the user-specified commit range. Treat changes as documentation-worthy only when they affect users: new features, CLI commands or flags, config options, APIs, breaking changes, user-visible behavior, setup/installation, or release notes. Skip internal refactors, tests-only changes, minor bug fixes without user impact, typo-only code changes, and performance work with no user-visible effect. Locate existing docs such as README files, `docs/`, `docs/releases/`, platform config for Mintlify/Docusaurus/GitBook/Fumadocs, or linked docs repositories. Read nearby docs first and match their tone, headings, terminology, code block style, frontmatter, and platform conventions. Prefer minimal, strictly additive edits that preserve accurate existing content. For ggcode, consider whether `docs/releases/<tag>.md`, `docs/releases/README.md`, `GGCODE.md`, installer wrapper docs, or command/config docs need updates. If no significant documentation impact exists, say so clearly. Do not create branches, commits, pushes, or PRs unless the user explicitly asks for release or repository automation.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		// --- Harness bundled skills ---
		{
			Name:          "harness-run",
			DisplayName:   "Run task in harness",
			Description:   "Execute a coding task in an isolated harness environment with worktree, checks, and review.",
			WhenToUse:     "Use when the user explicitly asks to run a task in harness mode, or when the auto-run router detects a code-change task and the user confirms. Also use when the user says /harness run or equivalent.",
			Template:      "Run the requested task in harness mode. Use the harness system to create an isolated worktree, execute the coding task with a worker agent, run configured checks, and present the result for review. Steps: 1) Parse the task description from the user's request. 2) Create a harness task with a clear goal. 3) Use `ggcode harness run` or the harness API to start execution. 4) Monitor progress and report results. 5) If checks fail, report the specific failures. 6) If checks pass, inform the user that the result is ready for review.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "harness-review",
			DisplayName:   "Review harness task",
			Description:   "Review and approve or reject harness task results before promotion.",
			WhenToUse:     "Use when a harness task has completed and needs review, or when the user asks to check harness task results, approve, or reject changes.",
			Template:      "Review harness task results. Show the user what was changed, which checks passed/failed, and the evidence. Steps: 1) List completed harness tasks awaiting review. 2) For the selected task, show the diff summary, check results, and any evidence files. 3) Ask the user to approve or reject. 4) If approved, the task becomes promotable. If rejected, note the rejection reason.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "harness-promote",
			DisplayName:   "Promote harness changes",
			Description:   "Promote approved harness task changes from the worktree back to the main branch.",
			WhenToUse:     "Use when harness tasks have been reviewed and approved, and the user wants to merge the changes into the main working tree.",
			Template:      "Promote approved harness task changes. Steps: 1) List promotable tasks (reviewed and approved). 2) For each task, show the changes that will be promoted. 3) Execute the promotion to merge worktree changes into the project root. 4) Report promotion success or any conflicts that need manual resolution.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "harness-diagnose",
			DisplayName:   "Diagnose harness issues",
			Description:   "Diagnose harness task failures, stuck tasks, or configuration problems.",
			WhenToUse:     "Use when a harness task fails, gets stuck, or the user asks about harness health, configuration issues, or why harness is not working as expected.",
			Template:      "Diagnose harness issues systematically. Steps: 1) Run `harness doctor` to check configuration and environment health. 2) Check the specific task's logs and error output. 3) Verify harness.yaml configuration is valid. 4) Check worktree state and git status. 5) Identify the root cause and suggest a fix. Common issues: missing harness.yaml, git not initialized, worktree conflicts, check command failures.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
	}
}
