package commands

func bundledSkills() []*Command {
	return []*Command{
		{
			Name:          "verify",
			DisplayName:   "Verify work",
			Description:   "Prove that a change actually satisfies the request instead of stopping at a plausible-looking fix.",
			WhenToUse:     "Use when code changes are done and you need targeted validation, reproduction checks, or a final confidence pass before concluding.",
			Template:      "Verify the work against the user's actual request. Re-state the expected behavior, choose the smallest existing checks that prove it, and inspect the concrete output instead of assuming success. Prefer focused tests, builds, or direct reproductions over broad ritual validation. If a gap remains, name the exact missing behavior or failed check rather than papering over it.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "debug",
			DisplayName:   "Debug systematically",
			Description:   "Work backward from symptoms to root cause instead of stacking guesses and speculative edits.",
			WhenToUse:     "Use when tests fail, the TUI behaves unexpectedly, a runtime error appears, a command hangs, or behavior does not match expectations.",
			Template:      "Debug systematically. Reproduce the issue first, isolate the failing layer, compare expected versus actual behavior, inspect the smallest relevant logs or code paths, and identify the root cause before editing. Prefer one strong hypothesis at a time. When useful, read `/tmp/ggcode-debug.log`, inspect recent harness or MCP state, and use focused commands to confirm or falsify the next guess.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
			Context:       "fork",
			AllowedTools: []string{
				"read_file",
				"list_directory",
				"search_files",
				"glob",
				"run_command",
				"start_command",
				"read_command_output",
				"wait_command",
				"stop_command",
				"list_commands",
				"git_status",
				"git_diff",
				"git_log",
				"web_fetch",
				"web_search",
			},
		},
		{
			Name:          "simplify",
			DisplayName:   "Simplify design",
			Description:   "Reduce unnecessary complexity before adding more logic.",
			WhenToUse:     "Use when the current approach feels over-engineered or duplicated.",
			Template:      "Simplify the approach before adding more code. Prefer reusing existing helpers, removing duplication, and shrinking the surface area of the solution while preserving correctness.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "update-config",
			DisplayName:   "Update ggcode config",
			Description:   "Safely adjust ggcode.yaml settings, MCP servers, hooks, plugins, and UI preferences without clobbering existing config.",
			WhenToUse:     "Use when the user asks to change ggcode behavior, permissions, MCP setup, hooks, plugins, models, or persistent UI settings.",
			Template:      "Update ggcode configuration carefully. Read the existing config first and merge changes instead of replacing the whole file. ggcode prefers project-local `ggcode.yaml` or `.ggcode/ggcode.yaml` before `~/.ggcode/ggcode.yaml`. Preserve existing sections and env placeholders like `${API_KEY}` rather than writing secrets inline. Common keys include `vendor`, `endpoint`, `vendors`, `model`, `default_mode`, `allowed_dirs`, `tool_permissions`, `mcp_servers`, `plugins`, `hooks.pre_tool_use`, `hooks.post_tool_use`, and `ui.sidebar_visible`. For hook changes, use ggcode's actual hook shape (`match`, `command`, `inject_output`) rather than Claude Code's settings.json schema. For MCP changes, prefer adding or updating `mcp_servers` entries and explain whether reconnect or restart is needed.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
		{
			Name:          "browser-automation",
			DisplayName:   "Use browser automation",
			Description:   "Route browser and website tasks through MCP-backed browser tools instead of pretending browser access exists by default.",
			WhenToUse:     "Use when the user wants to open websites, click elements, fill forms, capture screenshots, inspect console output, or automate browser flows.",
			Template:      "Handle browser tasks through MCP. Start by checking `list_mcp_capabilities` for a browser-oriented MCP server and its tools or prompts. If browser MCP tools are already available, use them directly. If they are not available, state that ggcode does not have built-in browser control and needs a browser automation MCP server first. In interactive sessions, guide the user toward `/mcp` install or the built-in Playwright preset (`b` in the `/mcp` panel), or add an equivalent `mcp_servers` config entry such as `playwright` via `npx -y @playwright/mcp`. Once connected, re-check capabilities and use the discovered MCP tools or MCP prompt-backed skills rather than freehanding web interactions.",
			Source:        SourceBundled,
			LoadedFrom:    LoadedFromBundled,
			UserInvocable: false,
			Enabled:       true,
		},
	}
}
