package agent

// Budget Guard — BAGEN-inspired Budget-Aware Agent Monitoring
//
// Research: "BAGEN: Are LLM Agents Budget-Aware?" (arXiv:2606.00198, May 2026)
// Key insight: frontier LLM agents waste 28-64% of tokens on doomed tasks because
// they never trigger early stopping. BAGEN defines internal budgets as computation
// cost (input + output tokens) and external budgets as action cost (tool execution).
// The leading indicator is the DERIVATIVE of per-step token cost — when recent
// steps cost significantly more than earlier ones (backtracking pattern), the
// trajectory is likely to fail.
//
// This implementation tracks TWO signals per iteration:
//   1. Output token consumption (model generation cost)
//   2. Input token delta (new context content added per step — tool result bloat)
//
// Either signal can trigger escalation detection independently. This catches two
// distinct failure modes:
//   - Output escalation: agent is generating verbose retries (backtracking)
//   - Input delta escalation: agent is adding large tool results repeatedly (re-reading)
//
// DIFFERENCE from existing monitoring systems:
//   - Error streak: counts consecutive failures (reactive)
//   - Confidence scorer: holistic quality score (includes success rate, tool diversity)
//   - Overseer drift: counts iterations without productive action (reactive)
//   - Budget guard: tracks per-iteration TOKEN COST TREND — dual signal (predictive)
//
// The budget guard fires at most once per run. It detects a cost-escalation
// pattern BEFORE the agent runs out of context — giving it a chance to wrap up
// or switch strategy.

import (
	"fmt"
	"strings"
)

const (
	// budgetEscalationFactor: if recent avg cost > overall avg * this factor,
	// the trajectory shows cost escalation (backtracking signal).
	// 1.3 = 30% increase triggers detection (moderate threshold).
	budgetEscalationFactor = 1.3

	// budgetMinSteps: need at least this many steps before evaluating.
	// Too few steps would produce noisy signals.
	budgetMinSteps = 6

	// budgetRecentWindow: number of recent steps to compare against overall average.
	// BAGEN uses 3; we use 3 as well for the same reason: it captures recent
	// behavior without being too sensitive to a single noisy step.
	budgetRecentWindow = 3

	// budgetContextThreshold: only warn when context utilization exceeds this
	// fraction. At low utilization, cost escalation is not a concern — the
	// agent has plenty of context budget to work with.
	budgetContextThreshold = 0.50
)

// budgetGuardState tracks per-iteration token trends to detect
// cost-escalating trajectories that indicate a doomed task.
type budgetGuardState struct {
	// Per-step output token costs (all steps so far)
	stepCosts []int

	// Per-step input token deltas (new tokens added to context per step).
	// Captures tool result bloat — when the agent reads large files repeatedly.
	stepInputDeltas []int

	// Running sums to avoid O(N²) recomputation in computeAvg
	totalOutputSum int
	totalInputSum  int

	// Previous total input tokens (to compute delta on next step)
	prevInputTokens int

	// Total output tokens consumed
	totalConsumed int

	// Whether we've already fired (one warning per run)
	warningGiven bool
}

func newBudgetGuardState() *budgetGuardState {
	return &budgetGuardState{}
}

func (b *budgetGuardState) reset() {
	b.stepCosts = b.stepCosts[:0]
	b.stepInputDeltas = b.stepInputDeltas[:0]
	b.totalOutputSum = 0
	b.totalInputSum = 0
	b.prevInputTokens = 0
	b.totalConsumed = 0
	b.warningGiven = false
}

// recordStep feeds per-iteration token usage into the budget guard.
// BAGEN defines internal budget as computation cost = input + output tokens.
// outputTokens: tokens generated by the model in this iteration.
// inputTokens: total input tokens sent to the model in this iteration.
func (b *budgetGuardState) recordStep(outputTokens, inputTokens int) {
	b.stepCosts = append(b.stepCosts, outputTokens)
	b.totalOutputSum += outputTokens
	b.totalConsumed += outputTokens

	// Track input delta — how much new content was added to context this step.
	// This captures tool result bloat that output-only tracking misses.
	// Skip the first step's delta: it includes the initial context (system
	// prompt + tools + conversation) which is baseline, not bloat.
	if len(b.stepInputDeltas) == 0 {
		b.stepInputDeltas = append(b.stepInputDeltas, 0)
	} else {
		inputDelta := 0
		if inputTokens > b.prevInputTokens {
			inputDelta = inputTokens - b.prevInputTokens
		}
		b.stepInputDeltas = append(b.stepInputDeltas, inputDelta)
		b.totalInputSum += inputDelta
	}
	b.prevInputTokens = inputTokens
}

// computeStats returns overall average, recent average, and whether costs are escalating.
// Uses running sums for O(1) overall average instead of O(N) loop.
func (b *budgetGuardState) computeStats() (overallAvg, recentAvg float64, escalating bool) {
	n := len(b.stepCosts)
	if n == 0 {
		return 0, 0, false
	}

	// Output token stats — O(1) using running sum
	overallAvg, recentAvg = b.computeAvgFromSum(b.totalOutputSum, b.stepCosts)
	outputEscalating := overallAvg > 0 && recentAvg > overallAvg*budgetEscalationFactor

	// Input delta stats (tool result bloat signal) — O(1)
	inputOverall, inputRecent := b.computeAvgFromSum(b.totalInputSum, b.stepInputDeltas)
	inputEscalating := inputOverall > 0 && inputRecent > inputOverall*budgetEscalationFactor

	escalating = outputEscalating || inputEscalating
	return overallAvg, recentAvg, escalating
}

// computeAvgFromSum computes overall and recent averages in O(recentWindow) time.
// Uses the pre-computed running sum for overall average instead of looping
// through the full slice (which was O(N) per call, O(N²) over N iterations).
func (b *budgetGuardState) computeAvgFromSum(totalSum int, costs []int) (overall, recent float64) {
	n := len(costs)
	if n == 0 {
		return 0, 0
	}
	overall = float64(totalSum) / float64(n)

	recentStart := n - budgetRecentWindow
	if recentStart < 0 {
		recentStart = 0
	}
	recentSum := 0
	recentCount := 0
	for i := recentStart; i < n; i++ {
		recentSum += costs[i]
		recentCount++
	}
	if recentCount > 0 {
		recent = float64(recentSum) / float64(recentCount)
	}
	return overall, recent
}

// maybeWarn checks whether the budget guard should inject a warning.
// Fires at most once per run (warningGiven flag).
//
// Parameters:
//   - contextWindow: total context window size (0 if unknown)
//   - currentTokens: current context token count
//
// Returns guidance text if the trajectory shows cost escalation under
// context pressure, or empty string otherwise.
func (b *budgetGuardState) maybeWarn(contextWindow, currentTokens int) string {
	if b.warningGiven {
		return ""
	}

	n := len(b.stepCosts)
	if n < budgetMinSteps {
		return ""
	}

	overallAvg, recentAvg, escalating := b.computeStats()
	if !escalating {
		return ""
	}

	// Only warn when context utilization is significant.
	// At low utilization, even escalating costs are acceptable —
	// the agent has room to work.
	if contextWindow > 0 {
		utilization := float64(currentTokens) / float64(contextWindow)
		if utilization < budgetContextThreshold {
			return ""
		}
	}

	b.warningGiven = true

	// Compute escalation percentage
	escalationPct := 0
	if overallAvg > 0 {
		escalationPct = int((recentAvg/overallAvg - 1) * 100)
	}

	// Project remaining cost based on context budget.
	// Instead of assuming a fixed number of remaining steps (10-n),
	// estimate based on available context budget and per-step cost.
	projectedPerStep := int(recentAvg)

	// Build diagnostic
	var reasons []string
	reasons = append(reasons, fmt.Sprintf("recent steps cost %.0f%% more tokens than earlier steps (%.0f avg → %.0f recent)",
		float64(escalationPct), overallAvg, recentAvg))

	// Include input delta signal if it's also escalating
	inputOverall, inputRecent := b.computeAvgFromSum(b.totalInputSum, b.stepInputDeltas)
	if inputOverall > 0 && inputRecent > inputOverall*budgetEscalationFactor {
		inputPct := int((inputRecent/inputOverall - 1) * 100)
		reasons = append(reasons, fmt.Sprintf("input context growing %.0f%% faster per step (%.0f → %.0f tokens/step)",
			float64(inputPct), inputOverall, inputRecent))
	}

	if contextWindow > 0 {
		utilization := float64(currentTokens) / float64(contextWindow) * 100
		// Estimate steps remaining from context budget
		remainingTokens := contextWindow - currentTokens
		// Total per-step cost = output + input delta (context growth)
		totalPerStep := recentAvg + inputRecent
		if totalPerStep <= 0 {
			totalPerStep = recentAvg
		}
		estimatedStepsRemaining := 2 // minimum
		if totalPerStep > 0 {
			estimatedStepsRemaining = int(float64(remainingTokens) / totalPerStep)
			if estimatedStepsRemaining < 2 {
				estimatedStepsRemaining = 2
			}
		}
		projectedTotal := b.totalConsumed + estimatedStepsRemaining*projectedPerStep
		reasons = append(reasons, fmt.Sprintf("context at %.0f%% (%d/%d tokens)", utilization, currentTokens, contextWindow))
		reasons = append(reasons, fmt.Sprintf("~%d steps remaining at current rate", estimatedStepsRemaining))
		reasons = append(reasons, fmt.Sprintf("projected total output: ~%d tokens if trend continues", projectedTotal))
	}

	reasonStr := "per-step token costs are escalating — a common pattern when the agent is backtracking or stuck"
	if len(reasons) > 0 {
		reasonStr = strings.Join(reasons, "; ")
	}

	return fmt.Sprintf(
		"[budget guard: token cost escalation detected] %s.\n"+
			"Token usage per step is increasing. To work more efficiently within the remaining context budget:\n"+
			"1. Keep responses concise — avoid repeating information already stated\n"+
			"2. Batch related operations into fewer steps instead of one-at-a-time\n"+
			"3. Avoid re-reading files or running searches you've already done\n"+
			"4. Focus on the most direct path to completing the current task",
		reasonStr,
	)
}
