package agent

// Budget Guard — BAGEN-inspired Budget-Aware Agent Monitoring
//
// Research: "BAGEN: Are LLM Agents Budget-Aware?" (arXiv:2606.00198, May 2026)
// Key insight: frontier LLM agents waste 28-64% of tokens on doomed tasks because
// they never trigger early stopping. The leading indicator is the DERIVATIVE of
// per-step token cost — when recent steps cost significantly more than earlier
// ones (backtracking pattern), the trajectory is likely to fail.
//
// This implementation tracks per-iteration output token consumption in a rolling
// window. When recent average output exceeds the overall average by a threshold
// AND context utilization is high, we inject a "budget awareness" message.
//
// DIFFERENCE from existing monitoring systems:
//   - Error streak: counts consecutive failures (reactive)
//   - Confidence scorer: holistic quality score (includes success rate, tool diversity)
//   - Overseer drift: counts iterations without productive action (reactive)
//   - Budget guard: tracks per-iteration TOKEN COST TREND (predictive)
//
// The budget guard fires at most once per run. It detects a cost-escalation
// pattern BEFORE the agent runs out of context — giving it a chance to wrap up
// or switch strategy.

import (
	"fmt"
	"strings"
)

const (
	// budgetEscalationFactor: if recent avg cost > overall avg * this factor,
	// the trajectory shows cost escalation (backtracking signal).
	// 1.3 = 30% increase triggers detection (moderate threshold).
	budgetEscalationFactor = 1.3

	// budgetMinSteps: need at least this many steps before evaluating.
	// Too few steps would produce noisy signals.
	budgetMinSteps = 6

	// budgetRecentWindow: number of recent steps to compare against overall average.
	// BAGEN uses 3; we use 3 as well for the same reason: it captures recent
	// behavior without being too sensitive to a single noisy step.
	budgetRecentWindow = 3

	// budgetContextThreshold: only warn when context utilization exceeds this
	// fraction. At low utilization, cost escalation is not a concern — the
	// agent has plenty of context budget to work with.
	budgetContextThreshold = 0.50
)

// budgetGuardState tracks per-iteration output token trends to detect
// cost-escalating trajectories that indicate a doomed task.
type budgetGuardState struct {
	// Per-step output token costs (all steps so far)
	stepCosts []int

	// Total tokens consumed (output only)
	totalConsumed int

	// Whether we've already fired (one warning per run)
	warningGiven bool
}

func newBudgetGuardState() *budgetGuardState {
	return &budgetGuardState{}
}

func (b *budgetGuardState) reset() {
	b.stepCosts = b.stepCosts[:0]
	b.totalConsumed = 0
	b.warningGiven = false
}

// recordStep feeds per-iteration token usage into the budget guard.
// outputTokens: tokens generated by the model in this iteration.
func (b *budgetGuardState) recordStep(outputTokens int) {
	b.stepCosts = append(b.stepCosts, outputTokens)
	b.totalConsumed += outputTokens
}

// computeStats returns overall average, recent average, and whether costs are escalating.
func (b *budgetGuardState) computeStats() (overallAvg, recentAvg float64, escalating bool) {
	n := len(b.stepCosts)
	if n == 0 {
		return 0, 0, false
	}

	// Overall average
	total := 0
	for _, c := range b.stepCosts {
		total += c
	}
	overallAvg = float64(total) / float64(n)

	// Recent average (last budgetRecentWindow steps)
	recentStart := n - budgetRecentWindow
	if recentStart < 0 {
		recentStart = 0
	}
	recentSum := 0
	recentCount := 0
	for i := recentStart; i < n; i++ {
		recentSum += b.stepCosts[i]
		recentCount++
	}
	if recentCount > 0 {
		recentAvg = float64(recentSum) / float64(recentCount)
	}

	// Escalating: recent average is significantly higher than overall
	if overallAvg > 0 {
		escalating = recentAvg > overallAvg*budgetEscalationFactor
	}

	return overallAvg, recentAvg, escalating
}

// maybeWarn checks whether the budget guard should inject a warning.
// Fires at most once per run (warningGiven flag).
//
// Parameters:
//   - contextWindow: total context window size (0 if unknown)
//   - currentTokens: current context token count
//
// Returns guidance text if the trajectory shows cost escalation under
// context pressure, or empty string otherwise.
func (b *budgetGuardState) maybeWarn(contextWindow, currentTokens int) string {
	if b.warningGiven {
		return ""
	}

	n := len(b.stepCosts)
	if n < budgetMinSteps {
		return ""
	}

	overallAvg, recentAvg, escalating := b.computeStats()
	if !escalating {
		return ""
	}

	// Only warn when context utilization is significant.
	// At low utilization, even escalating costs are acceptable —
	// the agent has room to work.
	if contextWindow > 0 {
		utilization := float64(currentTokens) / float64(contextWindow)
		if utilization < budgetContextThreshold {
			return ""
		}
	}

	b.warningGiven = true

	// Compute escalation percentage
	escalationPct := 0
	if overallAvg > 0 {
		escalationPct = int((recentAvg/overallAvg - 1) * 100)
	}

	// Project remaining cost based on recent trend
	// (BAGEN's projection: consumed + est_remaining * recent_avg)
	projectedPerStep := int(recentAvg)

	// Build diagnostic
	var reasons []string
	reasons = append(reasons, fmt.Sprintf("recent steps cost %.0f%% more tokens than earlier steps (%.0f avg → %.0f recent)",
		float64(escalationPct), overallAvg, recentAvg))

	if contextWindow > 0 {
		utilization := float64(currentTokens) / float64(contextWindow) * 100
		remainingEst := 10 - n
		if remainingEst < 2 {
			remainingEst = 2
		}
		projectedTotal := b.totalConsumed + remainingEst*projectedPerStep
		reasons = append(reasons, fmt.Sprintf("context at %.0f%% (%d/%d tokens)", utilization, currentTokens, contextWindow))
		reasons = append(reasons, fmt.Sprintf("projected total output: ~%d tokens if trend continues", projectedTotal))
	}

	reasonStr := "per-step token costs are escalating — a common pattern when the agent is backtracking or stuck"
	if len(reasons) > 0 {
		reasonStr = strings.Join(reasons, "; ")
	}

	return fmt.Sprintf(
		"[budget guard: token cost escalation detected] %s.\n"+
			"This trajectory is consuming increasing tokens per step, which often indicates "+
			"backtracking or an approach that isn't converging. Consider:\n"+
			"1. Summarize what you've accomplished so far\n"+
			"2. Identify the specific blocker preventing progress\n"+
			"3. Switch to a more targeted approach (fewer, smaller operations)\n"+
			"4. If the task cannot be completed, report what's blocking it instead of continuing to consume budget",
		reasonStr,
	)
}
