package agent

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGeneratedArtifactState_LockFile(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/go.sum")
	if hint == "" {
		t.Fatal("expected warning for go.sum")
	}
	if !contains(hint, "go mod tidy") {
		t.Errorf("expected 'go mod tidy' suggestion, got: %s", hint)
	}
	if !contains(hint, "lock file") {
		t.Errorf("expected 'lock file' mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_PackageLockJson(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/package-lock.json")
	if hint == "" {
		t.Fatal("expected warning for package-lock.json")
	}
	if !contains(hint, "npm install") {
		t.Errorf("expected 'npm install' suggestion, got: %s", hint)
	}
}

func TestGeneratedArtifactState_CargoLock(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/Cargo.lock")
	if hint == "" {
		t.Fatal("expected warning for Cargo.lock")
	}
	if !contains(hint, "cargo build") {
		t.Errorf("expected 'cargo build' suggestion, got: %s", hint)
	}
}

func TestGeneratedArtifactState_VendoredFile(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/vendor/github.com/pkg/errors/errors.go")
	if hint == "" {
		t.Fatal("expected warning for vendored file")
	}
	if !contains(hint, "vendored") {
		t.Errorf("expected 'vendored' mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_NodeModules(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/node_modules/react/index.js")
	if hint == "" {
		t.Fatal("expected warning for node_modules file")
	}
	if !contains(hint, "vendored") || !contains(hint, "node_modules") {
		t.Errorf("expected vendored/node_modules mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_ProtobufGenerated(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/api/user.pb.go")
	if hint == "" {
		t.Fatal("expected warning for .pb.go file")
	}
	if !contains(hint, "protobuf") || !contains(hint, "protoc") {
		t.Errorf("expected protobuf/protoc mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_MockGenerated(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/mocks/repo.mocks.go")
	if hint == "" {
		t.Fatal("expected warning for .mocks.go file")
	}
	if !contains(hint, "mock") {
		t.Errorf("expected mock mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_ZzGenerated(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/zz_generated_deepcopy.go")
	if hint == "" {
		t.Fatal("expected warning for zz_generated file")
	}
	if !contains(hint, "controller-gen") {
		t.Errorf("expected controller-gen mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_MinifiedJS(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/dist/bundle.min.js")
	if hint == "" {
		t.Fatal("expected warning for .min.js file")
	}
	if !contains(hint, "minified") {
		t.Errorf("expected minified mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_DoNotEditHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "generated_code.go")
	content := "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage main\n"
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	g := newGeneratedArtifactState()
	hint := g.checkGeneratedArtifact(path)
	if hint == "" {
		t.Fatal("expected warning for DO NOT EDIT file")
	}
	if !contains(hint, "DO NOT EDIT") {
		t.Errorf("expected DO NOT EDIT mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_AutogeneratedHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "auto_gen.py")
	content := "# This file is auto-generated. Do not modify.\nprint('hello')\n"
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	g := newGeneratedArtifactState()
	hint := g.checkGeneratedArtifact(path)
	if hint == "" {
		t.Fatal("expected warning for auto-generated file")
	}
}

func TestGeneratedArtifactState_NormalFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "main.go")
	content := "package main\n\nfunc main() {}\n"
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	g := newGeneratedArtifactState()
	hint := g.checkGeneratedArtifact(path)
	if hint != "" {
		t.Errorf("expected no warning for normal file, got: %s", hint)
	}
}

func TestGeneratedArtifactState_FiresOncePerFile(t *testing.T) {
	g := newGeneratedArtifactState()

	hint1 := g.checkGeneratedArtifact("/project/go.sum")
	if hint1 == "" {
		t.Fatal("expected first warning")
	}

	hint2 := g.checkGeneratedArtifact("/project/go.sum")
	if hint2 != "" {
		t.Error("expected no duplicate warning for same file")
	}
}

func TestGeneratedArtifactState_ResetClearsWarning(t *testing.T) {
	g := newGeneratedArtifactState()

	hint1 := g.checkGeneratedArtifact("/project/go.sum")
	if hint1 == "" {
		t.Fatal("expected first warning")
	}

	g.reset()

	hint2 := g.checkGeneratedArtifact("/project/go.sum")
	if hint2 == "" {
		t.Fatal("expected warning after reset")
	}
}

func TestGeneratedArtifactState_EmptyPath(t *testing.T) {
	g := newGeneratedArtifactState()
	if hint := g.checkGeneratedArtifact(""); hint != "" {
		t.Errorf("expected empty hint for empty path, got: %s", hint)
	}
}

func TestGeneratedArtifactState_CaseInsensitivePath(t *testing.T) {
	g := newGeneratedArtifactState()

	// Lock file with uppercase letters in path
	hint := g.checkGeneratedArtifact("/Project/GO.SUM")
	// Should NOT match because lockFileSuggestions uses lowercase base name
	// The function lowercases the path, so it should match
	if hint == "" {
		// "GO.SUM" lowercased to "go.sum" should match
		t.Error("expected warning for GO.SUM (case-insensitive)")
	}
}

func TestGeneratedArtifactState_MultipleDifferentFiles(t *testing.T) {
	g := newGeneratedArtifactState()

	// First file warns
	hint1 := g.checkGeneratedArtifact("/project/go.sum")
	if hint1 == "" {
		t.Fatal("expected warning for go.sum")
	}

	// Different lock file also warns
	hint2 := g.checkGeneratedArtifact("/project/package-lock.json")
	if hint2 == "" {
		t.Fatal("expected warning for package-lock.json")
	}
}

func TestGeneratedArtifactState_GenGoFile(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/types.gen.go")
	if hint == "" {
		t.Fatal("expected warning for .gen.go file")
	}
	if !contains(hint, "generated-artifact") || !contains(hint, "generator") {
		t.Errorf("expected generator mention, got: %s", hint)
	}
}

func TestGeneratedArtifactState_PipfileLock(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/Pipfile.lock")
	if hint == "" {
		t.Fatal("expected warning for Pipfile.lock")
	}
}

func TestGeneratedArtifactState_FlakeLock(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/flake.lock")
	if hint == "" {
		t.Fatal("expected warning for flake.lock")
	}
	if !contains(hint, "nix flake") {
		t.Errorf("expected nix flake suggestion, got: %s", hint)
	}
}

func TestGeneratedArtifactState_ThirdParty(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/third_party/lib/utils.cpp")
	if hint == "" {
		t.Fatal("expected warning for third_party file")
	}
}

func TestGeneratedArtifactState_SourceMapFile(t *testing.T) {
	g := newGeneratedArtifactState()

	hint := g.checkGeneratedArtifact("/project/dist/bundle.map.js")
	if hint == "" {
		t.Fatal("expected warning for .map.js file")
	}
}
