package agent

// Generated Artifact / Lock File Edit Warning
//
// Research basis: A common failure mode in AI coding agents is editing files
// that should never be manually modified. These include:
//
//   1. Lock files (go.sum, package-lock.json, yarn.lock, Cargo.lock, etc.)
//      — these should be regenerated by the package manager, not hand-edited.
//   2. Code-generated files (*.pb.go, *_gen.go, zz_generated*, *.generated.*)
//      — these are overwritten by code generators (protoc, mockgen, etc.)
//   3. Vendored/third-party files (vendor/, node_modules/)
//      — these should be fixed upstream, not patched locally.
//   4. Files with "DO NOT EDIT" headers — a universal convention for generated
//      code that agents frequently ignore.
//   5. Minified files (*.min.js, *.min.css) — impractical to edit by hand.
//
// Competitive landscape:
//   - Claude Code: no detection; the agent happily edits go.sum line by line
//   - Cursor: no detection; Composer will edit vendored files
//   - Aider: respects .aiderignore but doesn't warn in real-time
//   - OpenHands: no generated-file awareness
//   - Devin: has some awareness via its review step but not pre-edit
//
// ggcode's approach: deterministic, zero-LLM-cost detection at post-edit time.
// The guard fires once per file per run and injects a targeted suggestion
// (e.g., "run `go mod tidy` instead of editing go.sum"). It does NOT block
// the edit — the agent may have a valid reason — but it raises awareness so
// the agent can choose the correct tool for the job.

import (
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/topcheer/ggcode/internal/debug"
)

// generatedArtifactState tracks which files have already been warned.
type generatedArtifactState struct {
	mu     sync.Mutex
	warned map[string]bool
}

func newGeneratedArtifactState() *generatedArtifactState {
	return &generatedArtifactState{
		warned: make(map[string]bool),
	}
}

func (g *generatedArtifactState) reset() {
	g.mu.Lock()
	g.warned = make(map[string]bool)
	g.mu.Unlock()
}

// lockFileSuggestions maps lowercase lock file names to suggested
// regeneration commands. Keys are lowercase because the path is normalized
// to lowercase before lookup.
var lockFileSuggestions = map[string]string{
	"go.sum":            "go mod tidy",
	"package-lock.json": "npm install",
	"yarn.lock":         "yarn install",
	"pnpm-lock.yaml":    "pnpm install",
	"bun.lockb":         "bun install",
	"cargo.lock":        "cargo build",
	"composer.lock":     "composer install",
	"gemfile.lock":      "bundle install",
	"poetry.lock":       "poetry lock",
	"uv.lock":           "uv lock",
	"pipfile.lock":      "pipenv lock",
	"mix.lock":          "mix deps.get",
	"flake.lock":        "nix flake update",
}

// vendoredDirMarkers identifies directory segments that indicate vendored code.
var vendoredDirMarkers = []string{
	"vendor/",
	"node_modules/",
	"third_party/",
	"third-party/",
	".bundle/",
}

// generatedFilePatterns matches file names that are typically code-generated.
var generatedFilePatterns = []string{
	".pb.go",        // protobuf
	".pb.gw.go",     // protobuf gateway
	"_gen.go",       // code generation (mockgen, etc.)
	".gen.go",       // code generation
	".generated.go", // code generation
	"zz_generated_", // Kubernetes code generation
	".gen.",         // generic generated (.gen.ts, .gen.py, etc.)
	".pb.cc",        // protobuf C++
	".pb.h",         // protobuf C++
	"_generated.",   // generic generated suffix
	".mocks.go",     // mock generation
	".mock.go",      // mock generation
	".min.js",       // minified JS
	".min.css",      // minified CSS
	".map.js",       // source maps
	".map.css",      // source maps
}

// checkGeneratedArtifact returns a non-empty warning if the given file path
// targets a generated artifact, lock file, or vendored code. Returns "" if
// the file is a normal source file or if a warning was already issued for it.
func (g *generatedArtifactState) checkGeneratedArtifact(path string) string {
	if path == "" {
		return ""
	}

	g.mu.Lock()
	alreadyWarned := g.warned[path]
	if !alreadyWarned {
		g.warned[path] = true
	}
	g.mu.Unlock()
	if alreadyWarned {
		return ""
	}

	normalized := strings.ToLower(filepath.ToSlash(path))
	base := filepath.Base(normalized)

	// 1. Lock files — suggest regeneration command.
	if cmd, ok := lockFileSuggestions[base]; ok {
		debug.Log("artifact-guard", "lock file edit detected: %s (suggest: %s)", path, cmd)
		return "[generated-artifact] " + base + " is a lock file. Run `" + cmd + "` to regenerate it."
	}

	// 2. Vendored/third-party directories.
	for _, marker := range vendoredDirMarkers {
		if strings.Contains(normalized, "/"+marker) || strings.HasPrefix(normalized, marker) {
			debug.Log("artifact-guard", "vendored file edit detected: %s (marker: %s)", path, marker)
			return "[generated-artifact] File in vendored directory (" + marker + "). Fix upstream, not here."
		}
	}

	// 3. Generated file patterns.
	for _, pattern := range generatedFilePatterns {
		if strings.Contains(base, pattern) {
			suggestion := generatedFileSuggestion(base, path)
			debug.Log("artifact-guard", "generated file edit detected: %s (pattern: %s)", path, pattern)
			return "[generated-artifact] Code-generated file (" + pattern + "). Edits overwritten by generator. " + suggestion
		}
	}

	// 4. "DO NOT EDIT" header detection — read the first few lines of the file.
	if warning := checkDoNotEditHeader(path); warning != "" {
		debug.Log("artifact-guard", "DO NOT EDIT header detected: %s", path)
		return warning
	}

	return ""
}

// checkDoNotEditHeader reads the first ~500 bytes of a file and checks for
// the universal "DO NOT EDIT" convention used by code generators.
func checkDoNotEditHeader(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	// Only check the first 500 bytes — the header is always at the top.
	header := string(data[:min(len(data), 500)])
	headerLower := strings.ToLower(header)

	// Common variants:
	//   "Code generated ... DO NOT EDIT."
	//   "DO NOT EDIT"
	//   "Autogenerated ... do not modify"
	//   "This file is generated ... do not edit"
	if strings.Contains(headerLower, "do not edit") {
		return "[Generated artifact warning] This file has a \"DO NOT EDIT\" header, indicating it is auto-generated. " +
			"Edits will be overwritten when the generator runs again. Modify the source template or generator instead."
	}
	if strings.Contains(headerLower, "auto-generated") || strings.Contains(headerLower, "autogenerated") {
		if strings.Contains(headerLower, "do not modify") || strings.Contains(headerLower, "do not change") {
			return "[Generated artifact warning] This file is marked as auto-generated and should not be manually modified. " +
				"Edits will be overwritten. Modify the source template or generator instead."
		}
	}

	return ""
}

// generatedFileSuggestion returns a context-aware suggestion for generated files.
func generatedFileSuggestion(base, fullPath string) string {
	switch {
	case strings.Contains(base, ".pb."):
		return "For protobuf files, modify the .proto source and run `protoc` (or `buf generate`) to regenerate."
	case strings.Contains(base, ".mock"):
		return "For mock files, modify the source interface and re-run the mock generator (e.g., `mockgen`, `moq`)."
	case strings.Contains(base, "zz_generated_"):
		return "For Kubernetes generated files, modify the API types and re-run `controller-gen` or `code-generator`."
	case strings.Contains(base, ".min."):
		return "For minified files, edit the unminified source and re-run the build/bundler."
	default:
		return "Modify the source file and re-run the code generator."
	}
}
