package agent

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckMissingTestCompanion_NewFileWithTests(t *testing.T) {
	dir := t.TempDir()
	testFile := filepath.Join(dir, "existing_test.go")
	if err := os.WriteFile(testFile, []byte("package mypkg\n"), 0644); err != nil {
		t.Fatal(err)
	}

	src := `package mypkg

func Process(s string) string {
	return s + "!"
}

func Validate(n int) bool {
	return n > 0
}
`
	warning := checkMissingTestCompanion(filepath.Join(dir, "process.go"), "", src)
	if warning != "" {
		t.Errorf("expected no warning when test file exists, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_NewFileNoTests(t *testing.T) {
	dir := t.TempDir()

	src := `package mypkg

func Process(s string) string {
	return s + "!"
}

func Validate(n int) bool {
	return n > 0
}

func Transform(data []byte) []byte {
	return data
}
`
	warning := checkMissingTestCompanion(filepath.Join(dir, "process.go"), "", src)
	if warning == "" {
		t.Errorf("expected warning for new file without test companion")
	}
}

func TestCheckMissingTestCompanion_NewFileTooSmall(t *testing.T) {
	dir := t.TempDir()

	src := `package mypkg

func Tiny() int { return 1 }
`
	warning := checkMissingTestCompanion(filepath.Join(dir, "tiny.go"), "", src)
	if warning != "" {
		t.Errorf("expected no warning for tiny new file, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_ExistingFileNewExportedFunc(t *testing.T) {
	dir := t.TempDir()

	old := `package mypkg

func Existing() int { return 0 }
`

	newSrc := `package mypkg

func Existing() int { return 0 }

func NewFeature(x int) int {
	return x * 2
}
`
	warning := checkMissingTestCompanion(filepath.Join(dir, "feature.go"), old, newSrc)
	if warning == "" {
		t.Errorf("expected warning for new exported func without test companion")
	}
	if !strings.Contains(warning, "NewFeature") {
		t.Errorf("warning should mention NewFeature, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_ExistingFileNoNewFuncs(t *testing.T) {
	dir := t.TempDir()

	old := `package mypkg

func Existing() int { return 0 }
`

	newSrc := `package mypkg

func Existing() int {
	return 42
}
`
	warning := checkMissingTestCompanion(filepath.Join(dir, "feature.go"), old, newSrc)
	if warning != "" {
		t.Errorf("expected no warning when no new exported funcs, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_SkipsTestFiles(t *testing.T) {
	dir := t.TempDir()

	src := `package mypkg

func TestSomething(t *testing.T) {
	// test code
}
`
	warning := checkMissingTestCompanion(filepath.Join(dir, "foo_test.go"), "", src)
	if warning != "" {
		t.Errorf("expected no warning for _test.go file, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_SkipsNonGoFiles(t *testing.T) {
	warning := checkMissingTestCompanion("script.py", "", "def foo():\n    pass\n")
	if warning != "" {
		t.Errorf("expected no warning for non-Go file, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_SkipsVendorPaths(t *testing.T) {
	dir := t.TempDir()
	vendorDir := filepath.Join(dir, "vendor", "pkg")
	if err := os.MkdirAll(vendorDir, 0755); err != nil {
		t.Fatal(err)
	}

	src := `package pkg

func VendorFunc(s string) string {
	return s
}
`
	warning := checkMissingTestCompanion(filepath.Join(vendorDir, "vendor.go"), "", src)
	if warning != "" {
		t.Errorf("expected no warning for vendor path, got: %s", warning)
	}
}

func TestCheckMissingTestCompanion_SkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()

	src := `// Code generated by protoc. DO NOT EDIT.

package mypkg

func GeneratedFunc(s string) string {
	return s + "!"
}
`
	warning := CheckMissingTestCompanionWithFS(filepath.Join(dir, "gen.go"), "", src)
	if warning != "" {
		t.Errorf("expected no warning for generated file, got: %s", warning)
	}
}

func TestFindExportedFuncs(t *testing.T) {
	// nil ast
	got := findExportedFuncs(nil)
	if got != nil {
		t.Errorf("expected nil for nil ast, got %v", got)
	}

	// mixed exported and unexported
	src := `package p
func Exported() {}
func unexported() {}
func TestX(t *testing.T) {}
func init() {}
`
	fset := token.NewFileSet()
	astFile, err := parser.ParseFile(fset, "", src, 0)
	if err != nil {
		t.Fatal(err)
	}
	got = findExportedFuncs(astFile)
	if len(got) != 1 || got[0] != "Exported" {
		t.Errorf("expected [Exported], got %v", got)
	}
}

func TestCountSubstantiveGoLines(t *testing.T) {
	src := `package main

import "fmt"

// This is a comment
func main() {
	fmt.Println("hello")
}
`
	count := countSubstantiveGoLines(src)
	if count < 4 || count > 7 {
		t.Errorf("expected 4-7 substantive lines, got %d", count)
	}
}

func TestDiffExportedFuncs(t *testing.T) {
	old := []string{"A", "B", "C"}
	newF := []string{"A", "B", "C", "D", "E"}

	added := diffExportedFuncs(newF, old)
	if len(added) != 2 {
		t.Fatalf("expected 2 added funcs, got %d: %v", len(added), added)
	}
	if added[0] != "D" || added[1] != "E" {
		t.Errorf("expected [D E], got %v", added)
	}
}

func TestIsExportedName(t *testing.T) {
	if !isExportedName("Hello") {
		t.Error("Hello should be exported")
	}
	if isExportedName("hello") {
		t.Error("hello should not be exported")
	}
	if isExportedName("") {
		t.Error("empty string should not be exported")
	}
}
