package agent

// Nil Map Write Detection in Go Code
//
// Problem: AI coding agents frequently produce Go code that declares a map
// variable but writes to it before initialization, causing a runtime panic:
// "assignment to entry in nil map" or "panic: runtime error: index out of range".
//
// In Go, the zero value of a map is nil. A nil map is valid for read operations
// (returns the zero value) but PANICS on any write operation:
//
//	var m map[string]int
//	m["key"] = 1  // PANIC: assignment to entry in nil map
//
// This is one of the most common runtime panics in Go code generated by LLMs,
// because the model declares the map type but forgets the make() initialization.
//
// Competitor analysis:
//   - Claude Code: no automatic detection (relies on go vet / tests catching it)
//   - Cursor: no automatic detection (golangci-lint may catch via gochecknoglobals)
//   - Cline/OpenHands: reactive only -- caught by tests or production panics
//   - Aider: no automatic detection
//   - GitHub Copilot: sometimes warns via lint integration
//
// go vet does NOT detect nil map writes. staticcheck's S1023 is unrelated.
// This check provides zero-dependency static detection at write time in <1ms.
//
// Approach: AST-based analysis. For each function, find map variables that are:
//  1. Declared as var m map[K]V (or m := someNilMap) WITHOUT a subsequent make()
//  2. Then written to via m[key] = value or m[key] += value
//
// False positive mitigation:
//   - Only flags maps declared in the SAME function (not params or receivers)
//   - If the map is assigned via make() or a map literal anywhere before the write,
//     it is NOT flagged
//   - If the map is reassigned from another map (which may be initialized), NOT flagged
//   - Delta-aware: only flags patterns newly introduced by this edit

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
)

// nilMapWriteInstance represents a detected nil map write.
type nilMapWriteInstance struct {
	posStr   string // human-readable position
	mapName  string // variable name of the nil map
	funcName string // enclosing function — map variable names are function-scoped,
	// so the delta key must include it to distinguish same-named maps in
	// different functions (#222)
}

// checkNilMapWrite detects writes to nil (uninitialized) map variables in Go code.
// Delta-aware: only flags instances newly introduced by this edit.
func checkNilMapWrite(filePath, oldContent, newContent string) string {
	if filepath.Ext(filePath) != ".go" || strings.TrimSpace(newContent) == "" {
		return ""
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, newContent, parser.AllErrors)
	if err != nil {
		return ""
	}

	var instances []nilMapWriteInstance

	ast.Inspect(file, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok {
			return true
		}
		if fn.Body == nil {
			return true
		}

		instances = append(instances, findNilMapWritesInFunc(fset, fn)...)
		return true
	})

	if len(instances) == 0 {
		return ""
	}

	// Delta check: find instances in old content to suppress pre-existing warnings.
	var oldInstances []nilMapWriteInstance
	if strings.TrimSpace(oldContent) != "" {
		oldFset := token.NewFileSet()
		oldFile, oldErr := parser.ParseFile(oldFset, filePath, oldContent, parser.AllErrors)
		if oldErr == nil {
			ast.Inspect(oldFile, func(n ast.Node) bool {
				fn, ok := n.(*ast.FuncDecl)
				if !ok || fn.Body == nil {
					return true
				}
				oldInstances = append(oldInstances, findNilMapWritesInFunc(oldFset, fn)...)
				return true
			})
		}
	}

	// Build a set of old fingerprints for dedup: funcName + mapName. A bare
	// mapName key suppresses same-named maps across different functions —
	// they are independent variables, so a newly introduced nil-map write
	// in a new function must still be flagged (#222).
	oldSet := make(map[string]bool, len(oldInstances))
	for _, oi := range oldInstances {
		oldSet[oi.funcName+"|"+oi.mapName] = true
	}

	var newInstances []nilMapWriteInstance
	for _, inst := range instances {
		if !oldSet[inst.funcName+"|"+inst.mapName] {
			newInstances = append(newInstances, inst)
		}
	}

	if len(newInstances) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("[nil-map-write] Maps written without make() initialization - will panic:\n")
	for _, inst := range newInstances {
		b.WriteString(fmt.Sprintf("  - %s: map '%s' needs `make()` before write.\n",
			inst.posStr, inst.mapName))
		// Note: the format string above uses two constant-joined parts as the format.
		// This is safe because the concatenation result is still a constant string with %s verbs.
	}
	b.WriteString("Note: nil maps are valid for reads (return zero value) but PANIC on any write operation.")
	return b.String()
}

// findNilMapWritesInFunc analyzes a single function for nil map write patterns.
func findNilMapWritesInFunc(fset *token.FileSet, fn *ast.FuncDecl) []nilMapWriteInstance {
	nilMaps := collectNilRiskMaps(fn.Body)
	if len(nilMaps) == 0 {
		return nil
	}
	instances := findUninitializedMapWrites(fset, fn.Body, nilMaps)
	instances = deduplicateByMapName(instances)
	fnName := "<anonymous>"
	if fn.Name != nil {
		fnName = fn.Name.Name
	}
	for i := range instances {
		instances[i].funcName = fnName
	}
	return instances
}

// collectNilRiskMaps finds var m map[K]V declarations (without initializer)
// and returns the set of variable names that are nil-risk.
func collectNilRiskMaps(body *ast.BlockStmt) map[string]bool {
	nilMaps := make(map[string]bool)
	ast.Inspect(body, func(n ast.Node) bool {
		switch decl := n.(type) {
		case *ast.AssignStmt:
			if decl.Tok == token.ASSIGN {
				for _, lhs := range decl.Lhs {
					if ident, ok := lhs.(*ast.Ident); ok {
						if isMakeMapCall(decl.Rhs) || isMapLiteral(decl.Rhs) {
							delete(nilMaps, ident.Name)
						}
					}
				}
			}
		case *ast.DeclStmt:
			genDecl, ok := decl.Decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.VAR {
				return true
			}
			for _, spec := range genDecl.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				if vs.Type != nil {
					if _, isMap := vs.Type.(*ast.MapType); isMap && len(vs.Values) == 0 {
						for _, name := range vs.Names {
							if name.Name != "_" {
								nilMaps[name.Name] = true
							}
						}
					}
				}
			}
		}
		return true
	})
	return nilMaps
}

// findUninitializedMapWrites tracks initialization state and flags writes
// to nil-risk maps that haven't been initialized yet.
func findUninitializedMapWrites(fset *token.FileSet, body *ast.BlockStmt, nilMaps map[string]bool) []nilMapWriteInstance {
	initialized := make(map[string]bool)
	var instances []nilMapWriteInstance
	ast.Inspect(body, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.AssignStmt:
			for _, lhs := range node.Lhs {
				if ident, ok := lhs.(*ast.Ident); ok && nilMaps[ident.Name] {
					if node.Tok == token.ASSIGN && len(node.Rhs) > 0 {
						initialized[ident.Name] = true
					}
				}
				if idx, ok := lhs.(*ast.IndexExpr); ok {
					instances = append(instances, checkNilMapWriteInstance(fset, idx, nilMaps, initialized)...)
				}
			}
		case *ast.IncDecStmt:
			if idx, ok := node.X.(*ast.IndexExpr); ok {
				instances = append(instances, checkNilMapWriteInstance(fset, idx, nilMaps, initialized)...)
			}
		}
		return true
	})
	return instances
}

// checkNilMapWriteInstance returns a warning instance if the index expression
// writes to a nil-risk map that hasn't been initialized.
func checkNilMapWriteInstance(fset *token.FileSet, idx *ast.IndexExpr, nilMaps, initialized map[string]bool) []nilMapWriteInstance {
	ident, ok := idx.X.(*ast.Ident)
	if !ok || !nilMaps[ident.Name] || initialized[ident.Name] {
		return nil
	}
	pos := fset.Position(idx.Pos())
	return []nilMapWriteInstance{{
		posStr:  fmt.Sprintf("%s:%d", filepath.Base(pos.Filename), pos.Line),
		mapName: ident.Name,
	}}
}

// deduplicateByMapName keeps only the first occurrence per map name.
func deduplicateByMapName(instances []nilMapWriteInstance) []nilMapWriteInstance {
	seen := make(map[string]bool)
	var deduped []nilMapWriteInstance
	for _, inst := range instances {
		if !seen[inst.mapName] {
			seen[inst.mapName] = true
			deduped = append(deduped, inst)
		}
	}
	return deduped
}

// isMakeMapCall checks if any RHS expression is a make(map...) call.
func isMakeMapCall(rhs []ast.Expr) bool {
	for _, expr := range rhs {
		if call, ok := expr.(*ast.CallExpr); ok {
			if fun, ok := call.Fun.(*ast.Ident); ok && fun.Name == "make" {
				if len(call.Args) > 0 {
					if _, isMap := call.Args[0].(*ast.MapType); isMap {
						return true
					}
				}
			}
		}
	}
	return false
}

// isMapLiteral checks if any RHS expression is a map literal (map[K]V{...}).
func isMapLiteral(rhs []ast.Expr) bool {
	for _, expr := range rhs {
		if cl, ok := expr.(*ast.CompositeLit); ok {
			if _, isMap := cl.Type.(*ast.MapType); isMap {
				return true
			}
		}
	}
	return false
}
