package harness

import (
	"strings"
	"testing"
)

// Helper: parse a spec and return the first requirement's details.
func parseSingleReq(t *testing.T, spec string) *SpecRequirement {
	t.Helper()
	doc := ParseSpec(spec)
	if len(doc.Requirements) == 0 {
		t.Fatal("expected at least 1 requirement, got 0")
	}
	return &doc.Requirements[0]
}

func TestParseSpec_TitleAndOverview(t *testing.T) {
	spec := `# User Authentication Feature

## Overview
This feature adds OAuth-based login to the application.
It should support Google and GitHub providers.

## Requirements
`
	doc := ParseSpec(spec)
	if doc.Title != "User Authentication Feature" {
		t.Errorf("title = %q", doc.Title)
	}
	if !strings.Contains(doc.Overview, "OAuth-based login") {
		t.Errorf("overview missing expected text: %q", doc.Overview)
	}
	if !strings.Contains(doc.Overview, "Google and GitHub") {
		t.Errorf("overview missing second line: %q", doc.Overview)
	}
}

func TestParseSpec_RequirementWithIDAndTitle(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Login page
A login page with email and password.
`
	req := parseSingleReq(t, spec)
	if req.ID != "REQ-1" {
		t.Errorf("ID = %q, want REQ-1", req.ID)
	}
	if req.Title != "Login page" {
		t.Errorf("Title = %q, want 'Login page'", req.Title)
	}
	if !strings.Contains(req.Description, "email and password") {
		t.Errorf("Description = %q", req.Description)
	}
}

func TestParseSpec_AutoGeneratedID(t *testing.T) {
	spec := `# Test

## Requirements

### First requirement without explicit ID
Some description.
`
	doc := ParseSpec(spec)
	if len(doc.Requirements) != 1 {
		t.Fatalf("expected 1 requirement, got %d", len(doc.Requirements))
	}
	if doc.Requirements[0].ID != "REQ-1" {
		t.Errorf("auto ID = %q, want REQ-1", doc.Requirements[0].ID)
	}
}

func TestParseSpec_AcceptanceCriteria(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Feature A
Description here.
- Acceptance: Must validate input
- Acceptance: Must return 200 on success
- Criteria: Must handle errors gracefully
`
	req := parseSingleReq(t, spec)
	if len(req.AcceptanceCriteria) != 3 {
		t.Fatalf("expected 3 acceptance criteria, got %d: %v", len(req.AcceptanceCriteria), req.AcceptanceCriteria)
	}
	if req.AcceptanceCriteria[0] != "Must validate input" {
		t.Errorf("criteria[0] = %q", req.AcceptanceCriteria[0])
	}
	if req.AcceptanceCriteria[1] != "Must return 200 on success" {
		t.Errorf("criteria[1] = %q", req.AcceptanceCriteria[1])
	}
}

func TestParseSpec_ImplicitAcceptanceCriteria(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Feature A
Description.
- Must validate input format
- Should show error on failure
`
	req := parseSingleReq(t, spec)
	if len(req.AcceptanceCriteria) != 2 {
		t.Fatalf("expected 2 implicit criteria, got %d: %v", len(req.AcceptanceCriteria), req.AcceptanceCriteria)
	}
}

func TestParseSpec_Dependencies(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Base feature
Description.

### REQ-2: Dependent feature
- Depends on: REQ-1
Description.
`
	doc := ParseSpec(spec)
	if len(doc.Requirements) != 2 {
		t.Fatalf("expected 2 requirements, got %d", len(doc.Requirements))
	}
	req2 := &doc.Requirements[1]
	if len(req2.DependsOn) != 1 || req2.DependsOn[0] != "REQ-1" {
		t.Errorf("DependsOn = %v, want [REQ-1]", req2.DependsOn)
	}
}

func TestParseSpec_MultipleDependencies(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: A
### REQ-2: B
### REQ-3: C
- Depends on: REQ-1, REQ-2
`
	doc := ParseSpec(spec)
	req3 := &doc.Requirements[2]
	if len(req3.DependsOn) != 2 {
		t.Fatalf("expected 2 deps, got %v", req3.DependsOn)
	}
}

func TestParseSpec_Priority(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: High priority feature
- Priority: high
Description.
`
	req := parseSingleReq(t, spec)
	if req.Priority != "high" {
		t.Errorf("Priority = %q, want 'high'", req.Priority)
	}
}

func TestParseSpec_SelfReferenceRemoved(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Self-referencing
- Depends on: REQ-1
Description.
`
	doc := ParseSpec(spec)
	if len(doc.Requirements[0].DependsOn) != 0 {
		t.Errorf("self-reference should be removed, got %v", doc.Requirements[0].DependsOn)
	}
}

func TestParseSpec_DesignNotes(t *testing.T) {
	spec := `# Test

## Overview
Overview text.

## Requirements

### REQ-1: Feature A
Desc.

## Design Decisions
Use PKCE flow.
Use JWT tokens.
`
	doc := ParseSpec(spec)
	if !strings.Contains(doc.DesignNotes, "PKCE") {
		t.Errorf("DesignNotes = %q", doc.DesignNotes)
	}
	if !strings.Contains(doc.DesignNotes, "JWT") {
		t.Errorf("DesignNotes missing JWT: %q", doc.DesignNotes)
	}
}

func TestParseSpec_DifferentIDPrefixes(t *testing.T) {
	prefixes := []string{"FR-", "AC-", "US-", "TASK-"}
	for _, pfx := range prefixes {
		spec := "# Test\n\n## Requirements\n\n### " + pfx + "5: Some feature\nDesc.\n"
		doc := ParseSpec(spec)
		if len(doc.Requirements) != 1 {
			t.Fatalf("[%s] expected 1 req, got %d", pfx, len(doc.Requirements))
		}
		want := pfx + "5"
		if doc.Requirements[0].ID != want {
			t.Errorf("[%s] ID = %q, want %q", pfx, doc.Requirements[0].ID, want)
		}
	}
}

func TestParseSpec_EmptySpec(t *testing.T) {
	doc := ParseSpec("")
	if doc.Title != "" {
		t.Errorf("title should be empty")
	}
	if len(doc.Requirements) != 0 {
		t.Errorf("expected 0 requirements")
	}
}

func TestParseSpec_MinimalSpec(t *testing.T) {
	spec := "# Just a title"
	doc := ParseSpec(spec)
	if doc.Title != "Just a title" {
		t.Errorf("title = %q", doc.Title)
	}
}

// --- SpecToTasks tests ---

func TestSpecToTasks_BasicConversion(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: Login page
- Acceptance: Form validates
Description.

### REQ-2: Dashboard
- Acceptance: Shows user info
- Depends on: REQ-1
`
	doc := ParseSpec(spec)
	tasks, reqMap := SpecToTasks(doc, SpecToTasksOptions{
		EntryPoint: "harness",
	})

	if len(tasks) != 2 {
		t.Fatalf("expected 2 tasks, got %d", len(tasks))
	}
	if tasks[0].SpecRef != "REQ-1" {
		t.Errorf("task[0] SpecRef = %q, want REQ-1", tasks[0].SpecRef)
	}
	if tasks[1].SpecRef != "REQ-2" {
		t.Errorf("task[1] SpecRef = %q, want REQ-2", tasks[1].SpecRef)
	}
	// Check dependency mapping: REQ-2 depends on REQ-1 → task[1] depends on task[0]
	if len(tasks[1].DependsOn) != 1 {
		t.Fatalf("task[1] DependsOn = %v, want 1 dep", tasks[1].DependsOn)
	}
	if tasks[1].DependsOn[0] != tasks[0].ID {
		t.Errorf("task[1] DependsOn[0] = %q, want task[0].ID = %q", tasks[1].DependsOn[0], tasks[0].ID)
	}
	// Check reqMap
	if reqMap["REQ-1"] != tasks[0].ID {
		t.Errorf("reqMap[REQ-1] = %q", reqMap["REQ-1"])
	}
	// Check acceptance criteria preserved
	if len(tasks[0].AcceptanceCriteria) != 1 {
		t.Errorf("task[0] acceptance criteria = %v", tasks[0].AcceptanceCriteria)
	}
}

func TestSpecToTasks_SequentialChain(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: A
### REQ-2: B
### REQ-3: C
`
	doc := ParseSpec(spec)
	tasks, _ := SpecToTasks(doc, SpecToTasksOptions{
		SequentialChain: true,
	})

	if len(tasks) != 3 {
		t.Fatalf("expected 3 tasks, got %d", len(tasks))
	}
	// task[0] should have no deps
	if len(tasks[0].DependsOn) != 0 {
		t.Errorf("task[0] should have no deps, got %v", tasks[0].DependsOn)
	}
	// task[1] depends on task[0]
	if len(tasks[1].DependsOn) != 1 || tasks[1].DependsOn[0] != tasks[0].ID {
		t.Errorf("task[1] deps = %v", tasks[1].DependsOn)
	}
	// task[2] depends on task[1]
	if len(tasks[2].DependsOn) != 1 || tasks[2].DependsOn[0] != tasks[1].ID {
		t.Errorf("task[2] deps = %v", tasks[2].DependsOn)
	}
}

func TestSpecToTasks_NoSequentialChain(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: A
### REQ-2: B
`
	doc := ParseSpec(spec)
	tasks, _ := SpecToTasks(doc, SpecToTasksOptions{
		SequentialChain: false,
	})

	if len(tasks[0].DependsOn) != 0 {
		t.Errorf("task[0] should have no deps")
	}
	if len(tasks[1].DependsOn) != 0 {
		t.Errorf("task[1] should have no deps without chain, got %v", tasks[1].DependsOn)
	}
}

func TestSpecToTasks_GoalContainsTitle(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: Implement login
The login page should have email/password.
`
	doc := ParseSpec(spec)
	tasks, _ := SpecToTasks(doc, SpecToTasksOptions{})

	if !strings.Contains(tasks[0].Goal, "Implement login") {
		t.Errorf("Goal should contain title: %q", tasks[0].Goal)
	}
}

func TestSpecToTasks_Metadata(t *testing.T) {
	spec := `# My Feature

## Requirements

### REQ-1: Something
- Priority: high
Description.
`
	doc := ParseSpec(spec)
	tasks, _ := SpecToTasks(doc, SpecToTasksOptions{})

	if !strings.Contains(tasks[0].Metadata, "spec_ref=REQ-1") {
		t.Errorf("Metadata should contain spec_ref: %q", tasks[0].Metadata)
	}
	if !strings.Contains(tasks[0].Metadata, "priority=high") {
		t.Errorf("Metadata should contain priority: %q", tasks[0].Metadata)
	}
}

func TestSpecToTasks_NilDoc(t *testing.T) {
	tasks, reqMap := SpecToTasks(nil, SpecToTasksOptions{})
	if tasks != nil {
		t.Errorf("expected nil tasks")
	}
	if reqMap != nil {
		t.Errorf("expected nil reqMap")
	}
}

func TestSpecToTasks_ContextAssigned(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: A
`
	doc := ParseSpec(spec)
	tasks, _ := SpecToTasks(doc, SpecToTasksOptions{
		ContextName: "backend",
		ContextPath: "internal/api",
	})

	if tasks[0].ContextName != "backend" {
		t.Errorf("ContextName = %q", tasks[0].ContextName)
	}
	if tasks[0].ContextPath != "internal/api" {
		t.Errorf("ContextPath = %q", tasks[0].ContextPath)
	}
}

// --- ValidateSpec tests ---

func TestValidateSpec_NoErrors(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: Base
- Acceptance: Works

### REQ-2: Extended
- Depends on: REQ-1
- Acceptance: Also works
`
	doc := ParseSpec(spec)
	result := ValidateSpec(doc)
	if result.HasErrors() {
		t.Errorf("expected no errors, got: %v", result.Errors)
	}
}

func TestValidateSpec_UnresolvedDependency(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: A
- Depends on: REQ-999
`
	doc := ParseSpec(spec)
	result := ValidateSpec(doc)
	if !result.HasErrors() {
		t.Errorf("expected error for unresolved dep")
	}
	if !strings.Contains(result.Errors[0], "REQ-999") {
		t.Errorf("error should mention REQ-999: %v", result.Errors)
	}
}

func TestValidateSpec_NoAcceptanceCriteria(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: A
Some description.
`
	doc := ParseSpec(spec)
	result := ValidateSpec(doc)
	if len(result.Warnings) == 0 {
		t.Errorf("expected warning for missing acceptance criteria")
	}
}

func TestValidateSpec_CircularDependency(t *testing.T) {
	spec := `# Feature

## Requirements

### REQ-1: A
- Depends on: REQ-2

### REQ-2: B
- Depends on: REQ-1
`
	doc := ParseSpec(spec)
	result := ValidateSpec(doc)
	if !result.HasErrors() {
		t.Fatalf("expected error for circular dep, got none")
	}
	found := false
	for _, e := range result.Errors {
		if strings.Contains(e, "circular") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected circular dependency error, got: %v", result.Errors)
	}
}

func TestValidateSpec_EmptyDoc(t *testing.T) {
	result := ValidateSpec(nil)
	if !result.HasErrors() {
		t.Errorf("expected error for nil doc")
	}
}

func TestValidateSpec_NoRequirements(t *testing.T) {
	doc := ParseSpec("# Just a title")
	result := ValidateSpec(doc)
	if len(result.Warnings) == 0 {
		t.Errorf("expected warning for no requirements")
	}
}

// --- FormatSpecSummary tests ---

func TestFormatSpecSummary(t *testing.T) {
	spec := `# User Auth

## Requirements

### REQ-1: Login page
- Acceptance: Validates input

### REQ-2: Dashboard
- Depends on: REQ-1
- Priority: high
`
	doc := ParseSpec(spec)
	summary := FormatSpecSummary(doc)

	if !strings.Contains(summary, "User Auth") {
		t.Errorf("summary should contain title")
	}
	if !strings.Contains(summary, "2 requirements") {
		t.Errorf("summary should contain count")
	}
	if !strings.Contains(summary, "REQ-1") {
		t.Errorf("summary should contain REQ-1")
	}
	if !strings.Contains(summary, "(1 criteria)") {
		t.Errorf("summary should show criteria count")
	}
}

func TestFormatSpecSummary_EmptyDoc(t *testing.T) {
	summary := FormatSpecSummary(nil)
	if summary == "" {
		t.Errorf("summary should not be empty")
	}
}

// --- Edge case tests ---

func TestParseSpec_NonRequirementSections(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Real requirement
Desc.

## Other Section
This should not be parsed as a requirement.

### Not a requirement
This is in a non-requirements section.
`
	doc := ParseSpec(spec)
	if len(doc.Requirements) != 1 {
		t.Errorf("expected 1 requirement, got %d", len(doc.Requirements))
	}
}

func TestParseSpec_DescriptionWithMultipleLines(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Feature
Line one of description.
Line two of description.
- Acceptance: Must work
`
	req := parseSingleReq(t, spec)
	if !strings.Contains(req.Description, "Line one") {
		t.Errorf("missing line one: %q", req.Description)
	}
	if !strings.Contains(req.Description, "Line two") {
		t.Errorf("missing line two: %q", req.Description)
	}
}

func TestParseSpec_FeatureSectionAlias(t *testing.T) {
	spec := `# Test

## Features

### REQ-1: Feature A
Desc.
`
	doc := ParseSpec(spec)
	if len(doc.Requirements) != 1 {
		t.Errorf("expected 1 requirement from Features section, got %d", len(doc.Requirements))
	}
}

func TestSpecToTasks_AllTasksHaveIDs(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: A
### REQ-2: B
### REQ-3: C
`
	doc := ParseSpec(spec)
	tasks, _ := SpecToTasks(doc, SpecToTasksOptions{})

	ids := make(map[string]bool)
	for _, task := range tasks {
		if task.ID == "" {
			t.Error("task has empty ID")
		}
		if ids[task.ID] {
			t.Errorf("duplicate task ID: %s", task.ID)
		}
		ids[task.ID] = true
	}
}

func TestParseSpec_WindowsLineEndings(t *testing.T) {
	spec := "# Test\r\n\r\n## Requirements\r\n\r\n### REQ-1: Feature\r\nDescription.\r\n"
	doc := ParseSpec(spec)
	if len(doc.Requirements) != 1 {
		t.Errorf("expected 1 requirement, got %d", len(doc.Requirements))
	}
}

func TestParseSpec_InlineAcceptanceCriteria(t *testing.T) {
	spec := `# Test

## Requirements

### REQ-1: Feature
Acceptance: Must validate
Priority: high
Depends on: REQ-0
`
	req := parseSingleReq(t, spec)
	// These are inline (non-bullet) forms with key: value
	if req.Priority != "high" {
		t.Errorf("Priority = %q", req.Priority)
	}
	// Note: "Acceptance: Must validate" as a non-bullet line has key="acceptance"
	// and value="Must validate" — should be captured
	found := false
	for _, ac := range req.AcceptanceCriteria {
		if strings.Contains(ac, "Must validate") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected acceptance criteria from inline, got %v", req.AcceptanceCriteria)
	}
}
