package config

import (
	"regexp"
	"strconv"
	"strings"
)

const defaultContextWindow = 128000
const defaultMaxOutputTokens = 16384

type modelCapability struct {
	ContextWindow   int
	MaxOutputTokens int
	SupportsVision  bool
}

// knownModelCapabilities maps exact model name (lowercased) to its capabilities.
// Auto-generated by: go run scripts/sync-model-caps.go
// Source: https://github.com/charmbracelet/catwalk/tree/main/internal/providers/configs
var knownModelCapabilities = map[string]modelCapability{
	"ai21/jamba-large-1.7":                               {ContextWindow: 256000, MaxOutputTokens: 2048},
	"alibaba/qwen-3-14b":                                 {ContextWindow: 40960, MaxOutputTokens: 8000},
	"alibaba/qwen-3-235b":                                {ContextWindow: 131000, MaxOutputTokens: 8000},
	"alibaba/qwen-3-30b":                                 {ContextWindow: 40960, MaxOutputTokens: 8000},
	"alibaba/qwen-3-32b":                                 {ContextWindow: 128000, MaxOutputTokens: 8000},
	"alibaba/qwen-3.6-max-preview":                       {ContextWindow: 240000, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/qwen3-235b-a22b-thinking":                   {ContextWindow: 131072, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/qwen3-coder":                                {ContextWindow: 262144, MaxOutputTokens: 8000},
	"alibaba/qwen3-coder-30b-a3b":                        {ContextWindow: 262144, MaxOutputTokens: 8000},
	"alibaba/qwen3-coder-next":                           {ContextWindow: 256000, MaxOutputTokens: 8000},
	"alibaba/qwen3-coder-plus":                           {ContextWindow: 1000000, MaxOutputTokens: 8000},
	"alibaba/qwen3-max":                                  {ContextWindow: 262144, MaxOutputTokens: 8000},
	"alibaba/qwen3-max-preview":                          {ContextWindow: 262144, MaxOutputTokens: 8000},
	"alibaba/qwen3-max-thinking":                         {ContextWindow: 256000, MaxOutputTokens: 8000},
	"alibaba/qwen3-vl-thinking":                          {ContextWindow: 131072, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/qwen3.5-flash":                              {ContextWindow: 1000000, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/qwen3.5-plus":                               {ContextWindow: 1000000, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/qwen3.6-27b":                                {ContextWindow: 256000, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/qwen3.6-plus":                               {ContextWindow: 1000000, MaxOutputTokens: 8000, SupportsVision: true},
	"alibaba/tongyi-deepresearch-30b-a3b":                {ContextWindow: 131072, MaxOutputTokens: 65536},
	"amazon/nova-2-lite-v1":                              {ContextWindow: 1000000, MaxOutputTokens: 32767, SupportsVision: true},
	"amazon/nova-lite-v1":                                {ContextWindow: 300000, MaxOutputTokens: 2560, SupportsVision: true},
	"amazon/nova-micro-v1":                               {ContextWindow: 128000, MaxOutputTokens: 2560},
	"amazon/nova-premier-v1":                             {ContextWindow: 1000000, MaxOutputTokens: 16000, SupportsVision: true},
	"amazon/nova-pro-v1":                                 {ContextWindow: 300000, MaxOutputTokens: 2560, SupportsVision: true},
	"anthropic.claude-haiku-4-5-20251001-v1:0":           {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic.claude-opus-4-1-20250805-v1:0":            {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"anthropic.claude-opus-4-20250514-v1:0":              {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"anthropic.claude-opus-4-5-20251101-v1:0":            {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic.claude-opus-4-6-v1":                       {ContextWindow: 1000000, MaxOutputTokens: 126000, SupportsVision: true},
	"anthropic.claude-opus-4-7":                          {ContextWindow: 1000000, MaxOutputTokens: 126000, SupportsVision: true},
	"anthropic.claude-sonnet-4-20250514-v1:0":            {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic.claude-sonnet-4-5-20250929-v1:0":          {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic.claude-sonnet-4-6":                        {ContextWindow: 1000000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic/claude-3-haiku":                           {ContextWindow: 200000, MaxOutputTokens: 2048, SupportsVision: true},
	"anthropic/claude-3.5-haiku":                         {ContextWindow: 200000, MaxOutputTokens: 4096, SupportsVision: true},
	"anthropic/claude-3.7-sonnet":                        {ContextWindow: 200000, MaxOutputTokens: 8000, SupportsVision: true},
	"anthropic/claude-haiku-4.5":                         {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"anthropic/claude-opus-4":                            {ContextWindow: 200000, MaxOutputTokens: 16000, SupportsVision: true},
	"anthropic/claude-opus-4.1":                          {ContextWindow: 200000, MaxOutputTokens: 16000, SupportsVision: true},
	"anthropic/claude-opus-4.5":                          {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"anthropic/claude-opus-4.6":                          {ContextWindow: 1000000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic/claude-opus-4.6-fast":                     {ContextWindow: 1000000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic/claude-opus-4.7":                          {ContextWindow: 1000000, MaxOutputTokens: 64000, SupportsVision: true},
	"anthropic/claude-sonnet-4":                          {ContextWindow: 1000000, MaxOutputTokens: 32000, SupportsVision: true},
	"anthropic/claude-sonnet-4.5":                        {ContextWindow: 1000000, MaxOutputTokens: 32000, SupportsVision: true},
	"anthropic/claude-sonnet-4.6":                        {ContextWindow: 1000000, MaxOutputTokens: 64000, SupportsVision: true},
	"arcee-ai/trinity-large-preview":                     {ContextWindow: 131000, MaxOutputTokens: 13100},
	"arcee-ai/trinity-large-thinking":                    {ContextWindow: 262144, MaxOutputTokens: 131072},
	"arcee-ai/trinity-large-thinking:free":               {ContextWindow: 262144, MaxOutputTokens: 40000},
	"arcee-ai/trinity-mini":                              {ContextWindow: 131072, MaxOutputTokens: 65536},
	"arcee-ai/virtuoso-large":                            {ContextWindow: 131072, MaxOutputTokens: 32000},
	"arcee-trinity-large-thinking":                       {ContextWindow: 256000, MaxOutputTokens: 65536},
	"baidu/cobuddy:free":                                 {ContextWindow: 131072, MaxOutputTokens: 32768},
	"baidu/ernie-4.5-21b-a3b":                            {ContextWindow: 120000, MaxOutputTokens: 4000},
	"baidu/ernie-4.5-vl-28b-a3b":                         {ContextWindow: 30000, MaxOutputTokens: 4000, SupportsVision: true},
	"bytedance-seed/seed-1.6":                            {ContextWindow: 262144, MaxOutputTokens: 16384, SupportsVision: true},
	"bytedance-seed/seed-1.6-flash":                      {ContextWindow: 262144, MaxOutputTokens: 16384, SupportsVision: true},
	"bytedance-seed/seed-2.0-lite":                       {ContextWindow: 262144, MaxOutputTokens: 65536, SupportsVision: true},
	"bytedance-seed/seed-2.0-mini":                       {ContextWindow: 262144, MaxOutputTokens: 65536, SupportsVision: true},
	"bytedance/seed-1.6":                                 {ContextWindow: 256000, MaxOutputTokens: 8000},
	"bytedance/ui-tars-1.5-7b":                           {ContextWindow: 128000, SupportsVision: true},
	"claude-haiku-4-5-20251001":                          {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-haiku-4.5":                                   {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"claude-opus-4-1-20250805":                           {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"claude-opus-4-20250514":                             {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"claude-opus-4-5":                                    {ContextWindow: 198000, MaxOutputTokens: 32768, SupportsVision: true},
	"claude-opus-4-5-20251101":                           {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-opus-4-6":                                    {ContextWindow: 1000000, MaxOutputTokens: 126000, SupportsVision: true},
	"claude-opus-4-6-fast":                               {ContextWindow: 1000000, MaxOutputTokens: 128000, SupportsVision: true},
	"claude-opus-4-7":                                    {ContextWindow: 1000000, MaxOutputTokens: 126000, SupportsVision: true},
	"claude-opus-4.5":                                    {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"claude-opus-4.7":                                    {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-sonnet-4-20250514":                           {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-sonnet-4-5":                                  {ContextWindow: 198000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-sonnet-4-5-20250929":                         {ContextWindow: 200000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-sonnet-4-6":                                  {ContextWindow: 1000000, MaxOutputTokens: 64000, SupportsVision: true},
	"claude-sonnet-4.5":                                  {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"claude-sonnet-4.6":                                  {ContextWindow: 200000, MaxOutputTokens: 32000, SupportsVision: true},
	"codex-mini-latest":                                  {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"cohere/command-a":                                   {ContextWindow: 256000, MaxOutputTokens: 8000},
	"cohere/command-r-08-2024":                           {ContextWindow: 128000, MaxOutputTokens: 2000},
	"cohere/command-r-plus-08-2024":                      {ContextWindow: 128000, MaxOutputTokens: 2000},
	"deepseek-ai/deepseek-r1-0528-tee":                   {ContextWindow: 163840, MaxOutputTokens: 65536},
	"deepseek-ai/deepseek-v3-0324-tee":                   {ContextWindow: 163840, MaxOutputTokens: 65536},
	"deepseek-ai/deepseek-v3.1-tee":                      {ContextWindow: 163840, MaxOutputTokens: 65536},
	"deepseek-ai/deepseek-v3.2":                          {ContextWindow: 163000, MaxOutputTokens: 16300},
	"deepseek-ai/deepseek-v3.2-fast":                     {ContextWindow: 8000, MaxOutputTokens: 800},
	"deepseek-ai/deepseek-v3.2-tee":                      {ContextWindow: 131072, MaxOutputTokens: 65536},
	"deepseek-ai/deepseek-v3.2:fireworks-ai":             {ContextWindow: 163840, MaxOutputTokens: 8192},
	"deepseek-ai/deepseek-v4-pro:fireworks-ai":           {ContextWindow: 1048576, MaxOutputTokens: 8192},
	"deepseek-chat":                                      {ContextWindow: 128000, MaxOutputTokens: 4000},
	"deepseek-reasoner":                                  {ContextWindow: 128000, MaxOutputTokens: 32000},
	"deepseek-v3.2":                                      {ContextWindow: 160000, MaxOutputTokens: 32768},
	"deepseek-v4-flash":                                  {ContextWindow: 1000000, MaxOutputTokens: 32768},
	"deepseek-v4-pro":                                    {ContextWindow: 1000000, MaxOutputTokens: 32768},
	"deepseek/deepseek-chat":                             {ContextWindow: 64000, MaxOutputTokens: 8000},
	"deepseek/deepseek-chat-v3-0324":                     {ContextWindow: 163840, MaxOutputTokens: 32768},
	"deepseek/deepseek-chat-v3.1":                        {ContextWindow: 163840, MaxOutputTokens: 16384},
	"deepseek/deepseek-r1":                               {ContextWindow: 64000, MaxOutputTokens: 8000},
	"deepseek/deepseek-r1-0528":                          {ContextWindow: 163840, MaxOutputTokens: 81920},
	"deepseek/deepseek-v3":                               {ContextWindow: 163840, MaxOutputTokens: 8000},
	"deepseek/deepseek-v3.1":                             {ContextWindow: 163840, MaxOutputTokens: 8000},
	"deepseek/deepseek-v3.1-terminus":                    {ContextWindow: 163840, MaxOutputTokens: 16384},
	"deepseek/deepseek-v3.2":                             {ContextWindow: 163840, MaxOutputTokens: 81920},
	"deepseek/deepseek-v3.2-exp":                         {ContextWindow: 163840, MaxOutputTokens: 32768},
	"deepseek/deepseek-v3.2-thinking":                    {ContextWindow: 128000, MaxOutputTokens: 8000},
	"deepseek/deepseek-v4-flash":                         {ContextWindow: 1048576, MaxOutputTokens: 192000},
	"deepseek/deepseek-v4-pro":                           {ContextWindow: 1048576, MaxOutputTokens: 192000},
	"e2ee-qwen3-30b-a3b-p":                               {ContextWindow: 256000, MaxOutputTokens: 32768},
	"e2ee-qwen3-5-122b-a10b":                             {ContextWindow: 128000, MaxOutputTokens: 32768, SupportsVision: true},
	"e2ee-qwen3-vl-30b-a3b-p":                            {ContextWindow: 128000, MaxOutputTokens: 4096, SupportsVision: true},
	"essentialai/rnj-1-instruct":                         {ContextWindow: 32768, MaxOutputTokens: 3276},
	"gemini-2.5-flash":                                   {ContextWindow: 1048576, MaxOutputTokens: 50000, SupportsVision: true},
	"gemini-2.5-pro":                                     {ContextWindow: 1048576, MaxOutputTokens: 50000, SupportsVision: true},
	"gemini-3-1-pro-preview":                             {ContextWindow: 1000000, MaxOutputTokens: 32768, SupportsVision: true},
	"gemini-3-flash-preview":                             {ContextWindow: 1048576, MaxOutputTokens: 50000, SupportsVision: true},
	"gemini-3-pro-preview":                               {ContextWindow: 1048576, MaxOutputTokens: 64000, SupportsVision: true},
	"gemini-3.1-pro-preview":                             {ContextWindow: 1048576, MaxOutputTokens: 64000, SupportsVision: true},
	"gemini-3.1-pro-preview-customtools":                 {ContextWindow: 1048576, MaxOutputTokens: 64000, SupportsVision: true},
	"gemma-4-uncensored":                                 {ContextWindow: 256000, MaxOutputTokens: 8192, SupportsVision: true},
	"glm-4.5":                                            {ContextWindow: 131072, MaxOutputTokens: 49152},
	"glm-4.5-air":                                        {ContextWindow: 131072, MaxOutputTokens: 49152},
	"glm-4.5v":                                           {ContextWindow: 65536, MaxOutputTokens: 8192, SupportsVision: true},
	"glm-4.6":                                            {ContextWindow: 204800, MaxOutputTokens: 102400},
	"glm-4.6v":                                           {ContextWindow: 131072, MaxOutputTokens: 65536, SupportsVision: true},
	"glm-4.7":                                            {ContextWindow: 204800, MaxOutputTokens: 98000},
	"glm-4.7-flash":                                      {ContextWindow: 200000, MaxOutputTokens: 65550},
	"glm-5":                                              {ContextWindow: 204800, MaxOutputTokens: 65536},
	"glm-5-turbo":                                        {ContextWindow: 200000, MaxOutputTokens: 128000},
	"glm-5.1":                                            {ContextWindow: 204800, MaxOutputTokens: 65536},
	"google-gemma-3-27b-it":                              {ContextWindow: 198000, MaxOutputTokens: 16384, SupportsVision: true},
	"google-gemma-4-26b-a4b-it":                          {ContextWindow: 256000, MaxOutputTokens: 8192, SupportsVision: true},
	"google-gemma-4-31b-it":                              {ContextWindow: 256000, MaxOutputTokens: 8192, SupportsVision: true},
	"google/gemini-2.0-flash":                            {ContextWindow: 1048576, MaxOutputTokens: 8000, SupportsVision: true},
	"google/gemini-2.0-flash-001":                        {ContextWindow: 1048576, MaxOutputTokens: 4096, SupportsVision: true},
	"google/gemini-2.0-flash-lite":                       {ContextWindow: 1048576, MaxOutputTokens: 8000, SupportsVision: true},
	"google/gemini-2.0-flash-lite-001":                   {ContextWindow: 1048576, MaxOutputTokens: 4096, SupportsVision: true},
	"google/gemini-2.5-flash":                            {ContextWindow: 1048576, MaxOutputTokens: 32767, SupportsVision: true},
	"google/gemini-2.5-flash-lite":                       {ContextWindow: 1048576, MaxOutputTokens: 32767, SupportsVision: true},
	"google/gemini-2.5-flash-lite-preview-09-2025":       {ContextWindow: 1048576, MaxOutputTokens: 32767, SupportsVision: true},
	"google/gemini-2.5-pro":                              {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-2.5-pro-preview":                      {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-2.5-pro-preview-05-06":                {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-3-flash":                              {ContextWindow: 1000000, MaxOutputTokens: 8000, SupportsVision: true},
	"google/gemini-3-flash-preview":                      {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-3-pro-preview":                        {ContextWindow: 1000000, MaxOutputTokens: 8000, SupportsVision: true},
	"google/gemini-3.1-flash-lite":                       {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-3.1-flash-lite-preview":               {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-3.1-pro-preview":                      {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemini-3.1-pro-preview-customtools":          {ContextWindow: 1048576, MaxOutputTokens: 32768, SupportsVision: true},
	"google/gemma-3-12b-it":                              {ContextWindow: 131072, MaxOutputTokens: 8192, SupportsVision: true},
	"google/gemma-3-27b-it":                              {ContextWindow: 131072, MaxOutputTokens: 8192, SupportsVision: true},
	"google/gemma-4-26b-a4b-it":                          {ContextWindow: 262144, MaxOutputTokens: 131072, SupportsVision: true},
	"google/gemma-4-26b-a4b-it:free":                     {ContextWindow: 262144, MaxOutputTokens: 16384, SupportsVision: true},
	"google/gemma-4-31b-it":                              {ContextWindow: 262144, MaxOutputTokens: 8192, SupportsVision: true},
	"google/gemma-4-31b-it:free":                         {ContextWindow: 262144, MaxOutputTokens: 16384, SupportsVision: true},
	"google/gemma-4-31b-turbo-tee":                       {ContextWindow: 131072, MaxOutputTokens: 65536, SupportsVision: true},
	"gpt-3.5-turbo":                                      {ContextWindow: 16384, MaxOutputTokens: 4096},
	"gpt-4":                                              {ContextWindow: 32768, MaxOutputTokens: 4096},
	"gpt-4-0125-preview":                                 {ContextWindow: 128000, MaxOutputTokens: 4096},
	"gpt-4.1":                                            {ContextWindow: 1047576, MaxOutputTokens: 50000, SupportsVision: true},
	"gpt-4.1-mini":                                       {ContextWindow: 1047576, MaxOutputTokens: 50000, SupportsVision: true},
	"gpt-4.1-nano":                                       {ContextWindow: 1047576, MaxOutputTokens: 50000, SupportsVision: true},
	"gpt-4.5-preview":                                    {ContextWindow: 128000, MaxOutputTokens: 50000, SupportsVision: true},
	"gpt-4o":                                             {ContextWindow: 128000, MaxOutputTokens: 20000, SupportsVision: true},
	"gpt-4o-mini":                                        {ContextWindow: 128000, MaxOutputTokens: 20000, SupportsVision: true},
	"gpt-5":                                              {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5-codex":                                        {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5-mini":                                         {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5-nano":                                         {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.1":                                            {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.1-codex":                                      {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.1-codex-max":                                  {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.1-codex-mini":                                 {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.2":                                            {ContextWindow: 264000, MaxOutputTokens: 64000, SupportsVision: true},
	"gpt-5.2-codex":                                      {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.3-codex":                                      {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.4":                                            {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.4-mini":                                       {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.4-nano":                                       {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.4-pro":                                        {ContextWindow: 1050000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.5":                                            {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-5.5-pro":                                        {ContextWindow: 1050000, MaxOutputTokens: 128000, SupportsVision: true},
	"gpt-oss-120b":                                       {ContextWindow: 131072, MaxOutputTokens: 25000},
	"grok-3":                                             {ContextWindow: 131072, MaxOutputTokens: 13107},
	"grok-3-mini":                                        {ContextWindow: 131072, MaxOutputTokens: 13107},
	"grok-4":                                             {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4-1-fast":                                      {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4-1-fast-non-reasoning":                        {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4-20":                                          {ContextWindow: 2000000, MaxOutputTokens: 128000, SupportsVision: true},
	"grok-4-3":                                           {ContextWindow: 1000000, MaxOutputTokens: 32000, SupportsVision: true},
	"grok-4-fast":                                        {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4-fast-non-reasoning":                          {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4.20":                                          {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4.20-non-reasoning":                            {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-4.3":                                           {ContextWindow: 200000, MaxOutputTokens: 20000, SupportsVision: true},
	"grok-41-fast":                                       {ContextWindow: 1000000, MaxOutputTokens: 30000, SupportsVision: true},
	"grok-code-fast":                                     {ContextWindow: 131072, MaxOutputTokens: 13107},
	"grok-code-fast-1":                                   {ContextWindow: 128000, MaxOutputTokens: 64000},
	"ibm-granite/granite-4.1-8b":                         {ContextWindow: 131072, MaxOutputTokens: 65536},
	"inception/mercury-2":                                {ContextWindow: 128000, MaxOutputTokens: 25000},
	"inception/mercury-coder-small":                      {ContextWindow: 32000, MaxOutputTokens: 8000},
	"inclusionai/ling-2.6-1t":                            {ContextWindow: 262144, MaxOutputTokens: 16384},
	"inclusionai/ling-2.6-flash":                         {ContextWindow: 262144, MaxOutputTokens: 16384},
	"inclusionai/ring-2.6-1t:free":                       {ContextWindow: 262144, MaxOutputTokens: 32768},
	"kimi-for-coding":                                    {ContextWindow: 262144, MaxOutputTokens: 32768, SupportsVision: true},
	"kimi-k2-5":                                          {ContextWindow: 256000, MaxOutputTokens: 65536, SupportsVision: true},
	"kimi-k2-6":                                          {ContextWindow: 256000, MaxOutputTokens: 65536, SupportsVision: true},
	"kwaipilot/kat-coder-pro-v2":                         {ContextWindow: 256000, MaxOutputTokens: 40000},
	"llama-3.2-3b":                                       {ContextWindow: 128000, MaxOutputTokens: 4096},
	"llama-3.3-70b":                                      {ContextWindow: 128000, MaxOutputTokens: 4096},
	"meituan/longcat-flash-chat":                         {ContextWindow: 128000, MaxOutputTokens: 8000},
	"mercury-2":                                          {ContextWindow: 128000, MaxOutputTokens: 50000},
	"meta-llama/llama-3.1-70b-instruct":                  {ContextWindow: 131072, MaxOutputTokens: 8192},
	"meta-llama/llama-3.3-70b-instruct":                  {ContextWindow: 131072, MaxOutputTokens: 13107},
	"meta-llama/llama-3.3-70b-instruct:free":             {ContextWindow: 65536, MaxOutputTokens: 6553},
	"meta-llama/llama-3.3-70b-instruct:groq":             {ContextWindow: 131072, MaxOutputTokens: 8192},
	"meta-llama/llama-4-scout":                           {ContextWindow: 1310720, MaxOutputTokens: 4096, SupportsVision: true},
	"meta-llama/llama-4-scout-17b-16e-instruct:groq":     {ContextWindow: 131072, MaxOutputTokens: 8192},
	"meta-llama/meta-llama-3.1-8b-instruct":              {ContextWindow: 131072, MaxOutputTokens: 13107},
	"meta/llama-3.1-70b":                                 {ContextWindow: 128000, MaxOutputTokens: 8000},
	"meta/llama-3.1-8b":                                  {ContextWindow: 128000, MaxOutputTokens: 8000},
	"meta/llama-3.2-11b":                                 {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"meta/llama-3.2-90b":                                 {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"meta/llama-3.3-70b":                                 {ContextWindow: 128000, MaxOutputTokens: 8000},
	"meta/llama-4-maverick":                              {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"meta/llama-4-scout":                                 {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"minimax-m2":                                         {ContextWindow: 200000, MaxOutputTokens: 20000},
	"minimax-m2.1":                                       {ContextWindow: 200000, MaxOutputTokens: 128000},
	"minimax-m2.1-highspeed":                             {ContextWindow: 200000, MaxOutputTokens: 128000},
	"minimax-m2.5":                                       {ContextWindow: 200000, MaxOutputTokens: 128000},
	"minimax-m2.5-highspeed":                             {ContextWindow: 200000, MaxOutputTokens: 128000},
	"minimax-m2.7":                                       {ContextWindow: 200000, MaxOutputTokens: 128000},
	"minimax-m2.7-highspeed":                             {ContextWindow: 200000, MaxOutputTokens: 128000},
	"minimax-m25":                                        {ContextWindow: 198000, MaxOutputTokens: 32768},
	"minimax-m27":                                        {ContextWindow: 198000, MaxOutputTokens: 32768},
	"minimax/minimax-m2":                                 {ContextWindow: 196608, MaxOutputTokens: 98304},
	"minimax/minimax-m2.1":                               {ContextWindow: 204800, MaxOutputTokens: 65536},
	"minimax/minimax-m2.1-lightning":                     {ContextWindow: 204800, MaxOutputTokens: 8000},
	"minimax/minimax-m2.5":                               {ContextWindow: 204800, MaxOutputTokens: 65550},
	"minimax/minimax-m2.5-highspeed":                     {ContextWindow: 204800, MaxOutputTokens: 8000},
	"minimax/minimax-m2.5:free":                          {ContextWindow: 196608, MaxOutputTokens: 4096},
	"minimax/minimax-m2.7":                               {ContextWindow: 204800, MaxOutputTokens: 65536},
	"minimax/minimax-m2.7-highspeed":                     {ContextWindow: 204800, MaxOutputTokens: 8000, SupportsVision: true},
	"minimaxai/minimax-m2.5":                             {ContextWindow: 196608, MaxOutputTokens: 19660},
	"minimaxai/minimax-m2.5-fast":                        {ContextWindow: 8000, MaxOutputTokens: 800},
	"minimaxai/minimax-m2.5-tee":                         {ContextWindow: 196608, MaxOutputTokens: 65536},
	"minimaxai/minimax-m2.5:fireworks-ai":                {ContextWindow: 204800, MaxOutputTokens: 8192},
	"minimaxai/minimax-m2.7:fireworks-ai":                {ContextWindow: 196608, MaxOutputTokens: 8192},
	"mistral-small-2603":                                 {ContextWindow: 256000, MaxOutputTokens: 65536, SupportsVision: true},
	"mistral-small-3-2-24b-instruct":                     {ContextWindow: 256000, MaxOutputTokens: 16384},
	"mistral/codestral":                                  {ContextWindow: 128000, MaxOutputTokens: 4000},
	"mistral/devstral-2":                                 {ContextWindow: 256000, MaxOutputTokens: 8000},
	"mistral/devstral-small":                             {ContextWindow: 128000, MaxOutputTokens: 8000},
	"mistral/devstral-small-2":                           {ContextWindow: 256000, MaxOutputTokens: 8000},
	"mistral/ministral-3b":                               {ContextWindow: 128000, MaxOutputTokens: 4000},
	"mistral/ministral-8b":                               {ContextWindow: 128000, MaxOutputTokens: 4000},
	"mistral/mistral-medium":                             {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"mistral/mistral-small":                              {ContextWindow: 32000, MaxOutputTokens: 4000, SupportsVision: true},
	"mistral/pixtral-12b":                                {ContextWindow: 128000, MaxOutputTokens: 4000, SupportsVision: true},
	"mistral/pixtral-large":                              {ContextWindow: 128000, MaxOutputTokens: 4000, SupportsVision: true},
	"mistralai/codestral-2508":                           {ContextWindow: 256000},
	"mistralai/devstral-2512":                            {ContextWindow: 262144},
	"mistralai/devstral-medium":                          {ContextWindow: 131072},
	"mistralai/devstral-small":                           {ContextWindow: 131072},
	"mistralai/ministral-14b-2512":                       {ContextWindow: 262144, SupportsVision: true},
	"mistralai/ministral-3b-2512":                        {ContextWindow: 131072, SupportsVision: true},
	"mistralai/ministral-8b-2512":                        {ContextWindow: 262144, SupportsVision: true},
	"mistralai/mistral-7b-instruct-v0.1":                 {ContextWindow: 2824},
	"mistralai/mistral-large":                            {ContextWindow: 128000},
	"mistralai/mistral-large-2407":                       {ContextWindow: 131072},
	"mistralai/mistral-large-2411":                       {ContextWindow: 131072},
	"mistralai/mistral-large-2512":                       {ContextWindow: 262144, SupportsVision: true},
	"mistralai/mistral-medium-3":                         {ContextWindow: 131072, SupportsVision: true},
	"mistralai/mistral-medium-3-5":                       {ContextWindow: 262144, SupportsVision: true},
	"mistralai/mistral-medium-3.1":                       {ContextWindow: 131072, SupportsVision: true},
	"mistralai/mistral-nemo":                             {ContextWindow: 131072},
	"mistralai/mistral-saba":                             {ContextWindow: 32768},
	"mistralai/mistral-small-24b-instruct-2501":          {ContextWindow: 32768},
	"mistralai/mistral-small-2603":                       {ContextWindow: 262144, SupportsVision: true},
	"mistralai/mistral-small-3.1-24b-instruct":           {ContextWindow: 128000, SupportsVision: true},
	"mistralai/mistral-small-3.2-24b-instruct":           {ContextWindow: 128000, SupportsVision: true},
	"mistralai/mixtral-8x22b-instruct":                   {ContextWindow: 65536},
	"mistralai/pixtral-large-2411":                       {ContextWindow: 131072, SupportsVision: true},
	"mistralai/voxtral-small-24b-2507":                   {ContextWindow: 32000},
	"moonshotai/kimi-k2":                                 {ContextWindow: 131072},
	"moonshotai/kimi-k2-0905":                            {ContextWindow: 262144},
	"moonshotai/kimi-k2-instruct-0905":                   {ContextWindow: 131072, MaxOutputTokens: 10000},
	"moonshotai/kimi-k2-thinking":                        {ContextWindow: 262144},
	"moonshotai/kimi-k2-thinking-turbo":                  {ContextWindow: 262114, MaxOutputTokens: 8000},
	"moonshotai/kimi-k2-turbo":                           {ContextWindow: 256000, MaxOutputTokens: 8000},
	"moonshotai/kimi-k2.5":                               {ContextWindow: 262144, SupportsVision: true},
	"moonshotai/kimi-k2.5-fast":                          {ContextWindow: 8000, MaxOutputTokens: 800},
	"moonshotai/kimi-k2.5-tee":                           {ContextWindow: 262144, MaxOutputTokens: 65535, SupportsVision: true},
	"moonshotai/kimi-k2.5:fireworks-ai":                  {ContextWindow: 262144, MaxOutputTokens: 8192},
	"moonshotai/kimi-k2.6":                               {ContextWindow: 32768, SupportsVision: true},
	"moonshotai/kimi-k2.6-tee":                           {ContextWindow: 262144, MaxOutputTokens: 65535, SupportsVision: true},
	"moonshotai/kimi-k2.6:fireworks-ai":                  {ContextWindow: 262144, MaxOutputTokens: 8192},
	"nex-agi/deepseek-v3.1-nex-n1":                       {ContextWindow: 131072, MaxOutputTokens: 81920},
	"nousresearch/hermes-4-14b":                          {ContextWindow: 40960, MaxOutputTokens: 40960},
	"nousresearch/hermes-4-405b":                         {ContextWindow: 131072, MaxOutputTokens: 13107},
	"nousresearch/hermes-4-70b":                          {ContextWindow: 131072, MaxOutputTokens: 13107},
	"nvidia-nemotron-3-nano-30b-a3b":                     {ContextWindow: 128000, MaxOutputTokens: 16384},
	"nvidia-nemotron-cascade-2-30b-a3b":                  {ContextWindow: 256000, MaxOutputTokens: 32768},
	"nvidia/llama-3.3-nemotron-super-49b-v1.5":           {ContextWindow: 131072},
	"nvidia/nemotron-3-nano-30b-a3b":                     {ContextWindow: 262144},
	"nvidia/nemotron-3-nano-30b-a3b:free":                {ContextWindow: 256000},
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": {ContextWindow: 256000, SupportsVision: true},
	"nvidia/nemotron-3-super-120b-a12b":                  {ContextWindow: 262144},
	"nvidia/nemotron-3-super-120b-a12b:free":             {ContextWindow: 262144},
	"nvidia/nemotron-nano-12b-v2-vl":                     {ContextWindow: 131072, MaxOutputTokens: 8000, SupportsVision: true},
	"nvidia/nemotron-nano-12b-v2-vl:free":                {ContextWindow: 128000, SupportsVision: true},
	"nvidia/nemotron-nano-9b-v2":                         {ContextWindow: 131072},
	"nvidia/nemotron-nano-9b-v2:free":                    {ContextWindow: 128000},
	"nvidia/nvidia-nemotron-3-nano-30b-a3b":              {ContextWindow: 262144, MaxOutputTokens: 26214},
	"o3":                                                 {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"o3-mini":                                            {ContextWindow: 200000, MaxOutputTokens: 50000},
	"o3-pro":                                             {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"o4-mini":                                            {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"olafangensan-glm-4.7-flash-heretic":                 {ContextWindow: 200000, MaxOutputTokens: 24000},
	"openai-gpt-4o-2024-11-20":                           {ContextWindow: 128000, MaxOutputTokens: 16384, SupportsVision: true},
	"openai-gpt-4o-mini-2024-07-18":                      {ContextWindow: 128000, MaxOutputTokens: 16384, SupportsVision: true},
	"openai-gpt-52":                                      {ContextWindow: 256000, MaxOutputTokens: 65536},
	"openai-gpt-52-codex":                                {ContextWindow: 256000, MaxOutputTokens: 65536, SupportsVision: true},
	"openai-gpt-53-codex":                                {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"openai-gpt-54":                                      {ContextWindow: 1000000, MaxOutputTokens: 131072, SupportsVision: true},
	"openai-gpt-54-mini":                                 {ContextWindow: 400000, MaxOutputTokens: 128000, SupportsVision: true},
	"openai-gpt-54-pro":                                  {ContextWindow: 1000000, MaxOutputTokens: 128000, SupportsVision: true},
	"openai-gpt-55":                                      {ContextWindow: 1000000, MaxOutputTokens: 131072, SupportsVision: true},
	"openai-gpt-55-pro":                                  {ContextWindow: 1000000, MaxOutputTokens: 128000, SupportsVision: true},
	"openai-gpt-oss-120b":                                {ContextWindow: 128000, MaxOutputTokens: 16384},
	"openai/gpt-4-1106-preview":                          {ContextWindow: 128000, MaxOutputTokens: 2048},
	"openai/gpt-4-turbo":                                 {ContextWindow: 128000, MaxOutputTokens: 2048, SupportsVision: true},
	"openai/gpt-4-turbo-preview":                         {ContextWindow: 128000, MaxOutputTokens: 2048},
	"openai/gpt-4.1":                                     {ContextWindow: 1047576, MaxOutputTokens: 16384, SupportsVision: true},
	"openai/gpt-4.1-mini":                                {ContextWindow: 1047576, MaxOutputTokens: 104757, SupportsVision: true},
	"openai/gpt-4.1-nano":                                {ContextWindow: 1047576, MaxOutputTokens: 104757, SupportsVision: true},
	"openai/gpt-4o":                                      {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-4o-2024-05-13":                           {ContextWindow: 128000, MaxOutputTokens: 2048, SupportsVision: true},
	"openai/gpt-4o-2024-08-06":                           {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-4o-2024-11-20":                           {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-4o-audio-preview":                        {ContextWindow: 128000, MaxOutputTokens: 8192},
	"openai/gpt-4o-mini":                                 {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-4o-mini-2024-07-18":                      {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-5":                                       {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5-chat":                                  {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"openai/gpt-5-codex":                                 {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5-mini":                                  {ContextWindow: 400000, MaxOutputTokens: 40000, SupportsVision: true},
	"openai/gpt-5-nano":                                  {ContextWindow: 400000, MaxOutputTokens: 40000, SupportsVision: true},
	"openai/gpt-5-pro":                                   {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.1":                                     {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.1-chat":                                {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-5.1-codex":                               {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.1-codex-max":                           {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.1-codex-mini":                          {ContextWindow: 400000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/gpt-5.1-instant":                             {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"openai/gpt-5.1-thinking":                            {ContextWindow: 400000, MaxOutputTokens: 8000, SupportsVision: true},
	"openai/gpt-5.2":                                     {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.2-chat":                                {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-5.2-codex":                               {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.2-pro":                                 {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.3-chat":                                {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"openai/gpt-5.3-codex":                               {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.4":                                     {ContextWindow: 1050000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.4-mini":                                {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.4-nano":                                {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.4-pro":                                 {ContextWindow: 1050000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.5":                                     {ContextWindow: 1050000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-5.5-pro":                                 {ContextWindow: 1050000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-audio":                                   {ContextWindow: 128000, MaxOutputTokens: 8192},
	"openai/gpt-audio-mini":                              {ContextWindow: 128000, MaxOutputTokens: 8192},
	"openai/gpt-chat-latest":                             {ContextWindow: 400000, MaxOutputTokens: 64000, SupportsVision: true},
	"openai/gpt-oss-120b":                                {ContextWindow: 131072, MaxOutputTokens: 13107},
	"openai/gpt-oss-120b-fast":                           {ContextWindow: 8000, MaxOutputTokens: 800},
	"openai/gpt-oss-120b:cerebras":                       {ContextWindow: 131072, MaxOutputTokens: 8192},
	"openai/gpt-oss-120b:fireworks-ai":                   {ContextWindow: 131072, MaxOutputTokens: 8192},
	"openai/gpt-oss-120b:free":                           {ContextWindow: 131072, MaxOutputTokens: 65536},
	"openai/gpt-oss-120b:groq":                           {ContextWindow: 131072, MaxOutputTokens: 8192},
	"openai/gpt-oss-20b":                                 {ContextWindow: 131072, MaxOutputTokens: 65536},
	"openai/gpt-oss-20b:fireworks-ai":                    {ContextWindow: 131072, MaxOutputTokens: 8192},
	"openai/gpt-oss-20b:free":                            {ContextWindow: 131072, MaxOutputTokens: 4096},
	"openai/gpt-oss-20b:groq":                            {ContextWindow: 131072, MaxOutputTokens: 8192},
	"openai/gpt-oss-safeguard-20b":                       {ContextWindow: 131072, MaxOutputTokens: 32768},
	"openai/gpt-oss-safeguard-20b:groq":                  {ContextWindow: 131072, MaxOutputTokens: 8192},
	"openai/o1":                                          {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/o3":                                          {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/o3-deep-research":                            {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/o3-mini":                                     {ContextWindow: 200000, MaxOutputTokens: 50000},
	"openai/o3-mini-high":                                {ContextWindow: 200000, MaxOutputTokens: 50000},
	"openai/o3-pro":                                      {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/o4-mini":                                     {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/o4-mini-deep-research":                       {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openai/o4-mini-high":                                {ContextWindow: 200000, MaxOutputTokens: 50000, SupportsVision: true},
	"openrouter/owl-alpha":                               {ContextWindow: 1048756, MaxOutputTokens: 131072},
	"perplexity/sonar":                                   {ContextWindow: 127072, SupportsVision: true},
	"perplexity/sonar-deep-research":                     {ContextWindow: 128000},
	"perplexity/sonar-pro":                               {ContextWindow: 200000, SupportsVision: true},
	"perplexity/sonar-pro-search":                        {ContextWindow: 200000, SupportsVision: true},
	"perplexity/sonar-reasoning-pro":                     {ContextWindow: 128000, SupportsVision: true},
	"poolside/laguna-m.1:free":                           {ContextWindow: 131072, MaxOutputTokens: 4096},
	"poolside/laguna-xs.2:free":                          {ContextWindow: 131072, MaxOutputTokens: 4096},
	"prime-intellect/intellect-3":                        {ContextWindow: 131072, MaxOutputTokens: 65536},
	"primeintellect/intellect-3":                         {ContextWindow: 131072, MaxOutputTokens: 13107},
	"qwen-3-235b-a22b-instruct-2507":                     {ContextWindow: 131072, MaxOutputTokens: 25000},
	"qwen-3-6-plus":                                      {ContextWindow: 1000000, MaxOutputTokens: 65536, SupportsVision: true},
	"qwen/qwen-2.5-72b-instruct":                         {ContextWindow: 32768, MaxOutputTokens: 8192},
	"qwen/qwen-2.5-7b-instruct":                          {ContextWindow: 32768},
	"qwen/qwen-2.5-coder-32b-instruct":                   {ContextWindow: 32768},
	"qwen/qwen-max":                                      {ContextWindow: 32768, MaxOutputTokens: 4096},
	"qwen/qwen-plus":                                     {ContextWindow: 1000000, MaxOutputTokens: 16384},
	"qwen/qwen-plus-2025-07-28":                          {ContextWindow: 1000000, MaxOutputTokens: 16384},
	"qwen/qwen-plus-2025-07-28:thinking":                 {ContextWindow: 1000000, MaxOutputTokens: 16384},
	"qwen/qwen-turbo":                                    {ContextWindow: 131072, MaxOutputTokens: 4096},
	"qwen/qwen-vl-max":                                   {ContextWindow: 131072, MaxOutputTokens: 16384, SupportsVision: true},
	"qwen/qwen-vl-plus":                                  {ContextWindow: 131072, SupportsVision: true},
	"qwen/qwen2.5-vl-72b-instruct":                       {ContextWindow: 32000, SupportsVision: true},
	"qwen/qwen3-14b":                                     {ContextWindow: 131072, MaxOutputTokens: 4096},
	"qwen/qwen3-235b-a22b":                               {ContextWindow: 131072, MaxOutputTokens: 4096},
	"qwen/qwen3-235b-a22b-2507":                          {ContextWindow: 262144, MaxOutputTokens: 131072},
	"qwen/qwen3-235b-a22b-instruct-2507":                 {ContextWindow: 262144, MaxOutputTokens: 26214},
	"qwen/qwen3-235b-a22b-thinking-2507":                 {ContextWindow: 262144, MaxOutputTokens: 262144},
	"qwen/qwen3-235b-a22b-thinking-2507-fast":            {ContextWindow: 8000, MaxOutputTokens: 800},
	"qwen/qwen3-30b-a3b":                                 {ContextWindow: 131072, MaxOutputTokens: 4096},
	"qwen/qwen3-30b-a3b-instruct-2507":                   {ContextWindow: 262144, MaxOutputTokens: 26214},
	"qwen/qwen3-30b-a3b-thinking-2507":                   {ContextWindow: 131072, MaxOutputTokens: 65536},
	"qwen/qwen3-32b":                                     {ContextWindow: 131072, MaxOutputTokens: 10000},
	"qwen/qwen3-32b-tee":                                 {ContextWindow: 40960, MaxOutputTokens: 40960},
	"qwen/qwen3-32b:groq":                                {ContextWindow: 131072, MaxOutputTokens: 8192},
	"qwen/qwen3-8b":                                      {ContextWindow: 131072, MaxOutputTokens: 4096},
	"qwen/qwen3-8b:fireworks-ai":                         {ContextWindow: 40960, MaxOutputTokens: 8192},
	"qwen/qwen3-coder":                                   {ContextWindow: 262144, MaxOutputTokens: 32768},
	"qwen/qwen3-coder-30b-a3b-instruct":                  {ContextWindow: 262144, MaxOutputTokens: 131072},
	"qwen/qwen3-coder-flash":                             {ContextWindow: 1000000, MaxOutputTokens: 32768},
	"qwen/qwen3-coder-next":                              {ContextWindow: 262144, MaxOutputTokens: 131072},
	"qwen/qwen3-coder-plus":                              {ContextWindow: 1000000, MaxOutputTokens: 32768},
	"qwen/qwen3-coder:free":                              {ContextWindow: 262000, MaxOutputTokens: 131000},
	"qwen/qwen3-max":                                     {ContextWindow: 262144, MaxOutputTokens: 16384},
	"qwen/qwen3-max-thinking":                            {ContextWindow: 262144, MaxOutputTokens: 16384},
	"qwen/qwen3-next-80b-a3b-instruct":                   {ContextWindow: 262144, MaxOutputTokens: 262144},
	"qwen/qwen3-next-80b-a3b-instruct:free":              {ContextWindow: 262144, MaxOutputTokens: 26214},
	"qwen/qwen3-next-80b-a3b-thinking":                   {ContextWindow: 128000, MaxOutputTokens: 12800},
	"qwen/qwen3-next-80b-a3b-thinking-fast":              {ContextWindow: 8000, MaxOutputTokens: 800},
	"qwen/qwen3-vl-235b-a22b-instruct":                   {ContextWindow: 131072, MaxOutputTokens: 16384, SupportsVision: true},
	"qwen/qwen3-vl-235b-a22b-thinking":                   {ContextWindow: 131072, MaxOutputTokens: 16384, SupportsVision: true},
	"qwen/qwen3-vl-30b-a3b-instruct":                     {ContextWindow: 262144, MaxOutputTokens: 8192, SupportsVision: true},
	"qwen/qwen3-vl-30b-a3b-instruct:fireworks-ai":        {ContextWindow: 262144, MaxOutputTokens: 8192},
	"qwen/qwen3-vl-30b-a3b-thinking":                     {ContextWindow: 131072, MaxOutputTokens: 16384, SupportsVision: true},
	"qwen/qwen3-vl-30b-a3b-thinking:fireworks-ai":        {ContextWindow: 262144, MaxOutputTokens: 8192},
	"qwen/qwen3-vl-32b-instruct":                         {ContextWindow: 131072, MaxOutputTokens: 16384, SupportsVision: true},
	"qwen/qwen3-vl-8b-instruct":                          {ContextWindow: 262144, MaxOutputTokens: 131072, SupportsVision: true},
	"qwen/qwen3-vl-8b-thinking":                          {ContextWindow: 131072, MaxOutputTokens: 16384, SupportsVision: true},
	"qwen/qwen3.5-122b-a10b":                             {ContextWindow: 262144, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen/qwen3.5-27b":                                   {ContextWindow: 262144, MaxOutputTokens: 40960, SupportsVision: true},
	"qwen/qwen3.5-35b-a3b":                               {ContextWindow: 262144, MaxOutputTokens: 131072, SupportsVision: true},
	"qwen/qwen3.5-397b-a17b":                             {ContextWindow: 262144, MaxOutputTokens: 26214},
	"qwen/qwen3.5-397b-a17b-fast":                        {ContextWindow: 8000, MaxOutputTokens: 800},
	"qwen/qwen3.5-397b-a17b-tee":                         {ContextWindow: 262144, MaxOutputTokens: 65536, SupportsVision: true},
	"qwen/qwen3.5-9b":                                    {ContextWindow: 262144, MaxOutputTokens: 26214, SupportsVision: true},
	"qwen/qwen3.5-flash-02-23":                           {ContextWindow: 1000000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen/qwen3.5-plus-02-15":                            {ContextWindow: 1000000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen/qwen3.5-plus-20260420":                         {ContextWindow: 1000000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen/qwen3.6-27b":                                   {ContextWindow: 262144, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen/qwen3.6-27b-tee":                               {ContextWindow: 262144, MaxOutputTokens: 65536, SupportsVision: true},
	"qwen/qwen3.6-35b-a3b":                               {ContextWindow: 262144, MaxOutputTokens: 131072, SupportsVision: true},
	"qwen/qwen3.6-flash":                                 {ContextWindow: 1000000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen/qwen3.6-max-preview":                           {ContextWindow: 262144, MaxOutputTokens: 32768},
	"qwen/qwen3.6-plus":                                  {ContextWindow: 1000000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen3-235b-a22b-instruct-2507":                      {ContextWindow: 128000, MaxOutputTokens: 16384},
	"qwen3-235b-a22b-thinking-2507":                      {ContextWindow: 128000, MaxOutputTokens: 16384},
	"qwen3-5-35b-a3b":                                    {ContextWindow: 256000, MaxOutputTokens: 65536, SupportsVision: true},
	"qwen3-5-397b-a17b":                                  {ContextWindow: 128000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen3-5-9b":                                         {ContextWindow: 256000, MaxOutputTokens: 32768, SupportsVision: true},
	"qwen3-6-27b":                                        {ContextWindow: 256000, MaxOutputTokens: 65536, SupportsVision: true},
	"qwen3-coder-480b-a35b-instruct-turbo":               {ContextWindow: 256000, MaxOutputTokens: 65536},
	"qwen3-next-80b":                                     {ContextWindow: 256000, MaxOutputTokens: 16384},
	"qwen3-vl-235b-a22b":                                 {ContextWindow: 256000, MaxOutputTokens: 16384, SupportsVision: true},
	"relace/relace-search":                               {ContextWindow: 256000, MaxOutputTokens: 64000},
	"stepfun/step-3.5-flash":                             {ContextWindow: 262144, MaxOutputTokens: 32768},
	"tencent/hy3-preview":                                {ContextWindow: 262144, MaxOutputTokens: 131072},
	"thedrummer/rocinante-12b":                           {ContextWindow: 32768, MaxOutputTokens: 16384},
	"thedrummer/unslopnemo-12b":                          {ContextWindow: 32768, MaxOutputTokens: 16384},
	"tngtech/deepseek-tng-r1t2-chimera-tee":              {ContextWindow: 163840, MaxOutputTokens: 163840},
	"upstage/solar-pro-3":                                {ContextWindow: 128000, MaxOutputTokens: 12800},
	"venice-uncensored-1-2":                              {ContextWindow: 128000, MaxOutputTokens: 8192, SupportsVision: true},
	"venice-uncensored-role-play":                        {ContextWindow: 128000, MaxOutputTokens: 4096, SupportsVision: true},
	"x-ai/grok-3":                                        {ContextWindow: 131072, MaxOutputTokens: 13107},
	"x-ai/grok-3-beta":                                   {ContextWindow: 131072, MaxOutputTokens: 13107},
	"x-ai/grok-3-mini":                                   {ContextWindow: 131072, MaxOutputTokens: 13107},
	"x-ai/grok-3-mini-beta":                              {ContextWindow: 131072, MaxOutputTokens: 13107},
	"x-ai/grok-4":                                        {ContextWindow: 256000, MaxOutputTokens: 25600, SupportsVision: true},
	"x-ai/grok-4-fast":                                   {ContextWindow: 2000000, MaxOutputTokens: 15000, SupportsVision: true},
	"x-ai/grok-4.1-fast":                                 {ContextWindow: 2000000, MaxOutputTokens: 15000, SupportsVision: true},
	"x-ai/grok-4.20":                                     {ContextWindow: 2000000, MaxOutputTokens: 200000, SupportsVision: true},
	"x-ai/grok-4.3":                                      {ContextWindow: 1000000, MaxOutputTokens: 100000, SupportsVision: true},
	"x-ai/grok-code-fast-1":                              {ContextWindow: 256000, MaxOutputTokens: 5000},
	"xai/grok-3":                                         {ContextWindow: 131072, MaxOutputTokens: 8000},
	"xai/grok-3-fast":                                    {ContextWindow: 131072, MaxOutputTokens: 8000},
	"xai/grok-3-mini":                                    {ContextWindow: 131072, MaxOutputTokens: 8000},
	"xai/grok-3-mini-fast":                               {ContextWindow: 131072, MaxOutputTokens: 8000},
	"xai/grok-4":                                         {ContextWindow: 256000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4-fast-non-reasoning":                      {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4-fast-reasoning":                          {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.1-fast-non-reasoning":                    {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.1-fast-reasoning":                        {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.20-multi-agent":                          {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.20-multi-agent-beta":                     {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.20-non-reasoning":                        {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.20-non-reasoning-beta":                   {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.20-reasoning":                            {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.20-reasoning-beta":                       {ContextWindow: 2000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-4.3":                                       {ContextWindow: 1000000, MaxOutputTokens: 8000, SupportsVision: true},
	"xai/grok-code-fast-1":                               {ContextWindow: 256000, MaxOutputTokens: 8000},
	"xiaomi/mimo-v2-flash":                               {ContextWindow: 262144, MaxOutputTokens: 32768},
	"xiaomi/mimo-v2-omni":                                {ContextWindow: 262144, MaxOutputTokens: 32768, SupportsVision: true},
	"xiaomi/mimo-v2-pro":                                 {ContextWindow: 1048576, MaxOutputTokens: 65536},
	"xiaomi/mimo-v2.5":                                   {ContextWindow: 1048576, MaxOutputTokens: 65536, SupportsVision: true},
	"xiaomi/mimo-v2.5-pro":                               {ContextWindow: 1048576, MaxOutputTokens: 65536},
	"xiaomimimo/mimo-v2-flash-tee":                       {ContextWindow: 262144, MaxOutputTokens: 65536},
	"z-ai-glm-5-turbo":                                   {ContextWindow: 200000, MaxOutputTokens: 32768},
	"z-ai-glm-5v-turbo":                                  {ContextWindow: 200000, MaxOutputTokens: 32768, SupportsVision: true},
	"z-ai/glm-4-32b":                                     {ContextWindow: 128000, MaxOutputTokens: 12800},
	"z-ai/glm-4.5":                                       {ContextWindow: 131072, MaxOutputTokens: 49152},
	"z-ai/glm-4.5-air":                                   {ContextWindow: 131072, MaxOutputTokens: 48000},
	"z-ai/glm-4.5-air:free":                              {ContextWindow: 131072, MaxOutputTokens: 48000},
	"z-ai/glm-4.5v":                                      {ContextWindow: 65536, MaxOutputTokens: 8192, SupportsVision: true},
	"z-ai/glm-4.6":                                       {ContextWindow: 204800, MaxOutputTokens: 102400},
	"z-ai/glm-4.6v":                                      {ContextWindow: 131072, MaxOutputTokens: 12000, SupportsVision: true},
	"z-ai/glm-4.7":                                       {ContextWindow: 204800, MaxOutputTokens: 102400},
	"z-ai/glm-4.7-flash":                                 {ContextWindow: 202752, MaxOutputTokens: 101376},
	"z-ai/glm-5":                                         {ContextWindow: 204800, MaxOutputTokens: 65536},
	"z-ai/glm-5-turbo":                                   {ContextWindow: 262144, MaxOutputTokens: 65536},
	"z-ai/glm-5.1":                                       {ContextWindow: 204800, MaxOutputTokens: 65536},
	"z-ai/glm-5v-turbo":                                  {ContextWindow: 202752, MaxOutputTokens: 65536, SupportsVision: true},
	"zai-glm-4.7":                                        {ContextWindow: 131072, MaxOutputTokens: 25000},
	"zai-org-glm-4.6":                                    {ContextWindow: 198000, MaxOutputTokens: 16384},
	"zai-org-glm-4.7":                                    {ContextWindow: 198000, MaxOutputTokens: 16384},
	"zai-org-glm-4.7-flash":                              {ContextWindow: 128000, MaxOutputTokens: 16384},
	"zai-org-glm-5":                                      {ContextWindow: 198000, MaxOutputTokens: 32000},
	"zai-org-glm-5-1":                                    {ContextWindow: 200000, MaxOutputTokens: 24000},
	"zai-org/glm-4.6v":                                   {ContextWindow: 131072, MaxOutputTokens: 65536, SupportsVision: true},
	"zai-org/glm-4.7-tee":                                {ContextWindow: 202752, MaxOutputTokens: 65535},
	"zai-org/glm-4.7:cerebras":                           {ContextWindow: 204800, MaxOutputTokens: 8192},
	"zai-org/glm-4.7:fireworks-ai":                       {ContextWindow: 202752, MaxOutputTokens: 8192},
	"zai-org/glm-5":                                      {ContextWindow: 202752, MaxOutputTokens: 20275},
	"zai-org/glm-5-tee":                                  {ContextWindow: 202752, MaxOutputTokens: 65535},
	"zai-org/glm-5-turbo":                                {ContextWindow: 202752, MaxOutputTokens: 65535},
	"zai-org/glm-5.1-fp8:fireworks-ai":                   {ContextWindow: 202752, MaxOutputTokens: 8192},
	"zai-org/glm-5.1-tee":                                {ContextWindow: 202752, MaxOutputTokens: 65535},
	"zai-org/glm-5.1:fireworks-ai":                       {ContextWindow: 202752, MaxOutputTokens: 8192},
	"zai-org/glm-5:fireworks-ai":                         {ContextWindow: 202752, MaxOutputTokens: 8192},
	"zai/glm-4.5":                                        {ContextWindow: 128000, MaxOutputTokens: 8000},
	"zai/glm-4.5-air":                                    {ContextWindow: 128000, MaxOutputTokens: 8000},
	"zai/glm-4.5v":                                       {ContextWindow: 66000, MaxOutputTokens: 8000, SupportsVision: true},
	"zai/glm-4.6":                                        {ContextWindow: 200000, MaxOutputTokens: 8000},
	"zai/glm-4.6v":                                       {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"zai/glm-4.6v-flash":                                 {ContextWindow: 128000, MaxOutputTokens: 8000, SupportsVision: true},
	"zai/glm-4.7":                                        {ContextWindow: 131000, MaxOutputTokens: 8000},
	"zai/glm-4.7-flash":                                  {ContextWindow: 200000, MaxOutputTokens: 8000},
	"zai/glm-4.7-flashx":                                 {ContextWindow: 200000, MaxOutputTokens: 8000},
	"zai/glm-5":                                          {ContextWindow: 202800, MaxOutputTokens: 8000},
	"zai/glm-5-turbo":                                    {ContextWindow: 202800, MaxOutputTokens: 8000},
	"zai/glm-5.1":                                        {ContextWindow: 202800, MaxOutputTokens: 8000},
	"zai/glm-5v-turbo":                                   {ContextWindow: 200000, MaxOutputTokens: 8000, SupportsVision: true},
}

var contextWindowHintPattern = regexp.MustCompile(`(^|[^0-9])(\d+)(k|m)($|[^a-z0-9])`)

// inferContextWindow resolves an approximate input context window.
// Explicit endpoint config should override this; this heuristic exists so
// auto-compaction can track common models more accurately than a fixed 128k.
func inferContextWindow(model, protocol string) int {
	if cap, ok := lookupModelCapability(model); ok && cap.ContextWindow > 0 {
		return cap.ContextWindow
	}
	if hinted := parseContextWindowHint(model); hinted > 0 {
		return hinted
	}

	m := strings.ToLower(strings.TrimSpace(model))
	switch {
	// ─── Anthropic Claude ─────────────────────────────────────────
	case strings.Contains(m, "claude"):
		return 200000

	// ─── Google Gemini ────────────────────────────────────────────
	case strings.Contains(m, "gemini-1.5-pro"):
		return 2_000_000
	case strings.Contains(m, "gemini"):
		return 1_000_000

	// ─── OpenAI ───────────────────────────────────────────────────
	case strings.Contains(m, "gpt-5"),
		strings.Contains(m, "gpt-4.1"):
		return 1_000_000
	case strings.Contains(m, "gpt-4o"),
		strings.Contains(m, "gpt-4-turbo"):
		return 128000
	case strings.Contains(m, "o3"),
		strings.Contains(m, "o4-mini"):
		return 200000

	// ─── xAI Grok ────────────────────────────────────────────────
	case strings.Contains(m, "grok"):
		return 200000

	// ─── DeepSeek ─────────────────────────────────────────────────
	case strings.Contains(m, "deepseek"):
		return 128000

	// ─── Mistral ──────────────────────────────────────────────────
	case strings.Contains(m, "codestral"):
		return 256000
	case strings.Contains(m, "mistral-large"):
		return 128000
	case strings.Contains(m, "mistral"):
		return 32000

	// ─── Zhipu GLM ───────────────────────────────────────────────
	case strings.Contains(m, "glm-4-long"):
		return 1_000_000
	case strings.Contains(m, "glm-"):
		return 128000

	// ─── Moonshot / Kimi ─────────────────────────────────────────
	case strings.Contains(m, "kimi-k2"),
		strings.Contains(m, "kimi-k2.5"):
		return 262144
	case strings.Contains(m, "moonshot-v1-128k"),
		strings.Contains(m, "kimi"):
		return 131072
	case strings.Contains(m, "moonshot"):
		return 32768

	// ─── MiniMax ──────────────────────────────────────────────────
	case strings.Contains(m, "minimax-m1"),
		strings.Contains(m, "minimax-m2"),
		strings.Contains(m, "minimax-01"):
		return 1_000_192
	case strings.Contains(m, "minimax"):
		return 204800

	// ─── Doubao / Ark ─────────────────────────────────────────────
	case strings.Contains(m, "doubao"),
		strings.Contains(m, "ark-code"):
		return 200000

	// ─── Perplexity ──────────────────────────────────────────────
	case strings.Contains(m, "sonar-pro"):
		return 200000
	case strings.Contains(m, "sonar"):
		return 128000

	// ─── Meta Llama 4 ────────────────────────────────────────────
	case strings.Contains(m, "llama-4-scout"):
		return 10_000_000
	case strings.Contains(m, "llama-4"):
		return 1_000_000
	// ─── Meta Llama 3.x ─────────────────────────────────────────
	case strings.Contains(m, "llama-3"):
		return 128000

	// ─── Qwen ────────────────────────────────────────────────────
	case strings.Contains(m, "qwen-long"):
		return 1_000_000
	case strings.Contains(m, "qwen"):
		return 131072

	// ─── Groq hosted models ──────────────────────────────────────
	case strings.Contains(m, "mixtral-8x7b"):
		return 32768
	case strings.Contains(m, "gemma"):
		return 8192
	}

	switch strings.ToLower(strings.TrimSpace(protocol)) {
	case "anthropic":
		return 200000
	case "gemini":
		return 1_000_000
	default:
		return defaultContextWindow
	}
}

func inferMaxOutputTokens(model, protocol string) int {
	if cap, ok := lookupModelCapability(model); ok && cap.MaxOutputTokens > 0 {
		return cap.MaxOutputTokens
	}

	switch strings.ToLower(strings.TrimSpace(protocol)) {
	default:
		return defaultMaxOutputTokens
	}
}

func inferVisionSupport(model, protocol string) bool {
	if cap, ok := lookupModelCapability(model); ok && cap.SupportsVision {
		return true
	}

	m := strings.ToLower(strings.TrimSpace(model))
	switch {
	case strings.Contains(m, "claude"),
		strings.Contains(m, "gpt"),
		strings.Contains(m, "gemini"),
		strings.Contains(m, "gemma"),
		strings.Contains(m, "grok"),
		strings.Contains(m, "seed-2"),
		strings.Contains(m, "qwen3.5"),
		strings.Contains(m, "qwen-3.5"),
		strings.Contains(m, "qwen3.6"),
		strings.Contains(m, "qwen-3.6"),
		(strings.Contains(m, "glm-") && strings.Contains(m, "v")),
		strings.Contains(m, "kimi-2.5"),
		strings.Contains(m, "kimi-k2"),
		strings.Contains(m, "kimi-vl"):
		return true
	case strings.Contains(m, "glm-"),
		strings.Contains(m, "kimi"),
		strings.Contains(m, "deepseek"),
		strings.Contains(m, "mistral"),
		strings.Contains(m, "qwen"),
		strings.Contains(m, "moonshot"),
		strings.Contains(m, "minimax"),
		strings.Contains(m, "llama"):
		return false
	}

	return strings.EqualFold(strings.TrimSpace(protocol), "gemini")
}

func lookupModelCapability(model string) (modelCapability, bool) {
	cap, ok := knownModelCapabilities[strings.ToLower(strings.TrimSpace(model))]
	return cap, ok
}

func parseContextWindowHint(model string) int {
	matches := contextWindowHintPattern.FindAllStringSubmatch(strings.ToLower(model), -1)
	best := 0
	for _, match := range matches {
		if len(match) < 4 {
			continue
		}
		n, err := strconv.Atoi(match[2])
		if err != nil || n <= 0 {
			continue
		}
		switch match[3] {
		case "k":
			n *= 1000
		case "m":
			n *= 1000000
		}
		if n > best {
			best = n
		}
	}
	return best
}
