package im

// Code generated r166: mechanical transformation of the imLabel switch
// tables (origin/main 29fad0ab0, tool_format_helpers.go:52-568).
// Values are byte-identical to the pre-refactor switch returns; behavior is
// guarded by TestIMLabelGolden / TestIMLabelFallbackPins.
//
// NOTE: zh intentionally lacks delete_memory / memory_delete /
// memory_deleted (en-only keys since the tables diverged); zh lookups for
// those keys fall through to the raw-key return in imLabel, exactly as the
// old switch did.

var imLabelEn = map[string]string{

	"run_command":            "Run command",
	"read":                   "Reading",
	"read_file":              "Reading file",
	"edit_file":              "Edit file",
	"write_file":             "Write file",
	"find_files":             "Find files",
	"search":                 "Search",
	"list_directory":         "List directory",
	"fetch":                  "Fetch",
	"update_todos":           "Update todos",
	"load_skill":             "Load skill",
	"pages":                  "pages",
	"lines_extracted":        "lines extracted",
	"files":                  "files",
	"showing_first":          "showing first",
	"lines":                  "lines",
	"from_line":              "from line",
	"first_lines":            "lines",
	"no_output":              "no output",
	"no_matches":             "no matches",
	"matches":                "matches",
	"no_active_commands":     "no active commands",
	"no_active_agents":       "no active agents",
	"bg_command_started":     "Background command started",
	"bg_command":             "Background command",
	"command_stopped":        "Command stopped",
	"stop_command":           "Stop command",
	"read_output":            "Read output",
	"no_new_output":          "no new output",
	"wait_command":           "Wait command",
	"command_done":           "Command completed",
	"command_failed":         "Command failed",
	"input_sent":             "Input sent",
	"send_input":             "Send input",
	"active_commands":        "Active commands",
	"sub_task":               "Sub-task",
	"sub_task_started":       "Sub-task started",
	"sub_task_done":          "Sub-task completed",
	"sub_task_list":          "Sub-task list",
	"no_active_subtasks":     "no active sub-tasks",
	"mcp_service":            "MCP service",
	"mcp_service_list":       "MCP service list",
	"mcp_prompt":             "MCP Prompt",
	"resource_read":          "Resource read",
	"resource_content":       "Resource content",
	"skill_loaded":           "Skill loaded",
	"skill_load":             "Skill load",
	"memory_saved":           "Memory saved",
	"memory_save":            "Memory save",
	"memory_deleted":         "Memory deleted",
	"memory_delete":          "Memory delete",
	"delete_memory":          "Delete memory",
	"reply_received":         "Reply received",
	"todos":                  "Todos",
	"results":                "results",
	"team_create":            "Create team",
	"team_delete":            "Delete team",
	"teammate_spawn":         "Spawn teammate",
	"teammate_shutdown":      "Shutdown teammate",
	"send_message":           "Send message",
	"teammate_results":       "Collect team results",
	"swarm_task_create":      "Create task",
	"swarm_task_complete":    "Complete task",
	"a2a_remote":             "Remote call",
	"a2a_send_task":          "Send task",
	"team_created":           "Team created",
	"team_deleted":           "Team deleted",
	"teammate_created":       "Teammate created",
	"teammate_shutdown_done": "Teammate shut down",
	"message_sent":           "Message sent",
	"task_created":           "Task created",
	"task_completed":         "Task completed",
	"task_sent":              "Task sent",
	"read_multi":             "Read multiple files",
	"edit_multi":             "Edit multiple files",
	"write_multi":            "Write multiple files",
	"git_stage":              "Stage files",
	"git_commit":             "Commit",
	"git_show":               "Git show",
	"git_blame":              "Git blame",
	"git_branch_list":        "List branches",
	"git_staged":             "Files staged",
	"git_committed":          "Committed",
	"switch_mode":            "Switch mode",
	"mode_switched":          "Mode switched",
	"browser":                "Browser",
	"edit_notebook":          "Edit notebook",
	"delegate":               "Delegate",
	"delegated_to":           "Delegated to",
	"cron_update":            "Update cron job",
	"cron_pause":             "Pause cron job",
	"cron_resume":            "Resume cron job",
	"cron_get":               "Get cron job",
	"cron_update_done":       "Cron job updated",
	"cron_paused":            "Cron job paused",
	"cron_resumed":           "Cron job resumed",
	"spawn_agent":            "Spawn agent",
	"wait_agent":             "Wait for agent",
	"save_memory":            "Save memory",
	"config":                 "Config",
	"mobile_device":          "Mobile device",
	"im_manage":              "IM adapter",
	"git_diff":               "Git diff",
	"git_status":             "Git status",
	"git_log":                "Git log",
	"git_remote":             "Git remote",
	"git_stash":              "Git stash",
	"git_stash_list":         "Git stash list",
	"ask_user":               "Ask user",
	"command_manage":         "Manage command",
	"command_input":          "Send input",
	"files_edited":           "files edited",
	"files_written":          "files written",
	"files_failed":           "files failed",
	"edits":                  "edits",
	"failed":                 "failed",
	"errors":                 "errors",
	"cancel_agent":           "Cancelling agent",
	"task_create":            "Task created",
	"task_stopped":           "Task stopped",
	"lsp_definition":         "Go to definition",
	"lsp_references":         "Find references",
	"lsp_hover":              "Type info",
	"lsp_diagnostics":        "Diagnostics",
	"lsp_rename":             "Rename symbol",
	"lsp_symbols":            "Symbols",
	"lsp_implementation":     "Find implementations",
	"lsp_code_actions":       "Code actions",
}

var imLabelZh = map[string]string{

	"run_command":            "执行命令",
	"read":                   "读取",
	"read_file":              "读取文件",
	"edit_file":              "编辑文件",
	"write_file":             "写入文件",
	"find_files":             "查找文件",
	"search":                 "搜索",
	"list_directory":         "列出目录",
	"fetch":                  "抓取",
	"update_todos":           "更新待办列表",
	"load_skill":             "加载技能",
	"pages":                  "页",
	"lines_extracted":        "行",
	"files":                  "个文件",
	"showing_first":          "展示前",
	"lines":                  "行",
	"from_line":              "从行",
	"first_lines":            "前 %d 行",
	"no_output":              "无输出",
	"no_matches":             "无匹配",
	"matches":                "处匹配",
	"no_active_commands":     "无活动命令",
	"no_active_agents":       "无活动子任务",
	"bg_command_started":     "后台命令已启动",
	"bg_command":             "后台命令",
	"command_stopped":        "命令已停止",
	"stop_command":           "停止命令",
	"read_output":            "读取输出",
	"no_new_output":          "无新输出",
	"wait_command":           "等待命令",
	"command_done":           "命令完成",
	"command_failed":         "命令失败",
	"input_sent":             "输入已发送",
	"send_input":             "输入发送",
	"active_commands":        "活动命令",
	"sub_task":               "子任务",
	"sub_task_started":       "子任务已启动",
	"sub_task_done":          "子任务完成",
	"sub_task_list":          "子任务列表",
	"no_active_subtasks":     "无活动子任务",
	"mcp_service":            "MCP 服务",
	"mcp_service_list":       "MCP 服务列表",
	"mcp_prompt":             "MCP Prompt",
	"resource_read":          "资源读取",
	"resource_content":       "资源内容",
	"skill_loaded":           "技能已加载",
	"skill_load":             "技能加载",
	"memory_saved":           "记忆已保存",
	"memory_save":            "记忆保存",
	"reply_received":         "收到回复",
	"todos":                  "待办",
	"results":                "条结果",
	"team_create":            "创建团队",
	"team_delete":            "删除团队",
	"teammate_spawn":         "创建队友",
	"teammate_shutdown":      "关闭队友",
	"send_message":           "发送消息",
	"teammate_results":       "收集团队结果",
	"swarm_task_create":      "创建任务",
	"swarm_task_complete":    "完成任务",
	"a2a_remote":             "远程调用",
	"a2a_send_task":          "发送任务",
	"team_created":           "团队已创建",
	"team_deleted":           "团队已删除",
	"teammate_created":       "队友已创建",
	"teammate_shutdown_done": "队友已关闭",
	"message_sent":           "消息已发送",
	"task_created":           "任务已创建",
	"task_completed":         "任务已完成",
	"task_sent":              "任务已发送",
	"read_multi":             "读取多文件",
	"edit_multi":             "编辑多文件",
	"write_multi":            "写入多文件",
	"git_stage":              "暂存文件",
	"git_commit":             "提交",
	"git_show":               "Git show",
	"git_blame":              "Git blame",
	"git_branch_list":        "列出分支",
	"git_staged":             "文件已暂存",
	"git_committed":          "已提交",
	"switch_mode":            "切换模式",
	"mode_switched":          "模式已切换",
	"browser":                "浏览器",
	"edit_notebook":          "编辑笔记本",
	"delegate":               "委托",
	"delegated_to":           "委托给",
	"cron_update":            "更新定时任务",
	"cron_pause":             "暂停定时任务",
	"cron_resume":            "恢复定时任务",
	"cron_get":               "查看定时任务",
	"cron_update_done":       "定时任务已更新",
	"cron_paused":            "定时任务已暂停",
	"cron_resumed":           "定时任务已恢复",
	"spawn_agent":            "创建子代理",
	"wait_agent":             "等待子代理",
	"save_memory":            "保存记忆",
	"config":                 "配置",
	"mobile_device":          "移动设备",
	"im_manage":              "IM 适配器",
	"git_diff":               "查看差异",
	"git_status":             "查看状态",
	"git_log":                "查看日志",
	"git_remote":             "查看远程",
	"git_stash":              "储藏",
	"git_stash_list":         "储藏列表",
	"ask_user":               "询问用户",
	"command_manage":         "管理命令",
	"command_input":          "发送输入",
	"files_edited":           "个文件已编辑",
	"files_written":          "个文件已写入",
	"files_failed":           "个文件失败",
	"edits":                  "处修改",
	"failed":                 "个失败",
	"errors":                 "个错误",
	"cancel_agent":           "取消子代理",
	"task_create":            "任务已创建",
	"task_stopped":           "任务已停止",
	"lsp_definition":         "跳转定义",
	"lsp_references":         "查找引用",
	"lsp_hover":              "类型信息",
	"lsp_diagnostics":        "诊断",
	"lsp_rename":             "重命名符号",
	"lsp_symbols":            "符号",
	"lsp_implementation":     "查找实现",
	"lsp_code_actions":       "代码操作",
}
