package provider

import (
	"context"
	"encoding/json"
	"math"

	"github.com/topcheer/ggcode/internal/config"
)

// Message represents a single message in the conversation.
type Message struct {
	ID      string         `json:"id,omitempty"` // unique message ID (msg_ + ULID), generated by Manager.Add()
	Role    string         `json:"role"`         // "user", "assistant", "system"
	Content []ContentBlock `json:"content"`
}

// ContentBlock is a union type: text, image, tool call, or tool result.
type ContentBlock struct {
	Type              string          `json:"type"` // "text", "image", "tool_use", "tool_result"
	Text              string          `json:"text,omitempty"`
	ImageMIME         string          `json:"image_mime,omitempty"` // MIME type for image blocks
	ImageData         string          `json:"image_data,omitempty"` // base64-encoded image data
	ToolName          string          `json:"tool_name,omitempty"`
	ToolID            string          `json:"tool_id,omitempty"`
	Input             json.RawMessage `json:"input,omitempty"`
	Output            string          `json:"output,omitempty"`
	IsError           bool            `json:"is_error,omitempty"`
	Images            []ContentImage  `json:"images,omitempty"`             // images within a tool_result
	ReasoningContent  string          `json:"reasoning_content,omitempty"`  // DeepSeek reasoning content (must be echoed back)
	ThinkingSignature string          `json:"thinking_signature,omitempty"` // Anthropic extended thinking signature (must be echoed back)
	ThinkingData      string          `json:"thinking_data,omitempty"`      // Anthropic redacted thinking data (must be echoed back)
	Cache             bool            `json:"cache,omitempty"`              // hint for providers to apply cache_control on this block

	// Anthropic server-tool blocks (server_tool_use / web_search_tool_result /
	// web_fetch_tool_result): Raw keeps the verbatim API JSON so follow-up
	// requests echo the full exchange back losslessly (the API requires the
	// pair; a dropped result makes it re-run the tool).
	Raw json.RawMessage `json:"raw,omitempty"`
	ID  string          `json:"id,omitempty"` // server_tool_use block id

	// Anthropic server-side tool blocks (server_tool_use / web_search_tool_result
	// / web_fetch_tool_result). These execute INSIDE Anthropic's infrastructure:
	// ggcode never receives a client-side tool_use for them. The blocks are stored
	// verbatim so follow-up requests echo the full exchange back (the API requires
	// the server_tool_use + result pair on subsequent requests, and a dropped
	// result block makes the API treat the call as deferred and re-run it).
	ServerTool    string               `json:"server_tool,omitempty"`    // producing tool: "web_search" / "web_fetch"
	ServerResults []ServerSearchResult `json:"server_results,omitempty"` // web_search_tool_result payload
	ServerFetch   *ServerFetchResult   `json:"server_fetch,omitempty"`   // web_fetch_tool_result payload
	ServerError   string               `json:"server_error,omitempty"`   // error code when the server tool failed
}

// ImageBlock creates an image content block with base64-encoded data.
func ImageBlock(mime, base64Data string) ContentBlock {
	return ContentBlock{Type: "image", ImageMIME: mime, ImageData: base64Data}
}

// TextBlock creates a text content block.
func TextBlock(text string) ContentBlock {
	return ContentBlock{Type: "text", Text: text}
}

// ToolUseBlock creates a tool call content block.
func ToolUseBlock(id, name string, input json.RawMessage) ContentBlock {
	return ContentBlock{Type: "tool_use", ToolID: id, ToolName: name, Input: input}
}

// ToolResultBlock creates a tool result content block.
func ToolResultBlock(id, output string, isError bool) ContentBlock {
	return ContentBlock{Type: "tool_result", ToolID: id, Output: output, IsError: isError}
}

// ToolResultNamedBlock creates a tool result content block with the originating tool name.
func ToolResultNamedBlock(id, name, output string, isError bool) ContentBlock {
	return ContentBlock{Type: "tool_result", ToolID: id, ToolName: name, Output: output, IsError: isError}
}

// ContentImage represents an image within a tool_result block.
type ContentImage struct {
	MIME   string `json:"mime"`
	Base64 string `json:"base64"`
}

// ServerSearchResult is one web_search result, kept verbatim for round-trip
// echo: the API requires encrypted_content (and the other fields) to be
// replayed unchanged on subsequent requests.
type ServerSearchResult struct {
	Title            string `json:"title,omitempty"`
	URL              string `json:"url,omitempty"`
	EncryptedContent string `json:"encrypted_content,omitempty"`
	PageAge          string `json:"page_age,omitempty"`
}

// ServerFetchResult is the payload of a web_fetch_tool_result block. The page
// document travels by URL source (Anthropic re-resolves it server-side), so
// only the metadata is retained.
type ServerFetchResult struct {
	URL         string `json:"url,omitempty"`
	Title       string `json:"title,omitempty"`
	RetrievedAt string `json:"retrieved_at,omitempty"`
	Citations   bool   `json:"citations,omitempty"` // citations.enabled on the returned document
}

// ToolResultWithImages creates a tool result that carries both text and images.
func ToolResultWithImages(id, name, textOutput string, images []ContentImage, isError bool) ContentBlock {
	return ContentBlock{
		Type:     "tool_result",
		ToolID:   id,
		ToolName: name,
		Output:   textOutput,
		Images:   images,
		IsError:  isError,
	}
}

// TokenUsage records token consumption for a single API call.
type TokenUsage struct {
	InputTokens       int `json:"input_tokens"`
	OutputTokens      int `json:"output_tokens"`
	CacheRead         int `json:"cache_read_tokens"`
	CacheWrite        int `json:"cache_write_tokens"`
	PromptTokensTotal int `json:"prompt_tokens_total,omitempty"`
}

func (u TokenUsage) Add(delta TokenUsage) TokenUsage {
	u.InputTokens += delta.InputTokens
	u.OutputTokens += delta.OutputTokens
	u.CacheRead += delta.CacheRead
	u.CacheWrite += delta.CacheWrite
	u.PromptTokensTotal += delta.PromptTokensTotal
	return u
}

func (u TokenUsage) DisplayInputTokens() int {
	if u.CacheRead <= 0 {
		return u.InputTokens
	}
	if u.PromptTokensTotal > 0 {
		normalized := u.PromptTokensTotal - u.CacheRead
		if normalized >= 0 {
			if normalized < u.InputTokens {
				return normalized
			}
			return u.InputTokens
		}
	}
	return u.InputTokens
}

func (u TokenUsage) TotalInputTokens() int {
	if u.PromptTokensTotal > 0 {
		return u.PromptTokensTotal
	}
	return u.InputTokens
}

func (u TokenUsage) Total() int {
	return u.TotalInputTokens() + u.OutputTokens
}

func (u TokenUsage) CacheHitPercent() int {
	totalPromptTokens := u.PromptTokensTotal
	if totalPromptTokens <= 0 || totalPromptTokens < u.CacheRead {
		fallbackTotal := u.InputTokens
		if u.CacheWrite > 0 || u.CacheRead > u.InputTokens {
			fallbackTotal = u.InputTokens + u.CacheRead + u.CacheWrite
		}
		if fallbackTotal > totalPromptTokens {
			totalPromptTokens = fallbackTotal
		}
	}
	if totalPromptTokens <= 0 || u.CacheRead <= 0 {
		return 0
	}
	return int(math.Round(float64(u.CacheRead) * 100 / float64(totalPromptTokens)))
}

// StreamEvent is sent over a channel during streaming responses.
type StreamEvent struct {
	Type              StreamEventType
	Text              string        // for TextChunk, Reasoning
	ThinkingSignature string        // for Reasoning (Anthropic extended thinking signature)
	Tool              ToolCallDelta // for ToolCallChunk / ToolCallDone
	Result            string        // for ToolResult
	IsError           bool          // for ToolResult
	Usage             *TokenUsage   // for Done (nil if not final)
	Confidence        *float64      // for Done: mean token logprob of the turn (sa-74; nil = unavailable)
	Error             error         // for Error
	Truncated         bool          // for Done: true if output was cut off by length/max_tokens limit
	PolicyBlocked     bool          // for Done: true if the stream was cut by a provider policy filter (safety/recitation/blocklist/etc.) — not recoverable by continuation (#266)
	Block             ContentBlock  // for ServerTool: the complete server-side tool block (server_tool_use or result)
}

type StreamEventType int

const (
	StreamEventText StreamEventType = iota
	StreamEventToolCallChunk
	StreamEventToolCallDone
	StreamEventToolResult
	StreamEventDone
	StreamEventError
	StreamEventServerTool // Anthropic server-side tool block (web_search/web_fetch): not executable client-side
	StreamEventReasoning  // thinking/reasoning content (DeepSeek, etc.)
	StreamEventSystem     // system notification (retry status, etc.)
)

// ToolCallDelta represents a (possibly partial) tool call from a streaming response.
type ToolCallDelta struct {
	ID         string          // tool call ID (stable across chunks)
	Index      int             // position in the tool call list
	Name       string          // tool name (may be empty in early chunks)
	ServerTool bool            // true for Anthropic server_tool_use blocks (executed in-API; never a client tool call)
	Arguments  json.RawMessage // accumulated arguments so far
	// ThoughtSignature carries the Gemini thought signature attached to a
	// function call part (#1610-A); it must ride the SAME tool_use block so
	// the functionResponse can echo it back.
	ThoughtSignature []byte
}

// ToolDefinition describes a tool to the LLM provider.
type ToolDefinition struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Parameters  json.RawMessage `json:"parameters"` // JSON Schema
	// Strict enables provider-side grammar-constrained decoding for this
	// tool (OpenAI/Anthropic `strict: true`). Guarantees required fields are
	// present and types match the schema. See strict_tools.go.
	Strict bool `json:"strict,omitempty"`
	// DeferLoading marks the definition for Anthropic's server-side Tool
	// Search Tool (advanced-tool-use-2025-11-20): the schema stays out of
	// the model's context until the server search expands it via
	// tool_reference. Ignored by the OpenAI/Gemini adapters. Never set on
	// server tools themselves (the API rejects deferring the search tool).
	DeferLoading bool `json:"defer_loading,omitempty"`
}

// Provider is the interface every LLM backend must implement.
type Provider interface {
	// Name returns the provider identifier (e.g., "anthropic", "openai", "gemini").
	Name() string

	// Chat sends a non-streaming request and returns the complete response.
	// Used for token counting, summarization, and cost estimation.
	Chat(ctx context.Context, messages []Message, tools []ToolDefinition) (*ChatResponse, error)

	// ChatStream sends a streaming request and returns a channel of events.
	// The channel is closed when the stream ends.
	ChatStream(ctx context.Context, messages []Message, tools []ToolDefinition) (<-chan StreamEvent, error)

	// CountTokens returns the token count for the given messages.
	// Returns an error if the provider does not support counting.
	CountTokens(ctx context.Context, messages []Message) (int, error)
}

// MaxTokensSetter is implemented by providers that accept a per-call
// output-token budget. MCP sampling (#1592-A) uses it to honor the
// server-requested maxTokens; without it the budget was parsed and then
// silently dropped, violating the MCP sampling contract.
type MaxTokensSetter interface {
	SetMaxTokens(n int)
}

type ReasoningEffortProvider interface {
	SetReasoningEffort(effort string)
	ReasoningEffort() string
}

// TextVerbosityProvider is implemented by providers that support the GPT-5
// text.verbosity output-length control (Responses API only).
type TextVerbosityProvider interface {
	SetTextVerbosity(verbosity string)
	TextVerbosity() string
}

// ServiceTierProvider is implemented by providers that support the OpenAI
// service_tier processing-tier control (Chat Completions + Responses API).
type ServiceTierProvider interface {
	SetServiceTier(tier string)
	ServiceTier() string
}

// ServerToolsSetter is implemented by providers that support Anthropic
// server-side tools (web_search / web_fetch): tools declared once and
// executed inside the provider's infrastructure, with results returned
// in-band instead of as client-side tool_use calls.
type ServerToolsSetter interface {
	SetServerTools(tools []ServerToolConfig)
}

// ServerToolConfig declares one server-side tool. Defined in config (the
// declaration is endpoint configuration); aliased here so provider code and
// tests reference a single type.
type ServerToolConfig = config.ServerToolConfig

// ToolChoiceProvider is implemented by providers that support the
// tool_choice API parameter. Values: "auto" (default, model decides),
// "required" (force at least one tool call), "none" (disable tool calls).
// An empty string is treated as "auto" (the API default).
type ToolChoiceProvider interface {
	SetToolChoice(choice string)
	ToolChoice() string
}

// SamplingOverride is the per-call MCP sampling override snapshot
// (#2248): the sampling handler swaps ONE atomic pointer for the whole
// mutate->chat->restore window, so the main agent's concurrent Chat
// reads a consistent view instead of racing naked field writes (the
// #1612 lock serialized samplers but never the reader side).
type SamplingOverride struct {
	MaxTokens     int
	StopSequences []string
	// Temperature is the MCP sampling contract's per-call temperature
	// (#1592-A family, third member): parsed but never forwarded before,
	// so a server's temperature hint was silently ignored. 0 means "no
	// override" - matching the MCP omitempty semantics, where an absent
	// field leaves the choice to the model.
	Temperature float64
}

// SamplingOverrideSetter is implemented by providers whose request
// builders honor the atomic sampling override (#2248): override values
// win over configured defaults while set; nil means provider default.
type SamplingOverrideSetter interface {
	SetSamplingOverride(o *SamplingOverride)
	SamplingOverride() *SamplingOverride
}

// StopSequenceSetter is implemented by providers that can pass per-call
// stop sequences to the model API. MCP sampling (#2239) uses it to honor
// the server's stopSequences - parsed then dropped before, silently
// violating the sampling contract (sentinel-delimited structured output
// ran past its END marker). Symmetric getter/setter: the sampling handler
// snapshots the previous value for restore inside the shared lock window
// (#1612-A), no reflection like the legacy maxTokens path.
// StopSequenceSetter (#2239) was removed in the #2271 follow-up: since
// the #2248 override switch per-call stop sequences ride
// SamplingOverride/SamplingOverrideSetter exclusively and the Set/Get
// pair had no production caller.

// SamplingConfigProvider is implemented by providers that support temperature
// and top_p (nucleus sampling) inference parameters. Temperature controls
// randomness: 0.0 is fully deterministic, 1.0 is the default for most models.
// TopP controls nucleus sampling: 0.1 means only tokens comprising the top 10%
// probability mass are considered. Both values of 0 mean "use provider default".
type SamplingConfigProvider interface {
	SetTemperature(temp float64)
	Temperature() float64
	SetTopP(topP float64)
	TopP() float64
}

// ModelNameProvider is implemented by providers that can report their current model name.
type ModelNameProvider interface {
	ModelName() string
}

// RateLimitProvider is implemented by providers that capture rate-limit
// headers from API responses. The agent uses this to proactively warn the
// user when quotas are running low, rather than waiting for a 429 error.
type RateLimitProvider interface {
	RateLimitInfo() RateLimitInfo
}

// ChatResponse is the complete response from a non-streaming Chat call.
type ChatResponse struct {
	Message Message
	Usage   TokenUsage
	// StopReason (#1484-C) is the provider-reported stop reason, normalized
	// to the anthropic value family: "end_turn", "max_tokens",
	// "stop_sequence", "refusal" (mapped from openai content_filter /
	// gemini SAFETY), or a provider-specific lowercase string. Empty means
	// the provider did not report one — callers fall back to their own
	// heuristics. Previously the field did not exist, so the MCP sampling
	// handler guessed "max_tokens" from Usage.OutputTokens >= maxTokens,
	// which both false-positived (natural length >= budget with no
	// truncation) and made the stop_sequence branch unreachable.
	StopReason string
	// Confidence (sa-74) is the mean token logprob of the response when the
	// provider was asked for logprobs (openai logprobs / gemini
	// responseLogprobs). Research basis: logprobs quantify model confidence
	// per token and enable selective-escalation patterns in agents — flag
	// low-confidence turns for human review instead of silently proceeding
	// ("Logprobs Know Uncertainty", ACM KDD 2025; arXiv:2505.23854).
	// Anthropic does not expose logprobs, so Confidence stays nil there.
	Confidence *float64
}
