// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ggcode_plugin.proto

package ggcodeplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_ggcode_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{0}
}

type ToolDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema encoded as JSON bytes.
	// Example: {"type":"object","properties":{"query":{"type":"string"}}}
	Parameters []byte `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Optional category tags for grouping (e.g. "jira", "search").
	Categories    []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_ggcode_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ToolDefinition) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_ggcode_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ListToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool name (must match a name returned by ListTools).
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// JSON-encoded arguments (matches the tool's parameters schema).
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Runtime context from the host.
	Context       map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_ggcode_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Content string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Images  []*ResultImage         `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	// Optional hint: if non-empty, the agent will switch its working directory.
	SuggestedWorkingDir string `protobuf:"bytes,4,opt,name=suggested_working_dir,json=suggestedWorkingDir,proto3" json:"suggested_working_dir,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_ggcode_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ExecuteResponse) GetImages() []*ResultImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ExecuteResponse) GetSuggestedWorkingDir() string {
	if x != nil {
		return x.SuggestedWorkingDir
	}
	return ""
}

type ResultImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`
	Base64        string                 `protobuf:"bytes,2,opt,name=base64,proto3" json:"base64,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultImage) Reset() {
	*x = ResultImage{}
	mi := &file_ggcode_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultImage) ProtoMessage() {}

func (x *ResultImage) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultImage.ProtoReflect.Descriptor instead.
func (*ResultImage) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ResultImage) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ResultImage) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *ResultImage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResultImage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_ggcode_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{6}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_ggcode_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ggcode_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_ggcode_plugin_proto_rawDescGZIP(), []int{7}
}

var File_ggcode_plugin_proto protoreflect.FileDescriptor

const file_ggcode_plugin_proto_rawDesc = "" +
	"\n" +
	"\x13ggcode_plugin.proto\x12\x10ggcode.plugin.v1\"\x12\n" +
	"\x10ListToolsRequest\"\x86\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\fR\n" +
	"parameters\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\"K\n" +
	"\x11ListToolsResponse\x126\n" +
	"\x05tools\x18\x01 \x03(\v2 .ggcode.plugin.v1.ToolDefinitionR\x05tools\"\xc8\x01\n" +
	"\x0eExecuteRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12G\n" +
	"\acontext\x18\x03 \x03(\v2-.ggcode.plugin.v1.ExecuteRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x125\n" +
	"\x06images\x18\x03 \x03(\v2\x1d.ggcode.plugin.v1.ResultImageR\x06images\x122\n" +
	"\x15suggested_working_dir\x18\x04 \x01(\tR\x13suggestedWorkingDir\"g\n" +
	"\vResultImage\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x16\n" +
	"\x06base64\x18\x02 \x01(\tR\x06base64\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\x86\x02\n" +
	"\vToolService\x12T\n" +
	"\tListTools\x12\".ggcode.plugin.v1.ListToolsRequest\x1a#.ggcode.plugin.v1.ListToolsResponse\x12N\n" +
	"\aExecute\x12 .ggcode.plugin.v1.ExecuteRequest\x1a!.ggcode.plugin.v1.ExecuteResponse\x12Q\n" +
	"\bShutdown\x12!.ggcode.plugin.v1.ShutdownRequest\x1a\".ggcode.plugin.v1.ShutdownResponseBDZBgithub.com/topcheer/ggcode/internal/plugin/grpc/proto;ggcodepluginb\x06proto3"

var (
	file_ggcode_plugin_proto_rawDescOnce sync.Once
	file_ggcode_plugin_proto_rawDescData []byte
)

func file_ggcode_plugin_proto_rawDescGZIP() []byte {
	file_ggcode_plugin_proto_rawDescOnce.Do(func() {
		file_ggcode_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ggcode_plugin_proto_rawDesc), len(file_ggcode_plugin_proto_rawDesc)))
	})
	return file_ggcode_plugin_proto_rawDescData
}

var file_ggcode_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ggcode_plugin_proto_goTypes = []any{
	(*ListToolsRequest)(nil),  // 0: ggcode.plugin.v1.ListToolsRequest
	(*ToolDefinition)(nil),    // 1: ggcode.plugin.v1.ToolDefinition
	(*ListToolsResponse)(nil), // 2: ggcode.plugin.v1.ListToolsResponse
	(*ExecuteRequest)(nil),    // 3: ggcode.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),   // 4: ggcode.plugin.v1.ExecuteResponse
	(*ResultImage)(nil),       // 5: ggcode.plugin.v1.ResultImage
	(*ShutdownRequest)(nil),   // 6: ggcode.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),  // 7: ggcode.plugin.v1.ShutdownResponse
	nil,                       // 8: ggcode.plugin.v1.ExecuteRequest.ContextEntry
}
var file_ggcode_plugin_proto_depIdxs = []int32{
	1, // 0: ggcode.plugin.v1.ListToolsResponse.tools:type_name -> ggcode.plugin.v1.ToolDefinition
	8, // 1: ggcode.plugin.v1.ExecuteRequest.context:type_name -> ggcode.plugin.v1.ExecuteRequest.ContextEntry
	5, // 2: ggcode.plugin.v1.ExecuteResponse.images:type_name -> ggcode.plugin.v1.ResultImage
	0, // 3: ggcode.plugin.v1.ToolService.ListTools:input_type -> ggcode.plugin.v1.ListToolsRequest
	3, // 4: ggcode.plugin.v1.ToolService.Execute:input_type -> ggcode.plugin.v1.ExecuteRequest
	6, // 5: ggcode.plugin.v1.ToolService.Shutdown:input_type -> ggcode.plugin.v1.ShutdownRequest
	2, // 6: ggcode.plugin.v1.ToolService.ListTools:output_type -> ggcode.plugin.v1.ListToolsResponse
	4, // 7: ggcode.plugin.v1.ToolService.Execute:output_type -> ggcode.plugin.v1.ExecuteResponse
	7, // 8: ggcode.plugin.v1.ToolService.Shutdown:output_type -> ggcode.plugin.v1.ShutdownResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ggcode_plugin_proto_init() }
func file_ggcode_plugin_proto_init() {
	if File_ggcode_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ggcode_plugin_proto_rawDesc), len(file_ggcode_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ggcode_plugin_proto_goTypes,
		DependencyIndexes: file_ggcode_plugin_proto_depIdxs,
		MessageInfos:      file_ggcode_plugin_proto_msgTypes,
	}.Build()
	File_ggcode_plugin_proto = out.File
	file_ggcode_plugin_proto_goTypes = nil
	file_ggcode_plugin_proto_depIdxs = nil
}
