package tool

// Staging Quality Intelligence - Auto-Generated / Artifact / Vendored File Detection
//
// Problem: AI agents frequently stage files that shouldn't be committed:
//   - Build artifacts (dist/, build/, bin/, target/, out/)
//   - Auto-generated code (.pb.go, _generated.go, .min.js, Code generated by...)
//   - Vendored dependencies (vendor/, node_modules/, third_party/)
//   - Binary/executable files (.exe, .so, .dylib, .wasm)
//   - IDE/editor artifacts (.DS_Store, .idea/, .vscode/settings.json)
//   - OS-generated files (Thumbs.db, desktop.ini)
//
// These files pollute the git history, inflate repo size, and cause merge
// conflicts. They should be in .gitignore, not in commits.
//
// Competitor analysis:
//   - GitHub Copilot: no detection - relies on .gitignore
//   - Cursor: no detection
//   - Claude Code: no detection
//   - Aider: auto-adds files but doesn't warn about artifacts
//   - Husky/pre-commit framework: catches some via hook config, but not AI-aware
//
// Gap: No existing ggcode check covers this. The diff scan (diff_scan.go) checks
// ADDED LINE CONTENT for debug statements and secrets. The critical_file check
// warns when editing infrastructure files. But neither detects when the staged
// FILE ITSELF is a generated artifact that shouldn't be committed at all.
//
// This check analyzes staged file PATHS (not content) against known artifact
// patterns. Zero LLM cost, fully deterministic, non-blocking advisory.

import (
	"fmt"
	"path/filepath"
	"strings"
)

// maxStagingWarnings caps the number of files listed to avoid overwhelming context.
const maxStagingWarnings = 10

// StagingIssue categorizes a file that probably shouldn't be committed.
type StagingIssue struct {
	Path     string
	Category string // "build-artifact", "generated", "vendored", "binary", "os-artifact", "ide-artifact"
	Reason   string
}

// generatedFilePatterns matches file names that are typically auto-generated.
var generatedFilePatterns = []struct {
	pattern string
	reason  string
}{
	{".min.js", "minified JavaScript (generated by build tools)"},
	{".min.css", "minified CSS (generated by build tools)"},
	{".pb.go", "Protobuf-generated Go code"},
	{".pb.validate.go", "Protobuf validation generated code"},
	{".gen.go", "code-generated Go file"},
	{"_generated.go", "generated Go file"},
	{".generated.ts", "generated TypeScript file"},
	{".generated.js", "generated JavaScript file"},
	{"_generated.py", "generated Python file"},
	{".g.dart", "generated Dart file (freezed/json_serializable)"},
	{".freezed.dart", "generated Dart file (freezed)"},
	{".mocks.dart", "generated Dart mocks"},
	{".pb.dart", "Protobuf-generated Dart"},
	{".grpc.pb.go", "gRPC-generated Go code"},
	{".deepcopy.go", "k8s deepcopy-generated Go code"},
	{".zz_generated.go", "k8s-generated Go code"},
	{"Wire.swift", "Swift DI generated file"},
	{".h.swift", "Swift bridging header (generated)"},
}

// buildArtifactDirs matches directory prefixes that indicate build output.
var buildArtifactDirs = []struct {
	prefix string
	reason string
}{
	{"dist/", "build distribution output"},
	{"build/", "build output directory"},
	{"bin/", "compiled binary output"},
	{"out/", "build output"},
	{"target/", "build output (Rust/Maven)"},
	{".next/", "Next.js build output"},
	{".nuxt/", "Nuxt.js build output"},
	{".svelte-kit/", "SvelteKit build output"},
	{".turbo/", "Turborepo cache"},
	{".output/", "Nuxt/Nitro output"},
	{".dart_tool/", "Dart tool cache"},
	{"coverage/", "test coverage report"},
	{".coverage", "test coverage data"},
	{"__pycache__/", "Python bytecode cache"},
	{".pytest_cache/", "pytest cache"},
	{".gradle/", "Gradle build cache"},
	{".mvn/", "Maven wrapper cache"},
}

// vendoredDirs matches directory prefixes for vendored dependencies.
var vendoredDirs = []struct {
	prefix string
	reason string
}{
	{"vendor/", "Go vendored dependencies"},
	{"node_modules/", "npm/pnpm dependencies"},
	{"third_party/", "third-party vendored code"},
	{"bower_components/", "Bower dependencies"},
	{"Pods/", "CocoaPods dependencies"},
	{".cargo/registry/", "Cargo registry cache"},
	{".pub-cache/", "Dart pub cache"},
}

// binaryExtensions matches file extensions for binary/executable files.
var binaryExtensions = []string{
	".exe", ".dll", ".so", ".dylib", ".wasm",
	".o", ".obj", ".a", ".lib",
	".class", ".jar",
	".pyc", ".pyo",
	".elc",
}

// osArtifactFiles matches OS-generated files that shouldn't be committed.
var osArtifactFiles = map[string]string{
	".DS_Store":       "macOS Finder metadata",
	"Thumbs.db":       "Windows thumbnail cache",
	"desktop.ini":     "Windows desktop config",
	"ehthumbs.db":     "Windows thumbnail database",
	".LSOverride":     "macOS Launch Services override",
	"Icon\r":          "macOS custom icon",
	".Spotlight-V100": "macOS Spotlight index",
	".Trashes":        "macOS trash directory",
	".AppleDouble":    "macOS Apple Double file",
}

// ideArtifactFiles matches IDE/editor-generated files.
var ideArtifactFiles = map[string]string{
	".idea/workspace.xml":        "IntelliJ workspace state (user-specific)",
	".idea/usage.statistics.xml": "IntelliJ usage stats (user-specific)",
	".idea/shelf/":               "IntelliJ shelf (unshelved changes)",
	".vscode/settings.json":      "VS Code user settings (often machine-specific)",
	".vscode/launch.json":        "VS Code launch config (often machine-specific)",
	".project":                   "Eclipse project file (legacy)",
	".classpath":                 "Eclipse classpath (legacy)",
	".settings/":                 "Eclipse settings (legacy)",
	"*.swp":                      "Vim swap file",
	"*~":                         "Editor backup file",
	"*.swo":                      "Vim swap file",
}

// AnalyzeStagingQuality checks staged file paths against known patterns for
// auto-generated, build-artifact, vendored, binary, OS, and IDE files.
// Returns an advisory warning string listing files that likely shouldn't be
// committed. Returns empty string when no issues are found.
func AnalyzeStagingQuality(diffOutput string) string {
	if strings.TrimSpace(diffOutput) == "" {
		return ""
	}

	// Extract unique file paths from the diff.
	fileSet := make(map[string]bool)
	for _, line := range strings.Split(diffOutput, "\n") {
		if m := diffFileHeader.FindStringSubmatch(line); m != nil {
			fileSet[m[1]] = true
		}
	}

	if len(fileSet) == 0 {
		return ""
	}

	var issues []StagingIssue
	for path := range fileSet {
		issues = append(issues, checkStagingFile(path)...)
	}

	if len(issues) == 0 {
		return ""
	}

	return formatStagingIssues(issues)
}

// checkStagingFile evaluates a single file path against all artifact patterns.
func checkStagingFile(path string) []StagingIssue {
	var issues []StagingIssue
	lower := strings.ToLower(path)
	base := filepath.Base(path)

	// 1. OS-generated artifacts.
	if reason, ok := osArtifactFiles[base]; ok {
		issues = append(issues, StagingIssue{
			Path: path, Category: "os-artifact", Reason: reason,
		})
	}

	// 2. IDE/editor artifacts.
	for pattern, reason := range ideArtifactFiles {
		if stagingPatternMatch(lower, pattern) {
			issues = append(issues, StagingIssue{
				Path: path, Category: "ide-artifact", Reason: reason,
			})
			break
		}
	}

	// 3. Build artifact directories.
	// #867: HasPrefix on repo-root-relative paths never matched nested
	// monorepo artifacts ("web/dist/...", "packages/app/node_modules/...").
	// Segment-wise match: prefix must start a path segment anywhere.
	for _, d := range buildArtifactDirs {
		if hasPathPrefixSegment(lower, d.prefix) {
			issues = append(issues, StagingIssue{
				Path: path, Category: "build-artifact", Reason: d.reason,
			})
			break
		}
	}

	// 4. Vendored dependency directories.
	for _, d := range vendoredDirs {
		if hasPathPrefixSegment(lower, d.prefix) {
			issues = append(issues, StagingIssue{
				Path: path, Category: "vendored", Reason: d.reason,
			})
			break
		}
	}

	// 5. Generated code files.
	for _, p := range generatedFilePatterns {
		if strings.Contains(lower, strings.ToLower(p.pattern)) {
			issues = append(issues, StagingIssue{
				Path: path, Category: "generated", Reason: p.reason,
			})
			break
		}
	}

	// 6. Binary/executable extensions.
	for _, ext := range binaryExtensions {
		if strings.HasSuffix(lower, ext) {
			issues = append(issues, StagingIssue{
				Path: path, Category: "binary", Reason: "compiled binary file",
			})
			break
		}
	}

	// Deduplicate: if a file matched multiple patterns, keep only the first.
	if len(issues) > 1 {
		issues = issues[:1]
	}

	return issues
}

// stagingPatternMatch checks if a file path matches a glob-like pattern.
// Supports * wildcards and exact path matching.
func stagingPatternMatch(path, pattern string) bool {
	if strings.Contains(pattern, "*") {
		matched, err := filepath.Match(pattern, filepath.Base(path))
		if err == nil && matched {
			return true
		}
		// Also check full path match for patterns like ".settings/*"
		matched, err = filepath.Match(pattern, path)
		if err == nil && matched {
			return true
		}
		return false
	}
	return strings.Contains(path, pattern)
}

// formatStagingIssues formats staging quality issues into a human-readable warning.
func formatStagingIssues(issues []StagingIssue) string {
	if len(issues) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("Warning: the following staged files are likely auto-generated or " +
		"should not be committed:\n\n")

	shown := issues
	if len(shown) > maxStagingWarnings {
		shown = shown[:maxStagingWarnings]
	}

	for _, iss := range shown {
		b.WriteString(fmt.Sprintf("  - %s (%s): %s\n", iss.Path, iss.Category, iss.Reason))
	}

	if len(issues) > maxStagingWarnings {
		b.WriteString(fmt.Sprintf("  ... and %d more\n", len(issues)-maxStagingWarnings))
	}

	b.WriteString("\nConsider removing these files from staging with 'git restore --staged <file>' " +
		"and adding them to .gitignore if not already present.")

	return b.String()
}

// hasPathPrefixSegment reports whether prefix starts a path segment anywhere
// in path: at the root, or immediately after a '/'. The match must end at a
// segment boundary too (end of path or '/'), so ".coverage" does not match
// ".coveragerc" (#867).
func hasPathPrefixSegment(path, prefix string) bool {
	for i := 0; i < len(path); i++ {
		if i > 0 && path[i-1] != '/' {
			continue
		}
		if !strings.HasPrefix(path[i:], prefix) {
			continue
		}
		// Directory prefixes already end in '/': the segment boundary is
		// built into the prefix (e.g. "dist/" matching "dist/bundle.js" --
		// end points just past the '/', at the next segment's start).
		// File-like prefixes (".coverage") need an explicit boundary so
		// ".coveragerc" does not match.
		if strings.HasSuffix(prefix, "/") {
			return true
		}
		end := i + len(prefix)
		if end == len(path) || path[end] == '/' {
			return true
		}
	}
	return false
}
