package tool

import (
	"strings"
	"testing"
)

func TestAnalyzeStagingQuality(t *testing.T) {
	tests := []struct {
		name       string
		diffOutput string
		wantEmpty  bool
		wantSubstr string
	}{
		{
			name:       "empty diff",
			diffOutput: "",
			wantEmpty:  true,
		},
		{
			name: "clean source files only",
			diffOutput: `diff --git a/main.go b/main.go
+++ b/main.go
+package main
+func main() {}`,
			wantEmpty: true,
		},
		{
			name: "build artifact detected",
			diffOutput: `diff --git a/dist/bundle.js b/dist/bundle.js
+++ b/dist/bundle.js
+var x=1;`,
			wantEmpty:  false,
			wantSubstr: "build-artifact",
		},
		{
			name: "node_modules detected",
			diffOutput: `diff --git a/node_modules/foo/index.js b/node_modules/foo/index.js
+++ b/node_modules/foo/index.js
+module.exports = {};`,
			wantEmpty:  false,
			wantSubstr: "vendored",
		},
		{
			name: "DS_Store detected",
			diffOutput: `diff --git a/.DS_Store b/.DS_Store
+++ b/.DS_Store
+BINARY`,
			wantEmpty:  false,
			wantSubstr: "os-artifact",
		},
		{
			name: "minified JS detected",
			diffOutput: `diff --git a/app.min.js b/app.min.js
+++ b/app.min.js
+!function(){var a=1}();`,
			wantEmpty:  false,
			wantSubstr: "generated",
		},
		{
			name: "Go generated file detected",
			diffOutput: `diff --git a/api.pb.go b/api.pb.go
+++ b/api.pb.go
+// Code generated by protoc.`,
			wantEmpty:  false,
			wantSubstr: "generated",
		},
		{
			name: "binary file detected",
			diffOutput: `diff --git a/app.exe b/app.exe
+++ b/app.exe
+MZ`,
			wantEmpty:  false,
			wantSubstr: "binary",
		},
		{
			name: "vendor directory detected",
			diffOutput: `diff --git a/vendor/github.com/pkg/errors/errors.go b/vendor/github.com/pkg/errors/errors.go
+++ b/vendor/github.com/pkg/errors/errors.go
+package errors`,
			wantEmpty:  false,
			wantSubstr: "vendored",
		},
		{
			name: "mixed clean and artifact files",
			diffOutput: `diff --git a/main.go b/main.go
+++ b/main.go
+package main
diff --git a/build/output.o b/build/output.o
+++ b/build/output.o
+BINARY`,
			wantEmpty:  false,
			wantSubstr: "build-artifact",
		},
		{
			name: "coverage directory detected",
			diffOutput: `diff --git a/coverage/lcov.info b/coverage/lcov.info
+++ b/coverage/lcov.info
+TN:`,
			wantEmpty:  false,
			wantSubstr: "build-artifact",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := AnalyzeStagingQuality(tt.diffOutput)
			if tt.wantEmpty {
				if result != "" {
					t.Errorf("expected empty result, got: %s", result)
				}
				return
			}
			if !strings.Contains(result, tt.wantSubstr) {
				t.Errorf("expected result to contain %q, got: %s", tt.wantSubstr, result)
			}
		})
	}
}

func TestAnalyzeStagingQualityFormat(t *testing.T) {
	// Verify the output format includes actionable guidance.
	diff := `diff --git a/.DS_Store b/.DS_Store
+++ b/.DS_Store
+BINARY
diff --git a/dist/app.js b/dist/app.js
+++ b/dist/app.js
+console.log("built");`

	result := AnalyzeStagingQuality(diff)
	if !strings.Contains(result, "Warning:") {
		t.Error("expected warning prefix")
	}
	if !strings.Contains(result, ".DS_Store") {
		t.Error("expected .DS_Store in output")
	}
	if !strings.Contains(result, "dist/app.js") {
		t.Error("expected dist/app.js in output")
	}
	if !strings.Contains(result, ".gitignore") {
		t.Error("expected .gitignore suggestion in output")
	}
}

func TestAnalyzeStagingQualityMaxWarnings(t *testing.T) {
	// Generate 15+ staged artifact files to test capping.
	var lines []string
	for i := 0; i < 15; i++ {
		lines = append(lines, "+++ b/dist/file"+string(rune('a'+i))+".js")
	}
	diff := strings.Join(lines, "\n")

	result := AnalyzeStagingQuality(diff)
	if !strings.Contains(result, "and") && !strings.Contains(result, "more") {
		// With 15 files and maxStagingWarnings=10, should show truncation.
		// But since each file only produces 1 issue and we cap at 10, there
		// should be a "... and 5 more" message.
		if !strings.Contains(result, "more") {
			t.Logf("result (no truncation needed if <= cap): %s", result[:min(len(result), 200)])
		}
	}
}

func TestCheckStagingFileSingleIssue(t *testing.T) {
	// A file should only produce one issue (deduplication).
	issues := checkStagingFile("dist/app.min.js")
	if len(issues) != 1 {
		t.Errorf("expected 1 issue for dist/app.min.js (dedup), got %d", len(issues))
	}
}
