org.gradle.jvmargs=-Xmx4G -Djdk.net.hosts.file=/tmp/gradle-hosts
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
android.ndkVersion=27.1.12297006
